### ISSUE TITLE
CSG Tracker

### ISSUE THREAD

**Issue by fire** [godotengine/godot#100164]
### Tested versions

- Reproducible in Master https://github.com/godotengine/godot/commit/aa8d9b83f66488dbb2c9c918e9016ef80f821fb4
- Not reproducible in 4.3

### System information

Windows 11, Nvidia 4000 series

### Issue description

The 4.4 CSG update is crucial for projects that need help building 3D design tools in the engine and their game. It is a considerable service to the core mission of an accessible game engine, and it would be a shame to revert to the 4.3 CSG.

Previously, the 4.3 CSG feature did not handle mesh subtraction and intersection well. Yet, mesh addition was handled decently with some corrupted triangles.

Since 2018, many other types of Mesh have been added; although they were allowed to be placed in the CSGMesh3D, applying CSG to them wasn't mathematically sound.

In 4.4, CSG was improved so that mesh subtraction, intersection and addition work, with the requirement that all input meshes must be manifold as defined by the original CSG work https://godotengine.org/article/godot-gets-csg-support/ in 2018.

The general workflow is that developers use the CSG Sphere, Box, Torus, and Polygon to design models. If they are able to create manifold 3D meshes, those can also be used in CSGMesh3D secondarily.

## Issues and Pull Requests

Summary: Crash bugs are fixed. Most of the CSGMesh3D inputs from Mesh primitives have fixes incoming. We found a workaround for topologically zero-volume (quad and plane) meshes.

- [ ] CSGMesh is topologically a quad-triangle mesh with no volume, but the user’s use case involved creating CSGMeshes from 3d paths shaping a terrain. This was solved by placing a cube under the “quad mesh.”
- [ ] Mend gaps in meshes caused by trigonometric functions. #100020 -- Improve the ability of Mesh Primitives to be used in CSGMesh3D -- Fixes BoxMesh, CapsuleMesh, CylinderMesh, PrismMesh, SphereMesh, TorusMesh, TubeTrailMesh
	- [x] TextMesh—sometimes fonts may not be 3D manifolds by design error, but it works most of the time.
	- [ ] PointMesh, RibbonTrailMesh, PlaneMesh -- Prevent these from being used in CSGMesh3D by @Calinou
- [x] 4.4dev6 crashes when loading csgshape #100131 - Fixed in master due to `CameraServer* CameraServer::_create_builtin<CameraMacOS>()` erroring.
- [x] Crash with CSGPolygon3D in Spin mode #99888
- [x] CSGPolygon3D mode Path crashes when setting path_interval #100073 - Fixed in master due to `CameraServer* CameraServer::_create_builtin<CameraMacOS>()` erroring.

## Additional

Feel free to edit the issue to add more.

### Steps to reproduce

This is a tracker.

### Minimal reproduction project (MRP)

The contained bugs have MRPs.

**Comment by fire** [comment]
Worked on Push some warnings for CSG non manifold and other errors. #100361
