### ISSUE TITLE
[TRACKER] Particles issues

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#10239]
### 3D/Multimesh:
- [x] 3D particles blink when set a velocity of 0 https://github.com/godotengine/godot/issues/10183 (bug)
- [x] Particles don't fire again when unmarking "One Shot" https://github.com/godotengine/godot/issues/10181 (bug/enhancement)
- [x] Emission shape "directed points" is unable to emit in negative directions https://github.com/godotengine/godot/issues/10233 (bug)
- [x]  Shape mode "points" and "directed points": impossible to move emission point in negative axis https://github.com/godotengine/godot/issues/10236 (bug/enhancement)
- [x] Particles 3D - gravity does not work if initial velocity iz zero #10349 (bug)
- [x] Particles 3D initial velocity always random #10348 (bug)
- [x] 3D particles emission gets chunky if framerate is slowed down  https://github.com/godotengine/godot/issues/10186 (archived)
- [x] 3D particles are extremely laggy when seen close https://github.com/godotengine/godot/issues/10185 (archived)
- [x] MultiMesh does not change color of instances #10217 (archived)
- [x] Particles and Particles2D preprocess property doesn't do anything #12460 (bug)
- [x] Ability to convert buildin shaders and spatial material to text #10242 (enhancement)
- [x] Not emitted particles affects performance #19507 (bug)
- [x] 3D particles cannot rotate https://github.com/godotengine/godot/issues/10182 (bug)
- [ ] MultiMesh rendering issues in grid like setup  #10253 (bug)
- [x] Setting transform of meshes in MultiMesh produces an error #12595 (bug)
- [ ] Shape mode "points": points can be defined only in distance from 0 to 1 from the origin https://github.com/godotengine/godot/issues/10235 (enhancement)
- [x] color gradient / albedo of mesh is preferred over particle material https://github.com/godotengine/godot/issues/9781 (enhancement)
- [x] Change particles to use emission rate rather than max allowed particles.  https://github.com/godotengine/godot/issues/4294 (enhancement)
- [ ] Trail divisor is not very good https://github.com/godotengine/godot/issues/10363 (enhancement)
- [x] 3.0 Particles Shader: impossible to calculate current lifetime #11538 (enhancement)

### Couple less strict issues:
- [x] Particle 3d issues #10234 (bug)
- [x] Particle System Improvement  #6377 (feature proposal)
- [ ] Enhanced 2D and 3D particle system & tooling #4250 (feature proposal)
- [x]  Particle System Enhancements #19358

### 2D: 
 - [ ] Observing fast moving Particles2D from a fast moving object causes visual glitch. #6373 (bug)
- [ ]  emission_stopped signal for particles2d node  #10954 (enhancement)
- [ ] Particles with "one shot" enabled gets "emitting" turned off #17903
- [x] Particle2D emitting settings create unexpected results. #4003 (bug)
- [x] Particles2d random initial velocity doesn't seem to do anything #10668 (bug)
- [x] 2D particles are glitchy  https://github.com/godotengine/godot-demo-projects/issues/58 (bug in demo)

**Comment by kubecz3k** [comment]
Some issues for the future:
- [ ] LOD is not working (also for particles) https://github.com/godotengine/godot/issues/8806 (bug)
- [ ] Add Soft Particle to blend particle's edges #3834 (enhancement)
- [ ] Quick trails, vector fields and collisions for particles  https://github.com/godotengine/godot/issues/8583 (feature proposal)
- [ ] Particles bouncing off of collision objects? #3994 (feature proposal)

Hope didn't miss anything...

**Comment by maxim-sheronov** [comment]
Hi. Is it possible to use custom mesh as emission_shape for particles 3d? For example, I want emission from surface (or volume) of my 3d model. I did not find such issues, maybe it can be added to this list.

**Comment by volzhs** [comment]
https://mobile.twitter.com/reduzio/status/850156344871198720
https://mobile.twitter.com/reduzio/status/850077188275798018

**Comment by maxim-sheronov** [comment]
@volzhs thanks! The second post is what I am asking about.

**Comment by MrMaidx** [comment]
Some of these have already been closed. It would be nice to mark them so it doesn't look like particles are completely broken. :D

**Comment by curly-brace** [comment]
are those all known issues? because for me particles disappear in editor if i rotate view to some point, particles do not respect any settings concerning circular motions and orbiting, they cannot be made rotated according to their velocity (like pointing outwards of emission point), they do not scale.

**Comment by n-pigeon** [comment]
@curly-brace 
If you find any bugs in Godot. Search for it in Issues using searchbar. If you don't find issue matching your bug, create new report. Then Godot contributes will assign labels and milestones for it.

This list is only as of a help for potential bugfixers to find something to work on. It's not automatic so it can be outdated a bit.

**Comment by LikeLakers2** [comment]
Just commenting here to remind somebody (kubecz3k or someone who can edit his original comment) to update this tracker.

Checking through what's listed here, here's what I'd remove from the list (if it ended up not being a bug) or check off (if it's been fixed):
- **(Not a bug)** 3D particles emission gets chunky if framerate is slowed down #10186 (bug)
- **(Not a bug)** 3D particles are extremely laggy when seen close #10185 (bug)
- **(Not a bug)** MultiMesh does not change color of instances #10217 (bug)
- **(Fixed?)** Particles 3D - gravity does not work if initial velocity iz zero #10349 (bug)
- **(Fixed?)** Particles 3D initial velocity always random #10348 (bug)
- **(Moved to godotengine/godot-demo-projects#58)** 2D particles are glitchy #9884 (bug)
- **(Fixed)** Add Soft Particle to blend particle's edges #3834 (enhancement)

**Comment by kubecz3k** [comment]
@LikeLakers2 thanks!

**Comment by pwab** [comment]
#12460 was fixed on master (for 2.1 there is #13336).
#10242, #10668 and godotengine/godot-demo-projects#58 were fixed.

**Comment by MelvinWM** [comment]
Added #17903.

**Comment by chanon** [comment]
Some additional particle issues I found:
https://github.com/godotengine/godot/issues/20473
https://github.com/godotengine/godot/issues/16411
https://github.com/godotengine/godot/issues/14697
https://github.com/godotengine/godot/issues/13488
https://github.com/godotengine/godot/issues/10232

**Comment by pwab** [comment]
Only one issue in the starting post is left. Maybe the tracker should be reduced to only bugs as proposals for enhancements are moved to https://github.com/godotengine/godot-proposals/issues/815 right now?

**Comment by akien-mga** [comment]
Indeed, thanks for the triage.
Let's close this as partly fixed, and the rest superseded by godotengine/godot-proposals#815.
