### ISSUE TITLE
[TRACKER] 3D editor enhancements and fixes

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#11655]
Hi everyone, (yes I'm copying groud :D)

I plan to work on the 3D editor to make it ready for real work and fix bugs. I opened this issue to discuss what and how the changes should be implemented.

Here is list of what could be added:

**Enhancements:**
- [x] Add Scale Gizmo support - PR #11478 
- [x] Expose Global/Local Space mode to toolbar as an icon and with default shortcut - #11831
- [ ] Expose Snap toggle to toolbar as an icon and with default shortcut
- [ ] Selected object Outline with faded solid and line visualization for intersecting geometry - WIP
- [ ] World space Grid snapping support
- [x] Lock object for 3D #4447 - Done #12359 thx @kubecz3k !
- [x] GridMap - Include transforms of tile object's children when generating .meshlib file #11722
- [x] Display details like shapes and icons of instanced scenes #8261

**Fixes:**
- [x] Rotate Gizmo going crazy - PR #11842
- [x] Support for Planar Translate in Local Space
- [x] Grid Map node editing broken when node is rotated #2668
- [ ] AABB style Gizmos are broken when Spatial that uses them are scaled - @kubecz3k make an Issue plz :)

**Candidates:**
Selectable Children toggle for 3D #11756

**Temp:**
#10453
#8746
#4448 ???
#2620 ?

**Comment by toger5** [comment]
Transform shortcuts. (maybe shift + Q, W, E, R) immediatly start transformation without changing tool or holding mouse buttpn down. + shortcut for axis lock in all transformations.

**Comment by groud** [comment]
Awsome. If you can maybe use the 2D canvas editor as a reference, so that both are consistent. :)

**Comment by n-pigeon** [comment]
@toger5 This is interesting concept must test it out :D 
@groud Yes, that is important. :3 There may be some conflicts tho, but then we can thinks something out.

**Comment by homer666** [comment]
Along with the Lock toggle as mentioned in #4447, I think it would be cool to see the Selectable Children toggle ported over to the 3D side. Right now you can replicate this functionality by saving the branch to a scene and having it be instanced (with "Editable Children" disabled). This does the job, but the toggle would be really convenient.

**Comment by eon-s** [comment]
What do you think of #8261?

**Comment by n-pigeon** [comment]
@homer666 I will look into it maybe, but can't promise anything until I will finish some other things on my list. :)
@eon-s Yeah it sounds like a bigger usability issue, I will look into it at some point.

I will add those issues to not forget about it.

**Comment by n-pigeon** [comment]
@homer666 Make an issue about it so it will be easier to find/discover :)

**Comment by homer666** [comment]
@n-pigeon done.

**Comment by Noshyaar** [comment]
>Rotate Gizmo going crazy

I've only experienced this with Local coords enabled. It's because the Gizmo rotates with object. This wouldn't be an issue if it hadn't affected other axes. Somehow it misaligns when angle is wider, causing a loop of misalignment.

**Comment by n-pigeon** [comment]
@Noshyaar yup it was caused by flipping Plane that was used as base axis for rotation. I've fixed it in #11842

**Comment by fracteed** [comment]
@n-pigeon , a nice initiative you have started here! Would love to see some Blender style shortcuts for move/scale/rotate with numerical accuracy. In Blender you can hit, for instance, S, then X then 2 to scale an object to exactly twice the size on x-axis. Or R-Y-90 to rotate 90 degrees on Y axis. Would be very handy addition to Godot, but not sure if this is possible with its hotkey system?

Very much looking forward to being able to lock objects in the viewport. This would work really well with marquee selection for moving large selections around a scene. Speaking of which, despite a recent commit to fix marquee selections for meshes, it still doesn't work for me. Maybe it is a Win10 issue..is it working for anyone?

**Comment by n-pigeon** [comment]
@fracteed 
Yup I know how it works in Blender. I'm veteran Blender artist myself. :)
I will slowly improve tools that we have in editor, but I want to do it step by step with constant feedback from community and devs. ;)
Blenderification of Godot without it and 'on hurray' would be failed project from the beginning :D.
Game Level editor needs a bit different set of tools so we should thing about common user cases and not copy "ready" solutions for different problems.

I don't state I don't want more modal operator approach in 3D Gizmo I just wanted to clarify my approach to this tasks :)

First of all I want to fix MOST basic problems and UX enhancements before diving into new "revolutionary" features ;)

About marquee bug, make Issue report. I know @kubecz3k was working on this maybe he can update.

**Comment by Calinou** [comment]
What about allowing the camera pitch to go past -90..90 degrees, like in Blender or Unity? I can create an issue for this, if this is a desired tweak.

**Comment by n-pigeon** [comment]
@Calinou Honestly I don't understand why you would ever need to flip upside down. :) You can't just rotate to that position and look up?

**Comment by akien-mga** [comment]
Most of those issues have been fixed by now, so I'd suggest to close it.

If some of the points are still relevant in the current master branch, they should be split in their own issue. (And eventually if we need a new tracker for 3D editor usability, we could open a new one).
