### ISSUE TITLE
[Tracker] Clean up and reformat C# source code

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#18051]
**Godot version:**
`master` / 9e7cee2ce

**OS/device including version:**
_Manjaro KDE Linux 17.1_

**Issue description:**
As discussed in godotengine/godot-docs#1296, I'm planning to do a mass clean up of existing C# source files by running a code inspection tool.

The purpose is to improve code quality and make it more consistent with the standard code style and naming convention of the language.

The initial result reports 1,622 issues, so it'd be obviously dangerous do an automatic clean up. So, I'm going to list them by categories here, and incrementally fix them in case by case basis:

- [ ] Code Style (839 remaining).
- [ ] Potention Code Quality Issues (140 remaining).
- [ ] Common Practices and Code Improvements (97 remaining).
- [ ] Language Usage Opportunities (66 remaining).
- [ ] Redundancies in Code (83 remaining).
- [ ] Constraints Violations (90 remaining).
- [ ] Redundancies in Symbol Declarations (307 remaining).

Total 1,622 issues found.

**Comment by mysticfall** [comment]
Is `Godot.MarshalUtils.*` needed anywhere? It reports the type to be unused but I'm not sure if I should remove it, because it might be needed internally.

**Comment by Chaosus** [comment]
@mysticfall Could you also rebase it on #18038 ?

**Comment by mysticfall** [comment]
@Chaosus Sure, but would it be ok if I rebase after your PR is merged? I cloned the repo with `--depth=1`, so it'd be easier for me to do so.

**Comment by Chaosus** [comment]
@mysticfall Of course

**Comment by aaronfranke** [comment]
@mysticfall Can you update this tracker? How many issues are remaining? What about [the style guide](https://github.com/godotengine/godot-docs/issues/1296#issuecomment-379544354)?

**Comment by mysticfall** [comment]
@aaronfranke I normally can't spend much time during week days so it's been rather slow. I'll update this issue this weekend, and try to finish the style guide draft shortly after. Sorry about the delay! :sweat_smile:

**Comment by mysticfall** [comment]
Just updated the tracker and it seems we've fixed about 400 issues with the first pass. I also updated the style guide, so please feel free to review it and suggest changes. Thanks!

**Comment by aaronfranke** [comment]
@mysticfall What tool are you using? It's not very useful to have this issue open for other contributors if we don't know what issues it's supposed to be tracking :)

**Comment by mysticfall** [comment]
@aaronfranke Sorry, I haven't provided enough information. I'm using Rider's builtin inspectors which I believe is pretty much the same with VisualStudio's Resharper addon.

**Comment by van800** [comment]
BTW there is CleanupCode is a free cross-platform command-line tool https://www.jetbrains.com/help/rider/CleanupCode.html

**Comment by Anutrix** [comment]
I suspect the numbers in original comment are highly out of date.

Requesting fresh data along with tool used and any other info needed to reproduce the same output to keep this ticket relevant.
We should discuss good alternative tool options if needed.
