### ISSUE TITLE
[TRACKER] Better logging

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19122]
I've seen a lot of issues related to logging in general so I thought I would list them here.
Some issues appear multiple times because I tried to categorize the requested features and they sometimes overlap.

- [ ] #22184: No print to Output panel in infinite loop
- [ ] #19121: collapse same messages into one
- [ ] #19098: ability to search the output log to filter messages
- [x] #18319, #13335, #3884: ability to trace messages to which script they came from
- [x] #10566: jump to script location when double-click on log message
- [ ] #10870: highlight node when clicking on message, if possible
- [ ] #7095, #10870: have explicit debug, info, warning and error printouts so we can filter or opt them out on export for example
- [ ] #10870, #2308: ability to color and format messages

**Comment by BeayemX** [comment]
Maybe add theses too? 
#10870
#10566

**Comment by mhilbrunner** [comment]
Thanks for doing the work of creating a tracker. Some improvements here would be really welcome :)

**Comment by Calinou** [comment]
This is tangantially related: https://github.com/godotengine/godot/issues/2308

If implemented, those codes should work in the Output console as well.

**Comment by blurymind** [comment]
This would improve debugging a lot imo. The console is almost the main tool for me.

Thank you for creating this Tracker!

**Comment by Calinou** [comment]
@radishes Please refrain from bumping issues without contributing new information; use the :+1: reaction button on the first post instead.

**Comment by Calinou** [comment]
Closing, as all items on the tracker have been addressed. Further imporvements should be requested on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository after searching for duplicates.
