### ISSUE TITLE
[TRACKER] musl libc support in Godot

### ISSUE THREAD

**Issue by MazeChaZer** [godotengine/godot#20037]
I am currently working on a docker image for Godot. I would like to base this image on Alpine Linux, which uses musl libc instead of glibc. I already managed to get it compiling and now work on it running properly.

I created this issue for general discussion about musl libc/Alpine linux support. For the problems I encountered, I created separate issues:

- [x] #20035: musl libc compatibility: Can the use of execinfo.h be made optional?
- [x] #20036: musl libc compatibility: isnanf vs. isnan
- [x] #21282: Segmentation fault on opening a project on musl libc

It would be great if the continous integration on Travis CI would include a musl libc system like Alpine Linux, is that possible?

**Comment by ronchaine** [comment]
I started looking at running godot on musl about a week ago.

Compiling works fine with few minor fixes, but it segfaults when loading the editor for me, and I'm still trying to track down what happens.  The stack trace shows some radeonsi and libz deflate calls, but currently cannot test my build on non-amd-gpu-machine to see if it still happens.

**Comment by willvincent** [comment]
Any reason you can't just use a version of alpine that includes glibc?

Like: https://hub.docker.com/r/frolvlad/alpine-glibc/

**Comment by akien-mga** [comment]
The whole raison d'être of Alpine is to not include GNU tools but use more lightweight alternatives (and make on Linux distro where people can't tell you "actually, it's GNU/Linux, or as I've taken to call it, GNU+Linux).

**Comment by MazeChaZer** [comment]
@akien-mga this. Also I would like to use the official alpine images.

**Comment by ronchaine** [comment]
Both of the issues #20035 and #20036 in the original post have been resolved.

I made new ticket for #21282, either it should be added to the tracker or this issue should be closed.

**Comment by aaronfranke** [comment]
What's the status of this issue? It seems like a good thing for Godot to run on multiple libraries and compilers, as it should make the codebase more robust...?

**Comment by Anutrix** [comment]
The tracker seems to complete, so what else is left?

**Comment by akien-mga** [comment]
Closing then.
