### ISSUE TITLE
[TRACKER] Particle System improvements

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#20473]
**Suggestion for improvements of the Particle System.**

We are aware that some of these points are present in other issues as well. But in this list we tried to prioritize the features we are missing most, and also limit them to features that should not be too complex to implement.

- [x] Randomness for Particle Life time is not working.
- [ ] Add Sub Emitters for Particle Birth and Death. 
- [x] A Reset Button so you don't have to wait for particles to die out when you test new settings (this button could be placed underneath the Emitting field).
- [x] Set a direction for the Particle system in the Particle Material (instead of rotating the entire node).
- [ ] Stretch Particles (how much could be determined by speed or a custom variable).

**Comment by KoBeWi** [comment]
Worth to note that direction was present in Godot 2.1 and is even mentioned in Particle Systems tutorial, but in 3.0 is absent. For me that would be most important to (re)add.

**Comment by omomthings** [comment]
Any update about the particles system? I was trying to recreate the ''Particles pack'' from unity to learn get familiar with the editor and also to share it with the community but I was stuck early not finding a lot of features like sub emitters etc..

**Comment by Calinou** [comment]
@omomthings The particle system will likely get some changes in 4.0, but not before.

**Comment by omomthings** [comment]
@Calinou That's what I was affraid of.. :/

**Comment by clayjohn** [comment]
Three of those suggestions actually made it into 3.2! I checked them off.

**Comment by PLyczkowski** [comment]
Could we add Particle Forces (like Turbulence) to the list?

**Comment by pwab** [comment]
This should be closed in favor of https://github.com/godotengine/godot-proposals/issues/815

**Comment by KoBeWi** [comment]
Yep.
