### ISSUE TITLE
TileMap editor improvements

### ISSUE THREAD

**Issue by paulloz** [godotengine/godot#21123]
Those are returns I had from persons used to working with other (proper?) TileMap editors. They're based on current master builds.  
They are all small improvements so I'm grouping this in one issue, please tell me if I should split this.

* [x] We should be able to see what tool is currently selected, getting the tools out of the *TileMap* submenu and highlighting the one in use should do the trick.
* [x] The tool should not be reset automatically to the paint brush as soon as a selection is done.
* [x] Replace the Move and Duplicate actions by Cut and Copy as they're basically the same thing but less confusing (there's a little work to do to change the behaviour but not much imho).

I'll make other issues for bigger improvements as they might need more work.

**Comment by akien-mga** [comment]
Fixed by #21272.
