### ISSUE TITLE
[TRACKER] Collision Shape issues

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#24816]
This issue tracks improvements, bugs and compatibility breaks related with Collision Shapes

**Bugs**

- [x] Error 3D physics, violation collision mesh RigidBody and other body #4831
- [x] Collision with edges between convex/planar face pair #7701
- [x] Bad collision against StaticBody2D with LineShape2D #7920
- [x] CollisionShape2D trigger doesn't behave as expected #4393
- [x] "Create convex static body/collision sibling" freezes the editor if used on sphere mesh #21141
- [x] Unable to animate the shape of the CollisionPolygon2D #14599
- [x] 2D Physics excessive collision pairs, regardless of layer/mask #28460

**Improvements / Suggestions**

- [x] "Collision Groups" handling Collision Layers & Masks #7793
- [x] Expose collision resolution bias in editor for rigid bodies/collision shapes #7700
- [x] Shape Colision Editor Suggestions #8227

**Comment by timoschwarzer** [comment]
+ Suggestion: As we already have the option to create 2D meshes from sprites, an option to create collision polygons from sprites with a similar dialog.

**Comment by eon-s** [comment]
@timoschwarzer create/locate an issue about that so it can be added to the tracker

**Comment by davismiculis** [comment]
Hi, I think recent commits (around past 2 days) broke 2d collision:

![](https://media.giphy.com/media/7NOwbx0SH8AIoP6R9x/giphy.gif)

Perhaps this commit - https://github.com/godotengine/godot/commit/d8b702b5660ee4c8a072ecde0c7d6a85bf8f7337 ?

**Comment by eon-s** [comment]
@davismiculis open an issue about that with all the details you can add so it can be added on the tracker, otherwise nobody will check it (mention that is a regression).

**Comment by davismiculis** [comment]
https://github.com/godotengine/godot/issues/25181

**Comment by homer666** [comment]
Not sure if this tracker is still maintained, but #31030 could probably be added.

**Comment by avencherus** [comment]
May consider this.  The masking doesn't seem to exclude shape pairings:  https://github.com/godotengine/godot/issues/28460

**Comment by homer666** [comment]
My bad, it looks like #31030 was due to the .escn exporter for Blender. I think it should be removed from this tracker.

**Comment by KoBeWi** [comment]
Seems like all issues tracked here are closed, so closing.
