### ISSUE TITLE
[TRACKER] Inconsistencies between GPU Particles(2D) and CPUParticles(2D)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#29692]
**Godot version:**
3.2 master (15425b45)

**OS/device including version:**
Any OS, GLES3

**Issue description:**

While testing conversions from Particles2D to CPUParticles2D, I noticed a few things which do not get properly converted or do not work the same way once converted in the CPU variant. Similar issues exist for Particles -> CPUParticles (3D), so it's worth reviewing all 4 nodes systematically to fix or document inconsistencies.

- [x] Orbital velocity is not exposed in CPUParticles2D and CPUParticles, nor the related `FLAG_DISABLE_Z` flag. **PR #29683**

![Peek 2019-06-12 12-27](https://user-images.githubusercontent.com/4701338/59344039-7f385400-8d0d-11e9-8b0f-60dc89abaecc.gif)
*(CPU -- GPU)*

- [x] Tangential acceleration behaves differently (much stronger) in CPUParticles2D compared to Particles2D. The 3D counterpart is also affected if the "Disable Z" flag is enabled. **PR #29685**

![Peek 2019-06-12 12-32](https://user-images.githubusercontent.com/4701338/59344327-274e1d00-8d0e-11e9-9bbb-0461773efcf8.gif)
*(GPU -- CPU)*

- [x] Time/Emission randomness behaves differently in CPUParticles2D and CPUParticles, with almost no visible effect. There is something fishy in the way `lifetime` is used or missing as a factor in the randomness code, and a fix similar to c13ac398f might be needed. **PR #29696**

![Peek 2019-06-12 12-37](https://user-images.githubusercontent.com/4701338/59344658-d68af400-8d0e-11e9-91a4-71a9e380016b.gif)
*(CPU -- GPU)*

- [ ] Trail properties are not implemented in CPUParticles2D and CPUParticles. It's not clear yet whether this is by design (technical limitation) or omission.

![Peek 2019-06-12 12-23](https://user-images.githubusercontent.com/4701338/59343842-020cdf00-8d0d-11e9-8702-3f24483b41b1.gif)
*(GPU -- CPU)*

- [x] CPUParticles2D's "Sphere" emission shape is actually a circle (outline only), while Particles2D's is a disc ("filled circle"), or might even actually be a sphere projected on a 2D plane (it kind of feels like the emission density is higher on the edges than in the center, giving an impression of spherical surface). **PR #29854**

![Peek 2019-06-12 12-25](https://user-images.githubusercontent.com/4701338/59343932-32547d80-8d0d-11e9-8ab2-1d80cd748e98.gif)
*(CPU -- GPU)*

Will add more as I find them.

Test project: [particles.zip](https://github.com/godotengine/godot/files/3280867/particles.zip)
Note: The "Direction_Mask" Particles2D in the original demo, and kept in this example, seems to be kind of broken, as it will work some times and fail at other times. Disabling the "Disable Z" flag on the Particles2D seem to make it work more reliably, but I suspect some uninitialized variable or other issue.

**Comment by akien-mga** [comment]
I made a test project for Particles2D & CPUParticles2D based on the `2d/particles` official demo: [particles.zip](https://github.com/godotengine/godot/files/3280697/particles.zip)

In the `cpuparticles.tscn` scene, all particle effects have been duplicated the duplicate converted to CPUParticles2D using the editor plugin feature. It illustrates some of the bugs outside above and some more, especially when you start playing with the various directional acceleration properties which often do nothing for CPUParticles2D.

**Comment by clayjohn** [comment]
I have found a couple while working on https://github.com/godotengine/godot/pull/29700

- [ ] Depth draw order ``lifetime`` reversed for CPUParticles (same as https://github.com/godotengine/godot/issues/29440) (Will be addressed in #29700)

- [ ] Depth draw order ``view_depth`` doesn't match Particles (will be addressed in #29700)

- [ ] Default velocity is 1 in CPUParticles while it is ``0`` in Particles (Junior Job: just change ``1`` to ``0`` [here](https://github.com/godotengine/godot/blob/f410e7a8a9b14fd9f5c210afcc9e3519e9ce246d/scene/3d/cpu_particles.cpp#L1424))

**Comment by akien-mga** [comment]
>  Visibility rect not drawn in CPUParticles2D (start by copying from here)

Regarding the visibility rect, @JFonS told me that the property was not added to CPUParticles\* as it's computed automatically. But maybe we still want to draw the computed rect?

**Comment by simonpuchert** [comment]
@akien-mga The Particles2D sphere is actually just a projected 3D sphere (so you're correct about that). In a way, it makes sense as the UI says under "Flags": "Disable Z" and if you had to "disable Z" you would of course use orthogonal projection.

The CPUParticles2D sphere is a non-uniform density circle as it is created by normalizing uniformly distributed random points in a square. This means that the "diagonal regions" have a point density of sqrt(2) times that of the "cardinal regions". That can be fixed by using trigonometric functions at the cost of some performance
(i.e. t = 2 * PI * Math::randf(); x = r * cos(t); y = r * sin(t);).

Of course, it is not up to me to decide what is important to you (or anyone else), so take this more as a description of the status quo than a recommendation.

**Comment by fossegutten** [comment]
Would prefer a uniform distribution in a circle, like  @simonpuchert supplied an algorithm for :+1:

**Comment by clayjohn** [comment]
> Would prefer a uniform distribution in a circle, like @simonpuchert supplied an algorithm for 👍

That code creates a circle outline, we have decided to go with the sphere for CPUParticles2D to match the behaviour of Particles2D. We have discussed adding a circle option and a square option later. But for now, it makes the most sense for the two types of particles to have the same behaviour.

**Comment by fossegutten** [comment]
> But for now, it makes the most sense for the two types of particles to have the same behaviour.

Sorry about that, what i meant that it would be nice to have uniform circle distribution of particles, for both particles2d and cpuparticles2d! It would also be nice to have the old circle outline and this sphere as options also. Maybe also rect outline? I think several options here is a good thing, since particles need to be unique :) I could open a new issue with feature request?

**Comment by simonpuchert** [comment]
If you want a similar "algorithm" for the projected sphere, it would be
```c++
s = Math::randf();
t = 2*PI*Math::randf();
rad = r*sqrt(1-s^2);
x = rad*cos(t); y = rad*sin(t);
```
and a 3D sphere would be
```c++
s = Math::randf();
t = 2*PI*Math::randf();
rad = r*sqrt(1-s^2);
x = rad*cos(t); y = rad*sin(t); z = r*s;
```
An easy way to understand how it works is to look at the Lambert equal-area cylindrical projection.

Again, I'm not here to say what you should do, but if you want a uniform distribution on a sphere this is one way to accomplish it.
By the way, scene/3d/cpu_particles.cpp also uses the "normalized cube" method, so it produces the same non-uniform-density sphere.

**Comment by einnjo** [comment]
It might also make sense to track this one #40807 here.

**Comment by akien-mga** [comment]
Most of the issues have been fixed, and the particles system will be different in 4.0, so this tracker can be closed. (We can open a new one if/once we start noticing inconsistencies between particle systems in 4.0, though I'm not sure if it will also have CPU vs GPU particles.)
