### ISSUE TITLE
[TRACKER] Compilation warnings raised on iOS builds

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#29800]
**Godot version:**
3.2 master (5cc1c7d)


**OS/device including version:**
macOS


**Issue description:**
This tracker should list all current warnings raised for iOS builds, specifying when relevant the build options (`target`).

The initial set of warnings has been copied from @bruvzg's report on #29033.

If you're a contributor with edit access, please modify the OP directly to add more checkboxes for new/other warnings. If you don't have edit access, you can add them in a comment below.

Several of those might be fixed by the pending #22784 by @samgreen.

#### `warnings=extra`

With Xcode 10.2.1 (@bruvzg):

- [x] `tools=no target=release_debug` in `platform/iphone/gl_view.h` (fixed in #33035)

```
platform/iphone/gl_view.h:83:30: warning: 'MPMoviePlayerController' is deprecated: first deprecated in iOS 9.0 - Use AVPlayerViewController in AVKit. [-Wdeprecated-declarations,30]
 @property(strong, nonatomic) MPMoviePlayerController *moviePlayerController;
                              ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/MediaPlayer.framework/Headers/MPMoviePlayerController.h:83:12: note: 'MPMoviePlayerController' has been explicitly marked deprecated here [2]
 @interface MPMoviePlayerController : NSObject <MPMediaPlayback>
            ^
```

- [x] `tools=no target=release_debug` in `platform/iphone/gl_view.h`

```
platform/iphone/gl_view.h:108:26: note: setter and getter must both be synthesized, or both be user defined,or the property must be nonatomic [2]
 @property NSTimeInterval animationInterval;
                          ^
           (nonatomic)
fix-it:"platform/iphone/gl_view.h":{108:11-108:11}:"(nonatomic) "
platform/iphone/gl_view.h:108:26: note: property declared here [2]
```

- [x] `tools=no target=release_debug` in `platform/iphone/main.m`

```
platform/iphone/main.m:45:15: warning: unused variable 'app' [-Wunused-variable,35]
        AppDelegate *app = [AppDelegate alloc];
                      ^
```

- [x] `tools=no target=release_debug` in `platform/iphone/gl_view.mm`

```
platform/iphone/gl_view.mm:84:23:{84:23-84:38}: warning: 'safeAreaInsets' is only available on iOS 11.0 or newer [-Wunguarded-availability-new,2]
                insets = [_instance safeAreaInsets];
                                     ^~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIView.h:264:45: note: 'safeAreaInsets' has been marked as being introduced in iOS 11.0 here, but the deployment target is iOS 10.0.0 [2]
 @property (nonatomic,readonly) UIEdgeInsets safeAreaInsets API_AVAILABLE(ios(11.0),tvos(11.0));
                                             ^
platform/iphone/gl_view.mm:84:23:{84:23-84:38}: note: enclose 'safeAreaInsets' in an @available check to silence this warning [2]
                insets = [_instance safeAreaInsets];
                                     ^~~~~~~~~~~~~~~
fix-it:"platform/iphone/gl_view.mm":{84:3-84:3}:"if (@available(iOS 11.0, *)) {\n\t\t    "
fix-it:"platform/iphone/gl_view.mm":{84:39-84:39}:"\n\t\t} else {\n\t\t    // Fallback on earlier versions\n\t\t}"
platform/iphone/gl_view.mm:417:16: warning: 'setFrameInterval:' is deprecated: first deprecated in iOS 10.0 - preferredFramesPerSecond [-Wdeprecated-declarations,30]
                [displayLink setFrameInterval:frameInterval];
                              ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CADisplayLink.h:71:32: note: property 'frameInterval' is declared deprecated here [2]
 @property(nonatomic) NSInteger frameInterval
                                ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CADisplayLink.h:71:32: note: 'setFrameInterval:' has been explicitly marked deprecated here [2]
platform/iphone/gl_view.mm:451:1: warning: writable atomic property 'animationInterval' cannot pair a synthesized getter with a user defined setter [-Watomic-property-with-user-defined-accessor,2]
 - (void)setAnimationInterval:(NSTimeInterval)interval {
 ^
```

- [ ] `tools=no target=release_debug` in `platform/iphone/in_app_store.mm`

```
platform/iphone/in_app_store.mm:209:29: warning: 'transactionReceipt' is deprecated: first deprecated in iOS 7.0 - Use -[NSBundle appStoreReceiptURL] [-Wdeprecated-declarations,30]
                                                receipt = transaction.transactionReceipt;
                                                                       ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/StoreKit.framework/Headers/SKPaymentTransaction.h:47:50: note: 'transactionReceipt' has been explicitly marked deprecated here [2]
 @property(nonatomic, readonly, nullable) NSData *transactionReceipt NS_DEPRECATED_IOS(3_0, 7_0, "Use -[NSBundle appStoreReceiptURL]");
                                                  ^
platform/iphone/in_app_store.mm:213:28: warning: 'transactionReceipt' is deprecated: first deprecated in iOS 7.0 - Use -[NSBundle appStoreReceiptURL] [-Wdeprecated-declarations,30]
                                        receipt = transaction.transactionReceipt;
                                                               ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/StoreKit.framework/Headers/SKPaymentTransaction.h:47:50: note: 'transactionReceipt' has been explicitly marked deprecated here [2]
 @property(nonatomic, readonly, nullable) NSData *transactionReceipt NS_DEPRECATED_IOS(3_0, 7_0, "Use -[NSBundle appStoreReceiptURL]");
                                                  ^
platform/iphone/in_app_store.mm:276:34: warning: 'paymentWithProductIdentifier:' is deprecated: first deprecated in iOS 5.0 - Use +paymentWithProduct: after fetching the available products using SKProductsRequest [-Wdeprecated-declarations,30]
        SKPayment *payment = [SKPayment paymentWithProductIdentifier:pid];
                                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/StoreKit.framework/Headers/SKPayment.h:23:1: note: 'paymentWithProductIdentifier:' has been explicitly marked deprecated here [2]
 + (id)paymentWithProductIdentifier:(NSString *)identifier NS_DEPRECATED_IOS(3_0, 5_0, "Use +paymentWithProduct: after fetching the available products using SKProductsRequest");
 ^
```

- [x] `tools=no target=release_debug` in `platform/iphone/view_controller.mm`

```
platform/iphone/view_controller.mm:46:21: warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings,30]
        p_args[p_argc++] = "--path";
                            ^
platform/iphone/view_controller.mm:48:34: warning: 'cString' is deprecated: first deprecated in iOS 2.0 - Use -cStringUsingEncoding: instead [-Wdeprecated-declarations,30]
        p_args[p_argc++] = (char *)[str cString];
                                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:501:1: note: 'cString' has been explicitly marked deprecated here [2]
 - (nullable const char *)cString NS_RETURNS_INNER_POINTER API_DEPRECATED("Use -cStringUsingEncoding: instead", macos(10.0,10.4), ios(2.0,2.0), watchos(2.0,2.0), tvos(9.0,9.0));
 ^
platform/iphone/view_controller.mm:60:20: warning: comparison of integers of different signs: 'int' and 'NSUInteger' (aka 'unsigned long') [-Wsign-compare]
        for (int i = 0; i < [arr count]; i++) {
                        ~ ^ ~~~~~~~~~~~
platform/iphone/view_controller.mm:66:35: warning: 'cString' is deprecated: first deprecated in iOS 2.0 - Use -cStringUsingEncoding: instead [-Wdeprecated-declarations,30]
                p_args[p_argc++] = (char *)[str cString];
                                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:501:1: note: 'cString' has been explicitly marked deprecated here [2]
 - (nullable const char *)cString NS_RETURNS_INNER_POINTER API_DEPRECATED("Use -cStringUsingEncoding: instead", macos(10.0,10.4), ios(2.0,2.0), watchos(2.0,2.0), tvos(9.0,9.0));
 ^
platform/iphone/view_controller.mm:79:17: warning: method definition for 'shouldAutorotateToInterfaceOrientation:' not found [-Wincomplete-implementation,2]
 @implementation ViewController
                 ^
platform/iphone/view_controller.h:37:1: note: method 'shouldAutorotateToInterfaceOrientation:' declared here [2]
 - (BOOL)shouldAutorotateToInterfaceOrientation:
 ^
```

- [ ] `tools=no target=release_debug` in `platform/iphone/app_delegate.mm`

```
platform/iphone/app_delegate.mm:55:37: warning: 'openURL:' is deprecated: first deprecated in iOS 10.0 - Please use openURL:options:completionHandler: instead [-Wdeprecated-declarations,30]
        [[UIApplication sharedApplication] openURL:[NSURL URLWithString:url]];
                                            ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:128:1: note: 'openURL:' has been explicitly marked deprecated here [2]
 - (BOOL)openURL:(NSURL*)url NS_DEPRECATED_IOS(2_0, 10_0, "Please use openURL:options:completionHandler: instead") NS_EXTENSION_UNAVAILABLE_IOS("");
 ^
platform/iphone/app_delegate.mm:450:14: warning: '__bridge_transfer' casts have no effect when not using ARC [-Warc-bridge-casts-disallowed-in-nonarc,8]
                                        uuid = (__bridge_transfer NSString *)CFUUIDCreateString(NULL, cfuuid);
                                                 ^~~~~~~~~~~~~~~~~~
fix-it:"platform/iphone/app_delegate.mm":{450:14-450:32}:""
platform/iphone/app_delegate.mm:593:10: warning: unused variable 'quit_request' [-Wunused-variable,35]
                                bool quit_request = OSIPhone::get_singleton()->iterate();
                                      ^
platform/iphone/app_delegate.mm:612:15: warning: 'setStatusBarHidden:withAnimation:' is deprecated: first deprecated in iOS 9.0 - Use -[UIViewController prefersStatusBarHidden] [-Wdeprecated-declarations,30]
        [application setStatusBarHidden:YES withAnimation:UIStatusBarAnimationNone];
                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:464:1: note: 'setStatusBarHidden:withAnimation:' has been explicitly marked deprecated here [2]
 - (void)setStatusBarHidden:(BOOL)hidden withAnimation:(UIStatusBarAnimation)animation NS_DEPRECATED_IOS(3_2, 9_0, "Use -[UIViewController prefersStatusBarHidden]") __TVOS_PROHIBITED;
 ^
platform/iphone/app_delegate.mm:150:25:{150:4-150:24}: warning: 'UIView' may not respond to 'stopAnimation' [2]
                [view_controller.view stopAnimation];
                  ~~~~~~~~~~~~~~~~~~~~ ^
platform/iphone/app_delegate.mm:168:25:{168:4-168:24}: warning: 'UIView' may not respond to 'startAnimation' [2]
                [view_controller.view startAnimation];
                  ~~~~~~~~~~~~~~~~~~~~ ^
```

- [x] `tools=no target=release_debug` in `platform/iphone/ios.mm`

```
platform/iphone/ios.mm:41:2: warning: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead [-Wdeprecated-declarations,30]
        UIAlertView *alert = [[[UIAlertView alloc] initWithTitle:[NSString stringWithUTF8String:p_title] message:[NSString stringWithUTF8String:p_alert] delegate:nil cancelButtonTitle:@"OK" otherButtonTitles:nil, nil] autorelease];
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAlertView.h:27:12: note: 'UIAlertView' has been explicitly marked deprecated here [2]
 @interface UIAlertView : UIView
            ^
platform/iphone/ios.mm:41:26: warning: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead [-Wdeprecated-declarations,30]
        UIAlertView *alert = [[[UIAlertView alloc] initWithTitle:[NSString stringWithUTF8String:p_title] message:[NSString stringWithUTF8String:p_alert] delegate:nil cancelButtonTitle:@"OK" otherButtonTitles:nil, nil] autorelease];
                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAlertView.h:27:12: note: 'UIAlertView' has been explicitly marked deprecated here [2]
 @interface UIAlertView : UIView
            ^
```

- [x] `tools=no target=release_debug` in `drivers/unix/semaphore_posix.cpp` (more details in #24418, fixed in #33035)

```
drivers/unix/semaphore_posix.cpp:60:2: warning: 'sem_getvalue' is deprecated [-Wdeprecated-declarations,30]
        sem_getvalue(&sem, &val);
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/include/sys/semaphore.h:54:56: note: 'sem_getvalue' has been explicitly marked deprecated here [2]
 int sem_getvalue(sem_t * __restrict, int * __restrict) __deprecated;
                                                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/include/sys/cdefs.h:176:40: note: expanded from macro '__deprecated'
 #define __deprecated    __attribute__((deprecated))
                                        ^
drivers/unix/semaphore_posix.cpp:77:10: warning: 'sem_init' is deprecated [-Wdeprecated-declarations,30]
        int r = sem_init(&sem, 0, 0);
                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/include/sys/semaphore.h:55:42: note: 'sem_init' has been explicitly marked deprecated here [2]
 int sem_init(sem_t *, int, unsigned int) __deprecated;
                                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/include/sys/cdefs.h:176:40: note: expanded from macro '__deprecated'
 #define __deprecated    __attribute__((deprecated))
                                        ^
drivers/unix/semaphore_posix.cpp:84:2: warning: 'sem_destroy' is deprecated [-Wdeprecated-declarations,30]
        sem_destroy(&sem);
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/include/sys/semaphore.h:53:26: note: 'sem_destroy' has been explicitly marked deprecated here [2]
 int sem_destroy(sem_t *) __deprecated;
                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/include/sys/cdefs.h:176:40: note: expanded from macro '__deprecated'
 #define __deprecated    __attribute__((deprecated))
                                        ^
```

- [ ] `tools=no target=release_debug` in `platform/iphone/game_center.mm`

```
platform/iphone/game_center.mm:209:22: warning: comparison of integers of different signs: 'int' and 'NSUInteger' (aka 'unsigned long') [-Wsign-compare]
                        for (int i = 0; i < [descriptions count]; i++) {
                                        ~ ^ ~~~~~~~~~~~~~~~~~~~~
platform/iphone/game_center.mm:259:22: warning: comparison of integers of different signs: 'int' and 'NSUInteger' (aka 'unsigned long') [-Wsign-compare]
                        for (int i = 0; i < [achievements count]; i++) {
                                        ~ ^ ~~~~~~~~~~~~~~~~~~~~
```

- [ ] `tools=no target=release_debug` in `platform/iphone/icloud.mm`

```
platform/iphone/icloud.mm:164:30: warning: comparison of integers of different signs: 'unsigned int' and 'int' [-Wsign-compare]
                for (unsigned int i = 0; i < keys.size(); ++i) {
                                         ~ ^ ~~~~~~~~~~~
platform/iphone/icloud.mm:178:30: warning: comparison of integers of different signs: 'unsigned int' and 'int' [-Wsign-compare]
                for (unsigned int i = 0; i < arr.size(); ++i) {
                                         ~ ^ ~~~~~~~~~~
platform/iphone/icloud.mm:218:29: warning: comparison of integers of different signs: 'unsigned int' and 'int' [-Wsign-compare]
        for (unsigned int i = 0; i < keys.size(); ++i) {
                                 ~ ^ ~~~~~~~~~~~
```

- [ ] `tools=no target=release_debug` in `platform/iphone/camera_ios.mm`

```
platform/iphone/camera_ios.mm:168:8: warning: unused variable '_bytes_per_row' [-Wunused-variable]
                        int _bytes_per_row = CVPixelBufferGetBytesPerRowOfPlane(pixelBuffer, 0);
                            ^
platform/iphone/camera_ios.mm:189:8: warning: unused variable 'bytes_per_row' [-Wunused-variable]
                        int bytes_per_row = CVPixelBufferGetBytesPerRowOfPlane(pixelBuffer, 1);
                            ^
platform/iphone/camera_ios.mm:170:18: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
                        if ((width[0] != new_width) || (height[0] != new_height)) {
                             ~~~~~~~~ ^  ~~~~~~~~~
platform/iphone/camera_ios.mm:170:46: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
                        if ((width[0] != new_width) || (height[0] != new_height)) {
                                                        ~~~~~~~~~ ^  ~~~~~~~~~~
platform/iphone/camera_ios.mm:191:18: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
                        if ((width[1] != new_width) || (height[1] != new_height)) {
                             ~~~~~~~~ ^  ~~~~~~~~~
platform/iphone/camera_ios.mm:191:46: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
                        if ((width[1] != new_width) || (height[1] != new_height)) {
                                                        ~~~~~~~~~ ^  ~~~~~~~~~~
platform/iphone/camera_ios.mm:362:301: warning: missing sentinel in method dispatch [-Wsentinel]
        AVCaptureDeviceDiscoverySession *session = [AVCaptureDeviceDiscoverySession discoverySessionWithDeviceTypes:[NSArray arrayWithObjects:AVCaptureDeviceTypeBuiltInTelephotoCamera, AVCaptureDeviceTypeBuiltInDualCamera, AVCaptureDeviceTypeBuiltInTrueDepthCamera, AVCaptureDeviceTypeBuiltInWideAngleCamera] mediaType:AVMediaTypeVideo position:AVCaptureDevicePositionUnspecified];
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:93:1: note: method has been explicitly marked sentinel here
+ (instancetype)arrayWithObjects:(ObjectType)firstObj, ... NS_REQUIRES_NIL_TERMINATION;
^
platform/iphone/camera_ios.mm:362:217: warning: 'AVCaptureDeviceTypeBuiltInTrueDepthCamera' is only available on iOS 11.1 or newer [-Wunguarded-availability-new]
        AVCaptureDeviceDiscoverySession *session = [AVCaptureDeviceDiscoverySession discoverySessionWithDeviceTypes:[NSArray arrayWithObjects:AVCaptureDeviceTypeBuiltInTelephotoCamera, AVCaptureDeviceTypeBuiltInDualCamera, AVCaptureDeviceTypeBuiltInTrueDepthCamera, AVCaptureDeviceTypeBuiltInWideAngleCamera] mediaType:AVMediaTypeVideo position:AVCaptureDevicePositionUnspecified];
                                                                                                                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.1.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:520:38: note: 'AVCaptureDeviceTypeBuiltInTrueDepthCamera' has been marked as being introduced in iOS 11.1 here, but the deployment target is iOS 10.0.0
AVF_EXPORT AVCaptureDeviceType const AVCaptureDeviceTypeBuiltInTrueDepthCamera API_AVAILABLE(ios(11.1)) API_UNAVAILABLE(macos) __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
                                     ^
platform/iphone/camera_ios.mm:362:217: note: enclose 'AVCaptureDeviceTypeBuiltInTrueDepthCamera' in an @available check to silence this warning
        AVCaptureDeviceDiscoverySession *session = [AVCaptureDeviceDiscoverySession discoverySessionWithDeviceTypes:[NSArray arrayWithObjects:AVCaptureDeviceTypeBuiltInTelephotoCamera, AVCaptureDeviceTypeBuiltInDualCamera, AVCaptureDeviceTypeBuiltInTrueDepthCamera, AVCaptureDeviceTypeBuiltInWideAngleCamera] mediaType:AVMediaTypeVideo position:AVCaptureDevicePositionUnspecified];
                                                                                                                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

- [ ] `tools=no target=release_debug` in `modules/arkit/arkit_session_delegate.mm`

```
n file included from modules/arkit/arkit_session_delegate.mm:31:
modules/arkit/arkit_session_delegate.h:45:18: warning: 'ARSession' is only available on iOS 11.0 or newer [-Wunguarded-availability-new]
[ 13%] - (void)session:(ARSession *)session didAddAnchors:(NSArray<ARAnchor *> *)anchors;
                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.1.sdk/System/Library/Frameworks/ARKit.framework/Headers/ARSession.h:47:12: note: 'ARSession' has been marked as being introduced in iOS 11.0 here, but the deployment target is iOS 10.0.0
@interface ARSession : NSObject
           ^
modules/arkit/arkit_session_delegate.h:45:1: note: annotate 'session:didAddAnchors:' with an availability attribute to silence this warning
[ 13%] - (void)session:(ARSession *)session didAddAnchors:(NSArray<ARAnchor *> *)anchors;
^
                                                                                  API_AVAILABLE(ios(11.0))
modules/arkit/arkit_session_delegate.h:45:61: warning: 'ARAnchor' is only available on iOS 11.0 or newer [-Wunguarded-availability-new]
- (void)session:(ARSession *)session didAddAnchors:(NSArray<ARAnchor *> *)anchors;
                                                            ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.1.sdk/System/Library/Frameworks/ARKit.framework/Headers/ARAnchor.h:35:12: note: 'ARAnchor' has been marked as being introduced in iOS 11.0 here, but the deployment target is iOS 10.0.0
@interface ARAnchor : NSObject <ARAnchorCopying, NSSecureCoding>
           ^
modules/arkit/arkit_session_delegate.h:45:1: note: annotate 'session:didAddAnchors:' with an availability attribute to silence this warning
- (void)session:(ARSession *)session didAddAnchors:(NSArray<ARAnchor *> *)anchors;
^
                                                                                  API_AVAILABLE(ios(11.0))
modules/arkit/arkit_session_delegate.h:46:18: warning: 'ARSession' is only available on iOS 11.0 or newer [-Wunguarded-availability-new]
- (void)session:(ARSession *)session didRemoveAnchors:(NSArray<ARAnchor *> *)anchors;
                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.1.sdk/System/Library/Frameworks/ARKit.framework/Headers/ARSession.h:47:12: note: 'ARSession' has been marked as being introduced in iOS 11.0 here, but the deployment target is iOS 10.0.0
@interface ARSession : NSObject
           ^
modules/arkit/arkit_session_delegate.h:46:1: note: annotate 'session:didRemoveAnchors:' with an availability attribute to silence this warning
- (void)session:(ARSession *)session didRemoveAnchors:(NSArray<ARAnchor *> *)anchors;
^
                                                                                     API_AVAILABLE(ios(11.0))
modules/arkit/arkit_session_delegate.h:46:64: warning: 'ARAnchor' is only available on iOS 11.0 or newer [-Wunguarded-availability-new]
- (void)session:(ARSession *)session didRemoveAnchors:(NSArray<ARAnchor *> *)anchors;
                                                               ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.1.sdk/System/Library/Frameworks/ARKit.framework/Headers/ARAnchor.h:35:12: note: 'ARAnchor' has been marked as being introduced in iOS 11.0 here, but the deployment target is iOS 10.0.0
@interface ARAnchor : NSObject <ARAnchorCopying, NSSecureCoding>
           ^
modules/arkit/arkit_session_delegate.h:46:1: note: annotate 'session:didRemoveAnchors:' with an availability attribute to silence this warning
- (void)session:(ARSession *)session didRemoveAnchors:(NSArray<ARAnchor *> *)anchors;
^
                                                                                     API_AVAILABLE(ios(11.0))
modules/arkit/arkit_session_delegate.h:47:18: warning: 'ARSession' is only available on iOS 11.0 or newer [-Wunguarded-availability-new]
- (void)session:(ARSession *)session didUpdateAnchors:(NSArray<ARAnchor *> *)anchors;
                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.1.sdk/System/Library/Frameworks/ARKit.framework/Headers/ARSession.h:47:12: note: 'ARSession' has been marked as being introduced in iOS 11.0 here, but the deployment target is iOS 10.0.0
@interface ARSession : NSObject
           ^
modules/arkit/arkit_session_delegate.h:47:1: note: annotate 'session:didUpdateAnchors:' with an availability attribute to silence this warning
- (void)session:(ARSession *)session didUpdateAnchors:(NSArray<ARAnchor *> *)anchors;
^
                                                                                     API_AVAILABLE(ios(11.0))
modules/arkit/arkit_session_delegate.h:47:64: warning: 'ARAnchor' is only available on iOS 11.0 or newer [-Wunguarded-availability-new]
- (void)session:(ARSession *)session didUpdateAnchors:(NSArray<ARAnchor *> *)anchors;
                                                               ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.1.sdk/System/Library/Frameworks/ARKit.framework/Headers/ARAnchor.h:35:12: note: 'ARAnchor' has been marked as being introduced in iOS 11.0 here, but the deployment target is iOS 10.0.0
@interface ARAnchor : NSObject <ARAnchorCopying, NSSecureCoding>
           ^
modules/arkit/arkit_session_delegate.h:47:1: note: annotate 'session:didUpdateAnchors:' with an availability attribute to silence this warning
- (void)session:(ARSession *)session didUpdateAnchors:(NSArray<ARAnchor *> *)anchors;
^
                                                                                     API_AVAILABLE(ios(11.0))
```

**Comment by akien-mga** [comment]
Fixed by #42459.
