### ISSUE TITLE
[TRACKER] Compilation warnings raised on Windows builds (MinGW64)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#29801]
**Godot version:**
3.2 master (6902700, after #29797)

**OS/device including version:**
Native or cross-compiling for Windows with MinGW64.

**Issue description:**
This tracker should list all current warnings raised for iOS builds, specifying when relevant the build options (`tools`, `target`, `warnings`) and compiler version.

If you're a contributor with edit access, please modify the OP directly to add more checkboxes for new/other warnings. If you don't have edit access, you can add them in a comment below.

### `warnings=all`

With MinGW 5.0.4 / GCC 8.3.0 on Linux (@akien-mga):

- [ ] `tools=yes target=debug` in `drivers/wasapi/audio_driver_wasapi.cpp` (cc @marcelofg55)

```
drivers/wasapi/audio_driver_wasapi.cpp:71:7: warning: base class 'struct IMMNotificationClient' has accessible non-virtual destructor [-Wnon-virtual-dtor]
 class CMMNotificationClient : public IMMNotificationClient {
       ^~~~~~~~~~~~~~~~~~~~~
```

With MinGW 6.0.0 / GCC 8.3.0 on macOS (@bruzvg):

- [x] `tools=yes target=debug` in `platform/windows/os_windows.cpp`

```
platform/windows/os_windows.cpp: In member function 'virtual uint64_t OS_Windows::get_unix_time() const':
platform/windows/os_windows.cpp:2196:11: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  return (*(uint64_t *)&ft - *(uint64_t *)&fep) / 10000000;
           ^~~~~~~~~~~~~~~
platform/windows/os_windows.cpp:2196:30: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  return (*(uint64_t *)&ft - *(uint64_t *)&fep) / 10000000;
                              ^~~~~~~~~~~~~~~~
```

### `warnings=extra`

With MinGW 5.0.4 / GCC 8.3.0 on Linux (@akien-mga):

- [x] `tools=yes target=debug` in `platform/windows/context_gl_windows.cpp` [-Wcast-function-type]

```
platform/windows/context_gl_windows.cpp: In member function 'Error ContextGL_Windows::initialize()':
platform/windows/context_gl_windows.cpp:184:113: warning: cast between incompatible function types from 'PROC' {aka 'long long int (*)()'} to 'PFNWGLCREATECONTEXTATTRIBSARBPROC' {aka 'HGLRC__* (*)(HDC__*, HGLRC__*, const int*)'} [-Wcast-function-type]
   wglCreateContextAttribsARB = (PFNWGLCREATECONTEXTATTRIBSARBPROC)wglGetProcAddress("wglCreateContextAttribsARB");
                                                                                                                 ^
platform/windows/context_gl_windows.cpp:207:88: warning: cast between incompatible function types from 'PROC' {aka 'long long int (*)()'} to 'PFNWGLSWAPINTERVALEXTPROC' {aka 'bool (*)(int)'} [-Wcast-function-type]
  wglSwapIntervalEXT = (PFNWGLSWAPINTERVALEXTPROC)wglGetProcAddress("wglSwapIntervalEXT");
                                                                                        ^
platform/windows/context_gl_windows.cpp:208:97: warning: cast between incompatible function types from 'PROC' {aka 'long long int (*)()'} to 'PFNWGLGETSWAPINTERVALEXTPROC' {aka 'int (*)()'} [-Wcast-function-type]
  wglGetSwapIntervalEXT = (PFNWGLGETSWAPINTERVALEXTPROC)wglGetProcAddress("wglGetSwapIntervalEXT");
                                                                                                 ^
```

- [x] `tools=yes target=debug` in `platform/windows/joypad_windows.cpp` [-Wcast-function-type]

```
platform/windows/joypad_windows.cpp: In member function 'void JoypadWindows::load_xinput()':
platform/windows/joypad_windows.cpp:546:96: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'JoypadWindows::XInputGetState_t' {aka 'long unsigned int (*)(long unsigned int, _XINPUT_STATE*)'} [-Wcast-function-type]
  XInputGetState_t func = (XInputGetState_t)GetProcAddress((HMODULE)xinput_dll, "XInputGetState");
                                                                                                ^
platform/windows/joypad_windows.cpp:547:100: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'JoypadWindows::XInputSetState_t' {aka 'long unsigned int (*)(long unsigned int, _XINPUT_VIBRATION*)'} [-Wcast-function-type]
  XInputSetState_t set_func = (XInputSetState_t)GetProcAddress((HMODULE)xinput_dll, "XInputSetState");
                                                                                                    ^
```

- [x] `tools=yes target=debug` in `platform/windows/os_windows.cpp` [-Wcast-function-type]

```
platform/windows/os_windows.cpp: In function 'int QueryDpiForMonitor(HMONITOR, _MonitorDpiType)':
platform/windows/os_windows.cpp:1194:92: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'GetDPIForMonitor_t' {aka 'long int (*)(HMONITOR__*, _MonitorDpiType, unsigned int*, unsigned int*)'} [-Wcast-function-type]
   getDPIForMonitor = Shcore ? (GetDPIForMonitor_t)GetProcAddress(Shcore, "GetDpiForMonitor") : NULL;
                                                                                            ^
platform/windows/os_windows.cpp: In member function 'virtual Error OS_Windows::initialize(const OS::VideoMode&, int, int)':
platform/windows/os_windows.cpp:1254:127: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'SetProcessDpiAwareness_t' {aka 'long int (*)(_SHC_PROCESS_DPI_AWARENESS)'} [-Wcast-function-type]
    SetProcessDpiAwareness_t SetProcessDpiAwareness = (SetProcessDpiAwareness_t)GetProcAddress(Shcore, "SetProcessDpiAwareness");
                                                                                                                               ^
platform/windows/os_windows.cpp: In member function 'virtual Error OS_Windows::open_dynamic_library(String, void*&, bool)':
platform/windows/os_windows.cpp:2253:122: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'PAddDllDirectory' {aka 'void* (*)(const wchar_t*)'} [-Wcast-function-type]
  PAddDllDirectory add_dll_directory = (PAddDllDirectory)GetProcAddress(GetModuleHandle("kernel32.dll"), "AddDllDirectory");
                                                                                                                          ^
platform/windows/os_windows.cpp:2254:134: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'PRemoveDllDirectory' {aka 'int (*)(void*)'} [-Wcast-function-type]
  PRemoveDllDirectory remove_dll_directory = (PRemoveDllDirectory)GetProcAddress(GetModuleHandle("kernel32.dll"), "RemoveDllDirectory");
                                                                                                                                      ^
platform/windows/os_windows.cpp: In function 'BOOL is_wow64()':
platform/windows/os_windows.cpp:3035:108: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'LPFN_ISWOW64PROCESS' {aka 'int (*)(void*, int*)'} [-Wcast-function-type]
  fnIsWow64Process = (LPFN_ISWOW64PROCESS)GetProcAddress(GetModuleHandle(TEXT("kernel32")), "IsWow64Process");
                                                                                                            ^
platform/windows/os_windows.cpp: In constructor 'OS_Windows::OS_Windows(HINSTANCE)':
platform/windows/os_windows.cpp:3388:88: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'GetPointerTypePtr' {aka 'int (*)(unsigned int, long unsigned int*)'} [-Wcast-function-type]
   win8p_GetPointerType = (GetPointerTypePtr)GetProcAddress(user32_lib, "GetPointerType");
                                                                                        ^
platform/windows/os_windows.cpp:3389:97: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'GetPointerPenInfoPtr' {aka 'int (*)(unsigned int, tagPOINTER_PEN_INFO*)'} [-Wcast-function-type]
   win8p_GetPointerPenInfo = (GetPointerPenInfoPtr)GetProcAddress(user32_lib, "GetPointerPenInfo");
                                                                                                 ^
```

- [x] `tools=yes target=debug` in `platform/windows/os_windows.cpp` [-Wmissing-field-initializers]

```
platform/windows/os_windows.cpp: In member function 'virtual void OS_Windows::set_custom_mouse_cursor(const RES&, OS::CursorShape, const Vector2&)':
platform/windows/os_windows.cpp:2383:27: warning: missing initializer for member '_ICONINFO::xHotspot' [-Wmissing-field-initializers]
   ICONINFO iconinfo = { 0 };
                           ^
platform/windows/os_windows.cpp:2383:27: warning: missing initializer for member '_ICONINFO::yHotspot' [-Wmissing-field-initializers]
platform/windows/os_windows.cpp:2383:27: warning: missing initializer for member '_ICONINFO::hbmMask' [-Wmissing-field-initializers]
platform/windows/os_windows.cpp:2383:27: warning: missing initializer for member '_ICONINFO::hbmColor' [-Wmissing-field-initializers]
```

- [x] `tools=yes target=debug` in `platform/windows/os_windows.cpp` [-Wimplicit-fallthrough=]

```
platform/windows/os_windows.cpp: In member function 'LRESULT OS_Windows::WndProc(HWND, UINT, WPARAM, LPARAM)':
platform/windows/os_windows.cpp:557:4: warning: this statement may fall through [-Wimplicit-fallthrough=]
    }
    ^
platform/windows/os_windows.cpp:558:3: note: here
   case WM_MBUTTONDOWN:
   ^~~~
```

- [x] `tools=yes target=debug` in `drivers/windows/file_access_windows.cpp` [-Wmissing-field-initializers]

```
drivers/windows/file_access_windows.cpp: In member function 'virtual Error FileAccessWindows::_open(const String&, int)':
drivers/windows/file_access_windows.cpp:96:28: warning: missing initializer for member '_WIN32_FIND_DATAW::ftCreationTime' [-Wmissing-field-initializers]
   WIN32_FIND_DATAW d = { 0 };
                            ^
drivers/windows/file_access_windows.cpp:96:28: warning: missing initializer for member '_WIN32_FIND_DATAW::ftLastAccessTime' [-Wmissing-field-initializers]
drivers/windows/file_access_windows.cpp:96:28: warning: missing initializer for member '_WIN32_FIND_DATAW::ftLastWriteTime' [-Wmissing-field-initializers]
drivers/windows/file_access_windows.cpp:96:28: warning: missing initializer for member '_WIN32_FIND_DATAW::nFileSizeHigh' [-Wmissing-field-initializers]
drivers/windows/file_access_windows.cpp:96:28: warning: missing initializer for member '_WIN32_FIND_DATAW::nFileSizeLow' [-Wmissing-field-initializers]
drivers/windows/file_access_windows.cpp:96:28: warning: missing initializer for member '_WIN32_FIND_DATAW::dwReserved0' [-Wmissing-field-initializers]
drivers/windows/file_access_windows.cpp:96:28: warning: missing initializer for member '_WIN32_FIND_DATAW::dwReserved1' [-Wmissing-field-initializers]
drivers/windows/file_access_windows.cpp:96:28: warning: missing initializer for member '_WIN32_FIND_DATAW::cFileName' [-Wmissing-field-initializers]
drivers/windows/file_access_windows.cpp:96:28: warning: missing initializer for member '_WIN32_FIND_DATAW::cAlternateFileName' [-Wmissing-field-initializers]
```

- [x] `tools=no target=release` in `platform/windows/os_windows.cpp`

```
platform/windows/os_windows.cpp: At global scope:
platform/windows/os_windows.cpp:97:15: warning: 'String format_error_message(DWORD)' defined but not used [-Wunused-function]
 static String format_error_message(DWORD id) {
               ^~~~~~~~~~~~~~~~~~~~
```

**Comment by Anutrix** [comment]
Changing `(function_name)` to `(function_name)(void(*)())` should fix the `cast between incompatible function types from 'FARPROC'` warnings but I am unable to test it right now because haven't done cross-compiling before. So do test it.
Also, it might decrease readability.

**Comment by Anutrix** [comment]
>
>
> With MinGW 6.0.0 / GCC 8.3.0 on macOS (@bruzvg):
> 
>     * [ ]  `tools=yes target=debug` in `platform/windows/os_windows.cpp`
> 
> 
> ```
> platform/windows/os_windows.cpp: In member function 'virtual uint64_t OS_Windows::get_unix_time() const':
> platform/windows/os_windows.cpp:2196:11: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>   return (*(uint64_t *)&ft - *(uint64_t *)&fep) / 10000000;
>            ^~~~~~~~~~~~~~~
> platform/windows/os_windows.cpp:2196:30: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>   return (*(uint64_t *)&ft - *(uint64_t *)&fep) / 10000000;
>                               ^~~~~~~~~~~~~~~~
> ```
> 
>

This can me marked as done I guess.

**Comment by akien-mga** [comment]
Moved the last warning to #35194.
