### ISSUE TITLE
[TRACKER] Script editor enhancements

### ISSUE THREAD

**Issue by GlaDOSik** [godotengine/godot#2982]
I love writing code so here are some script editor enhancements I would like to see in Godot. It's not a top priority but it might be a good material for 2.1. What do you think? Add your own ideas.
- [x] optional code minimap #4881 
- [ ] optional pigments (display colors in editor) #4882
- [x] multi-line editing #4884
- [x] highlight unused variables #4885
- [x] the word (variable, method, etc) highlighting <b>(2.0.2)</b>
- [x] support for foreign characters (new editor font (Inconsolata is neat) + support through the whole engine)
- [x] possibility to hide the script list and use tabs to switch between them (maybe even hide inspector ? - small screen mode) <b>(kubecz3k)</b>
- [x] full screen mode, ability to switch between scripts that would appear as a list only when needed (similar as the idea above) <b>(purpleorangegames)</b>
- [ ] improve autocomplete - extending script, Globals.get(""), paths to resources <b>(jeremi360)</b>
- [x] ability to move scripts up/down in the script list <b>(kubecz3k)</b>
- [ ] ability to move between opened scripts on the script list from the keyboard <b>(kubecz3k)</b>
- [x] automatic scrolling when I hit the first line in text selection mode (pressed left mouse button + drag)
- [x] numpad arrow/home/end/pgup/pgdn should work as usual when numlock is off <b>(grigi)</b> (Already added by #3269)
- [ ] copy-on-select, and paste with middle-click (maybe optional?) <b>(grigi)</b>
- [x] tab should enter spaces instead of a tab character (optional mode?) <b>(grigi)</b>
- [x] ability to collapse bundled lines of code (ifs, functions, etc.) <b>(Todor Imreorov via FB)</b> #2732
-  [x] go to implementation (jump to the implementation of highlighted function - Shift+F1 works only for built-in functions) <b>(puppetmaster)</b> #3238 #4886
- [ ] split editor horizontally/vertically **(vnen)** #5315
- [ ] Less aggressive error highlighting **(DriNeo)** #7502
- [x] smooth scrolling (not line by line) **(toger5)** #8953

![scripteditor](https://cloud.githubusercontent.com/assets/3484686/11576580/f1a824e4-9a17-11e5-9756-e28cc256d9a5.jpg)

**Comment by kubecz3k** [comment]
I would love to have additional ability to switch between script list on the left and script list in tabs (like in previous Godot versions). I have rather small laptop screen and this would make my life easier quite a lot :) 
Multi-line editing and word-highlighting also sounds very good :+1: . I would also definitely add more colors, for the syntax highlighting, especially "variable"(local or member)  and "method/function"  highlighting/recognition (declaration and usage both a little different color, declaration could be bolded).

**Comment by GlaDOSik** [comment]
"I would love to have additional ability to switch between script list on the left and script list in tabs (like in previous Godot versions)." You mean like the old Resource tab?

**Comment by kubecz3k** [comment]
Maybe I will post a picture that will illustrates what I meant:
https://goo.gl/photos/Ecp8N6Mj5ZQeRCYf7
(sorry for quality of the first example, took it from you tube video, since don't have any 1.1 project)

**Comment by GlaDOSik** [comment]
I see. Yeah, that's a good idea. Godot is pretty lighweight so I also use it on old laptop with small screen. And there isn't too much space for code. I added your idea to the first post.

**Comment by neikeq** [comment]
The word (variable, method, etc) highlighting would be good to have.

**Comment by jeremi360** [comment]
Godot editor already support foreign characters you must,
just change font in editor settings to font imported with "Mode" set to "Unicode".

**Comment by jeremi360** [comment]
Auto complete for when you extending script.
Now is working only for extending build in classes.
Also auto complete for Globals.get("") and for paths to resources.

**Comment by reduz** [comment]
minimap should be pretty easy, and word highlighting for search i'm not so
sure but should be rather easy too i guess
the only feature that seems like a lot of work is code folding

**Comment by neikeq** [comment]
I am not sure about OP, but I didn't meant search word highlighting (though this is cool too). When the cursor is over a variable (or method), this variable and all of its usages will be highlighted.
![Example](https://cloud.githubusercontent.com/assets/7718100/11615030/01200e16-9c55-11e5-82c5-ee0d9fb9636e.png)

**Comment by AlexHolly** [comment]
+1 (syntax highlighting, especially "variable"(local or member) and "method/function")

**Comment by kubecz3k** [comment]
Couple more enhancements from me: 
* Ability to move scripts up/down in the script list (+keyboard shortcuts for this maybe alt+shift+up/down arrow?)
* Ability to move between opened scripts on the script list from the keyboard (maybe ctrl+shift+up/down arrow)
Would be happy if you @GlaDOSik could add these two to the list in the first post :)

**Comment by GlaDOSik** [comment]
<b>neikeq</b> Yes, I meant highlighting selected word in the script. 
Thanks for your ideas. I updated the first post.

**Comment by purpleorangegames** [comment]
Would love a full screen mode for coding in gdscript, nothing to distract or reduce the work area.
And a way to switch between scripts that would appear as a list only when needed.

**Comment by reduz** [comment]
many great ideas, let's label this 2.1

**Comment by purpleorangegames** [comment]
https://github.com/godotengine/godot/issues/2982#issuecomment-164160423

**Comment by grigi** [comment]
Hi, I have 2 requests to be added:

1. `Numpad arrow/home/end/pgup/pgdn should work as usual when numlock is off`

  I have a notebook with a numpad, and I use the numpad with numlock off. Currently on Gotot when I press up/down/left/right/home/end/pgup/pgdn nothing happens. It would be great if they can work like the regular keys. This is on Linux.
2. `Copy-on-select, and paste with middle-click`

  The other thing is, in Linux, when selecting text, it automatically copies it to your clipboard. Likewise, middle-click is paste. I find this extremely useful and is quite used to it. I understand that this could confuse people, but even as an option it would be great.

**Comment by GlaDOSik** [comment]
The list was updated. But I'm not sure about 3rd point. GDScript uses tab-based indentation so I don't know how it should work with spaces.

**Comment by grigi** [comment]
I have been using GDScript with spaces, but lots of sample code I find on the internet is space indented. I think it is clear as long as you stick to one or the other?
Maybe an option to clean indentation as a macro would be a better idea? I know Komodo can be configured to automatically fix indentation to a desired style on load, and it works well enough. It does the little things, like replace tabs with 4 spaces, removes all trailing space, etc...
But that it probably too complicated to implement to be worth it, as it could really break some peoples established workflow.

I do agree that point 3 as it currently stands probably isn't very useful.

**Comment by akien-mga** [comment]
Regarding this point 3, I once opened #1340 but it seems far from being consensual... Now I got used to tabs, but I'd like to have the possibility to use spaces too. It is not as simple as changing the effect of the tab key though, the editor hardcodes the addition of tabs in some context, e.g. to autoindent when opening a block, etc.. It would have to be made configurable too (and depend on the editor setting for indentation).

**Comment by puppetmaster-** [comment]
This function would be also cool to have.
- put/click cursor on name of function in code and jump with F3 to function (like in eclipse) 

`node2d.set_pos(getNew 'click here' Pos())`

`func getNewPos():`
`      return Vector2d(0,1)`

**Comment by ndee85** [comment]
I would also love to see word highlighting in script editor. This makes navigating through the script and finding multiple variables/objects or values so much easier!

**Comment by neikeq** [comment]
I think the following requests should go into separated issues:
- **highlight unused variables**. This looks more like a static GDScript analyzer request.
- **highlight function call of the non-existent function**. Same as above
- **improve autocomplete - extending script, Globals.get(""), paths to resources**. Auto-completion improvements are also GDScript related request, not editor.
- **go to implementation (jump to the implementation of highlighted function - Shift+F1 works only for built-in functions)**. This is also GDScript related, and could be part of a feature request for refactoring tools.

**Comment by GlaDOSik** [comment]
I could do it, but there's already a lot of issues and I think it's handy to have them on one nice list. Maybe, renaming the issue would be enough?

**Comment by vnen** [comment]
This list is good as a reference, but we should also make each item an individual issue that can be actually tackled. Then we can have PRs closing the individual issues in manageable steps and enhance the script editor gradually.

A neat thing to do, parallel to individual issues, would be to add checkboxes to the top post here.

**Comment by trollworkout** [comment]
Yeah I was gonna say this is 20 issues in one. Buy 1 get 19 for free. Each issue should be an individual topic makes life easier for devs I found out.

**Comment by neikeq** [comment]
Yes, that's why we have the tracker label now.

**Comment by trollworkout** [comment]
Also about half of these are already done based on pull requests and comments? Is hard to close these issues when you have them all in one list.

**Comment by GlaDOSik** [comment]
Fine, I'll do it. I'm still not comfortable to make more issue requests. There's already more than a thousand of them and I feel the new ones will sink down very soon. But yeah, I get your point. I'm on it.

**Comment by reduz** [comment]
optional tree organized scripts and code minimap would be nice additions

**Comment by wahming** [comment]
It'd be nice if we could disable case sensitivity in autocomplete. So it'd stop caring that I typed in lowercase and just suggest matching uppercase items.

**Comment by Zylann** [comment]
@wahming are you sure? https://github.com/godotengine/godot/issues/5964

**Comment by caryoscelus** [comment]
Hmm, what about global search? It was kinda mentioned in #5747, but now it's closed and global search is nowhere on this list. Should i open a new issue?

**Comment by kubecz3k** [comment]
@caryoscelus yes you should :)

**Comment by HummusSamurai** [comment]
` ability to collapse bundled lines of code (ifs, functions, etc.) (Todor Imreorov via FB) #2732`

Can be considered closed after the latest merge.

**Comment by Hinsbart** [comment]
@HummusSamurai really, did I miss something? ;)
I haven't seen this being implemented recently.

**Comment by DriNeo** [comment]
I would like to add my minor improvement request.

https://github.com/godotengine/godot/issues/7502

**Comment by HummusSamurai** [comment]
@Hinsbart Ah my bad, the PR has not been merged yet.

But issue https://github.com/godotengine/godot/issues/2732 can be considered complete after PR https://github.com/godotengine/godot/pull/8974

I'll point it out in the issue if the PR doesn't close it.

**Comment by vnen** [comment]
@HummusSamurai AFAIK #8974 is just about functions overview, it does not implement code folding as is requested in #2732.

**Comment by toger5** [comment]
might also add :
 - smooth scrolling (not line by line) #8953

**Comment by vnen** [comment]
Updated the OP to add the last two requests.

**Comment by Jvanmourik** [comment]
I would like to expand on:

> split editor horizontally/vertically (vnen) [#5315](https://github.com/godotengine/godot/issues/5315)

It would be nice if you could pop out a script editor tab (or multiple tabs if you will) into it's own application window. This way you can position Godot's editors across multiple computer screens.

Support for multiple application windows in general could also add unique gameplay possibilities for games.

**Comment by KoBeWi** [comment]
Found this issue and thought it's not worth to make a separate one.

My idea:
`Allow for closing scripts with Middle Click, just like you can close scene tabs.`

**Comment by char0xff** [comment]
I think the editor is missing an auto-wrap option. Very useful when typing long strings. You can write multiple strings and concatenate them with "+" but if you ever want to change the text again it's not a good solution.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
i would only request a better Ctrl+Click and better autocomplete that can figure stuff out intelligently

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
@Jvanmourik  it might be nice but the editor does not support multi window. the pop up window would simply be a subwindow inside that same window

**Comment by vnen** [comment]
@CarlGustavAlbertDwarfsteinYung 
> i would only request a better Ctrl+Click and better autocomplete that can figure stuff out intelligently

This is too vague. We all want a "better" engine. You should point out what exactly is failing, where it could complete but it's not doing (and preferably open a new issue about it, if there isn't one already). Especially since this is a tracker for multiple issues, this only adds noise, so please refrain to comment if you don't have a specific need.

Also, you are replying to a 6-month old comment, which is still a valid request (the editor will eventually support multiple windows).

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
@vnen  you woke up on the wrong side of the bed eh? is okay man i like adding noise. get used to it ;)

**Comment by akien-mga** [comment]
@CarlGustavAlbertDwarfsteinYung Nobody has to "deal with it". If a core developer tells you that your comment is noise and counter productive, it's not about waking up on the wrong side of the bed, it's about trying to keep things organized and efficient with an issue tracker strong of thousands of issues, and 300 to 500 more per month.

This issue is a *tracker*, which means that it's meant to keep references to other issues opened regarding specific script editor enhancements. Describing vague enhancement here without opening a detailed issue is not only useless, but also a waste of our time.

> there are other examples. I hope you don't want me to list them all do you?

So yes, open an issue and *list them all*. Then we can see how to improve the Ctrl-Click behaviour. We don't have a magic wand to "improve" things if we don't know what has to be done.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
@akien-mga  Nah

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
You guys are overworked. You need some time off.

**Comment by mhilbrunner** [comment]
Seeing how old this issue is and how many of these were implemented, I'll close this issue. New issues should go into new issues, and for feature proposals there is now the proposals repository. :)
