### ISSUE TITLE
[TRACKER] Internationalization-related issues (CJK and RTL support, IME, fonts, etc.)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3081]
We have quite a few issues and PRs (both new and old) related to internationalization issues, especially CJK and Arabic input and display support, input method engines, etc., so I thought to list them all here so that a global solution can be discussed and implemented.

**Issues:**
- [x] #29: IME support for non-latin Unicode characters (CJK, Arabic, etc.) 
- [x] #531: Default font in editor is non-unicode
- [x] #871: Godot editor accepts non-ascii chars but doesn't show them
- [ ] #982: Support for RTL input and display
- [x] #1708: Can't import template if folder contains non-ascii characters
- [x] #1848: RichTextLabel does not support wrapping for Chinese font
- [x] #2379: International font problem with OptionButton
- [x] #2491: Cannot display CJK properly on linux
- [ ] #2689: Alt codes aren’t picked up by text 
- [ ] #2915: Missing support for non-ascii keyboard bindings
- [ ] #9961: Add HarfBuzz for text shaping
- [x] #9398: Improve internationalization support for projects via gettext
- [ ] #31432: Add support for gettext plural forms

**Pull requests:**
- #194: Fixed issue #29 Editor doesn't support CJK **(closed)**
- #245: Split font atlas texture into 1024*1024 size if atlas size > 1024 **(merge conflicts, closed)**
- #257: New add dynamic ttf loading support **(closed, obsoleted by 2.1 developments)**
- #287: Add editor localization support (WIP) **(closed, obsoleted by 2.1 developments)**
- #300: Fix CJK input on ios platform **(merge conflicts)**
- #2297: Add RTL text support and fa locale **(closed, was using copylefted code apparently)**
- #2799: Add character selection to font importer **(merge conflicts)**
- #2886: RTL support based on ICU library **(merge conflicts, but could likely get rebased if asked for)**

**Comment by est31** [comment]
I'd also add these two issues:
* #2379 International font problem with OptionButton
* #2915 Non-ascii keyboard bindings

**Comment by akien-mga** [comment]
Most display issues were fixed by 3e8eb39 :-D
Now to the input stuff... :-)

**Comment by vnen** [comment]
While working on input, maybe #2689 should be looked too.

**Comment by MoustafaC** [comment]
Just checked out Arabic support in 3.0 (build ade39f5). The letters are currently rendered LTR.

![screenshot from 2017-11-26 22-48-26](https://user-images.githubusercontent.com/4623254/33250060-4d0c4b84-d2fc-11e7-9d95-6b3e1734a592.png)

**Comment by mhilbrunner** [comment]
Closing this due to the age and most of those being fixed.

**Comment by Teashrock** [comment]
@akien-mga 
You added this to 4.0, but you forgot to reopen.

Thank you.

**Comment by akien-mga** [comment]
There's nothing to reopen, all issues on this tracker are fixed.

**Comment by Teashrock** [comment]
Okay, sorry.
