### ISSUE TITLE
[TRACKER] FBX Importer bugs

### ISSUE THREAD

**Issue by RevoluPowered** [godotengine/godot#30822]
**Known issues:**
- [x] Extra transforms created for mesh instances. (not found any nasty side effects of this; this is an intentional step in creating the scene, it simply requires them to exist temporarily so we need to add a step to remove them after we have used them.)
- [ ] Pivots from Maya do not work - this needs a lot of work in assimp to fix this.
- [x] When an animated mesh has not executed any animation the rest pose is wrong.

**If you're using Maya:**
A workaround for the pivots in Maya/Autodesk product not functioning is to import the FBX file into blender then re-export as FBX.

This is a temporary workaround so please be patient as we are working on fixing it.

**Comment by fire** [comment]
Multi root models are supported by Godot, but the skeleton has to be defined at the correct point so that the armature is not in the skeleton.

Investigating.

**Comment by RevoluPowered** [comment]
@fire Hey, seem to have made some progress adding in support for multi parents.

I used the same logic that you have used in the past and it seems to load, but unfortunately the other problem with the multi parents being applied is that the transforms for the mesh and the skeleton are off.

However when the actual mesh plays the animation I can see the bones behaving precisely like blender.

![image](https://user-images.githubusercontent.com/748770/61958908-2d484680-afba-11e9-95a6-71e5a7ad9803.png)

I think this is closer because now we have 100% of the bones in the scene. 

Let me know when you're available and we can figure this out. I'll try to debug further.

**Comment by RevoluPowered** [comment]
Sidenote, for this to work I have removed FBX specific code too.

**Comment by RevoluPowered** [comment]
So next step for multi parents is simply getting the transform to follow the bones again.

**Comment by RevoluPowered** [comment]
So further progress just made, got the multi parent working now without fbx specific override :)
![deepin-screen-recorder_Select area_20190726153543](https://user-images.githubusercontent.com/748770/61959339-1b1ad800-afbb-11e9-848d-3d3603d76d54.gif)

**Comment by RevoluPowered** [comment]
I will be fixing the offsets so that they do not override the position, scale and rotation of the mesh, as this was causing issues.

**Comment by RevoluPowered** [comment]
We are making progress on a scaling bug. multi parent now works but xform is off by 40~ degrees we are trying different strategies to fix this for the 'bird.fbx'

**Comment by RevoluPowered** [comment]
We are still in the process of debugging the following issues:

- Scaling on FBX import differs to the animationbecause we aren't able to replicate the tree 1:1 from assimp yet we will hopefully conclude this tomorrow.
- We have ensured duplicate parents do not get added by using OAHashMap.

**Comment by fire** [comment]
Map mode is initialized to NULL. Should be created and then given the pointer.

```
struct AssimpImageData {
	Ref<Image> raw_image;
	Ref<ImageTexture> texture;
	aiTextureMapMode map_mode;
};
```

**Comment by fire** [comment]
Add blend shape is called after surfaces are created.

https://github.com/godotengine/godot/blob/7bb2215ed0d7415179a8b59ad4766a3b573cf696/scene/resources/mesh.cpp#L886

Triggers this condition and fails to create mesh.

**Comment by RevoluPowered** [comment]
```Map mode is initialized to NULL. Should be created and then given the address of.

struct AssimpImageData {
	Ref<Image> raw_image;
	Ref<ImageTexture> texture;
	aiTextureMapMode map_mode[2];
};

Edited: With newer change``` @fire has merged the fix for this.

**Comment by RevoluPowered** [comment]
> Multi root models are supported by Godot, but the skeleton has to be defined at the correct point so that the armature is not in the skeleton.
> 
> Investigating.

This is something I am also having trouble with setting the skeleton path seems to fail with some valid paths to the skeleton mesh even when you know the skeleton is on the root and supply ".." as the skeleton path like GLTF2.

I am noticing a subtle warning when manually binding the skeleton too which throws a warning "skeleton not found". 

100% reproducible if you select more than 1 mesh and try to assign the skeleton. Shows up infrequently during import. Noticed other importers avoid calling it and if they do they use set_skeleton_path(String("..")) as per GLTF2.

@reduz any ideas what could cause the set_skeleton_path to fail?

**Comment by IuryBorges1993** [comment]
Facial animation on Godot results in strange deformation.

in blender it works all normal.

in godot the eyes do not close and the mouth is giving a strange deformation.


![Captura de tela de 2020-01-10 10-12-48](https://user-images.githubusercontent.com/39449626/72182045-6c801d80-33c9-11ea-9efe-267387b8f8c9.png)

**Comment by fire** [comment]
https://github.com/godotengine/godot/pull/38966 is the current work in progress for this.

Pivots work but other bugs appeared.

Closing so we can use the pr request as the tracker.
