### ISSUE TITLE
[TRACKER] inst2dict and dict2inst related issues

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#33348]
**Godot version:**
3.2+, 4.0

**Issue description:**
There are quite a bunch of old issues present with `inst2dict` and `dict2inst` that it's worth to add a tracker for it. I'm currently working on some of them.

## Issues

- [ ] `inst2dict` does not turn classes inside classes to dict #6533.
- [x] `inst2dict` references in exported file non compatible with editor #26188.
- [ ] `inst2dict` does not work with objects having no script on them #30077.
- [ ] `dict2inst` does not work on classes with _init parameters #30572.
- [x] `inst2dict` and `dict2inst` fail in compiled version of game #31045.
- [ ] `inst2dict` do not serialize object correctly due to calling getter methods #33015.

## Fixes
I think it would be best if these fixes could be reviewed in order so that smaller fixes can be rebased on top of bigger ones more easily if deemed satisfactory:

1. Make inst2dict and dict2inst work recursively #33137.
2. Fix `inst2dict` calling to getters to retrieve value #33018.
3. Make `dict2inst` to work with arbitrary `_init` parameters #32534.

They could as well be targeted for 4.0 but see for yourself.

CC @vnen @bojidar-bg.

**Comment by capnm** [comment]
[?] Fix the accessibility of the online API docs (might be a more general issue).

The https://docs.godotengine.org/en/latest/search.html?q=inst2dict query currently returns only a link to unusable c# hints instead of
https://docs.godotengine.org/en/latest/classes/class_@gdscript.html#class-gdscript-method-inst2dict

**Comment by nhold** [comment]
Can we add the following:

A class de-serialised with dict2inst fails if the class has moved it's path. A classes ability to be de-serialised should not be linked to it's path. I do get this might require a re-write to the entire gdscript language to force class names.

**Comment by Xrayez** [comment]
@capnm I think you could open an issue about this at [godot-docs](https://github.com/godotengine/godot-docs). It fails to search the class ref for some reason. I've stumbled upon this with other keywords if I recall correctly.

@nhold you could open a separate issue and/or proposal to discuss the best way to implement it first. But it feels like this could be solved relatively easy by writing global class name to dictionary along with script path.

Anyways, added to `Other issues` section because they currently have no home.
