### ISSUE TITLE
[TRACKER] Issues with Editable Children

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33790]
**Godot version:**
3.1 beta2

**Issue description:**
I noticed there are many issues with editable children (after closing a duplicate just now) and all of them are caused by "Editable Children" property stored in scene root, not in the node. Metadata might be perfect place to store this information, but it can't happen until #12990 is fixed. Meantime, I thought that it makes sense to create some tracker for these issues.

- [x] #28861 Editable children property persists after node deletion
- [x] #27064 Editable Children Flag Turns Off Due to Node Path Change
- [x] #23979 Data in editable children lost without warning when moving node in tree
- [x] #20409 Rename an "Instanced Scene as Node" disables "Editable Children"
- [x] #6455 Instance loses it's "Editable children" flag after renaming. Affects saved edits too
- [x] #12075 "Editable Children" of instanced scenes' export variables not updated during duplication
- [ ] #27023 Editable Children doesn't overwrite properties some times

There's probably more of them, but all of the above are closely related and could potentially be closed by single PR.

Also related: #20292

**Comment by hilfazer** [comment]
Maybe the information about editable children could be kept together with node? Like

`[node name="integer" parent="Lines" instance=ExtResource( 2 ) editable="y"]`

No need to deal with paths.

**Comment by nathanfranke** [comment]
https://github.com/godotengine/godot/issues/34768

**Comment by PLyczkowski** [comment]
Related: #43261

**Comment by jitspoe** [comment]
Before I enter one, is there an issue for this case?:

If you have a scene that contains another scene and "Editable Children" is set, then you modify the child scene while both scenes are open, the (unchanged) state of the parent scene will override the change to the child scene, even if you don't explicitly change it.  This can have some very unexpected problems if, for example, the child scene contains an imported model and you reimport to find your animations do not update.  Also has a habit of wiping out materials.

**Comment by KoBeWi** [comment]
Closing as all related issues are fixed by #45265
#27023 is likely still not fixed, but it's slightly different. I'll verify it later.
