### ISSUE TITLE
[TRACKER] Issues with Go to definition (Ctrl + Click)

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33898]
**Godot version:**
3.2 beta2

**Issue description:**
Soo there's this old issue #7080 which is a bit chaotic, so I decided to make a fine tracker for all the cases. If someone knows an example of go to definition failing, pls comment. Also not all examples have issues created, so scroll below for code.

So far it is known that go to definition (Ctrl + Click) fails on:
- [ ] Relative paths (#33859)
- [ ] Preloaded script used as type
- [ ] Property accessors
- [ ] Typed onready variables (related to #33434)
- [ ] Members of custom class' properties (might be something broader)
- [ ] Methods from custom classes used as argument types (might be related to above)
- [ ] Autoload singletons with built-in scripts

Non-issued examples:

- Preloaded script used as type
```
const THE_SCRIPT = preload("res://TheScript.gd")

var variable: THE_SCRIPT #fails
var b = THE_SCRIPT.new() #works
```

- Property accessors
```
var test: Control
test.set_visible(false) #should jump to visible property doc, goes to Control
```

- Typed onready variables
```
onready var test_node: Control = $Some/Control
func _ready() -> void:
	test_node.hide() #hide isn't found
```

- Members of custom class' properties
```
class_name TestClass
var velocity: Vector2

#another script
func test(test_obj: TestClass):
	test_obj.velocity.reflect(Vector2()) #can't go to reflect
```

- Methods from custom classes used as argument types
```
class_name Test
func test_method():
	pass
#another script
func meth(arg: Test, vec: Vector2):
	var brg := Test.new()
	arg.test_method() #this doesn't work (can't go to definition)
	brg.test_method() #this does
        vec.normalized() #this too
```

- Autoload singletons with built-in scripts
```
func some_func():
    MySingleton.do_stuff() #clicking MySingleton won't work, but do_stuff() will jump correctly
```

**Comment by capnm** [comment]
[ ?] Property Descriptions
e.g. set (get) _process_priority should point to the **process_priority** property

https://docs.godotengine.org/en/3.1/classes/class_node.html#class-node-method-set-process-priority
https://docs.godotengine.org/en/latest/classes/class_node.html#class-node-method-set-process-priority
https://docs.godotengine.org/en/latest/classes/class_node.html#class-node-property-process-priority

**Comment by dalexeev** [comment]
Also, this does not work with scene singletones (the scene script is internal). At the same time, if you click on the singleton property, it will work.

**Comment by Anutrix** [comment]
Will be fixed by #33898.

**Comment by Janglee123** [comment]
"Typed onready var" example works if the script belongs to the currently open scene.
