### ISSUE TITLE
List of probably unused signals

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#37604]
**Godot version:**
4.0.dev.custom_build. 321ce4d4c

**Issue description:**

After recent changes, I'm not sure if all this examples are wrong due to strange for me singleton SceneStringNames in which I don't know to which functions are connected signals.

I just saved to different files all occurrences of signals(adding, emitting, connecting) and then with Kdiff3 I checked signals which are unavailable in others files.

Godot should have an automated scripts, which should check unused or used but not added signals(of course not always is this possible). 

**Signals which are emitted/connected but not declared(by ADD_SIGNAL)**
- [ ] - dpi_changed
- [ ] - drop_attempted
- [ ] - modal_closed (#37557)

**Signals which are added but never emitted or connected**
- [ ] - clear_request
- [ ] - copy_request
- [ ] - item_doubleclicked(is commented)
- [ ] - pause_pressed
- [ ] - item_custom_button_pressed
- [ ] - bake_finished
- [ ] - search

**Signals which are added and connected but never emitted(This may not be a bug)**
- [ ] - autoload_changed
- [ ] - group_edited
- [ ] - item_group_status_changed
- [ ] - item_lock_status_changed
- [ ] - multiple_properties_changed
- [ ] - node_added
- [ ] - node_removed
- [ ] - preview_invalidated
- [ ] - property_edited
- [ ] - removed_from_graph

**Comment by qarmin** [comment]
I created small program in Rust which search for unused signals - https://github.com/qarmin/godot_signal_checker
With it help I found a lot of possible unused signals
Linux binaries - https://github.com/qarmin/godot_signal_checker/releases/download/0.10/godot_unusable_signals
Usage
`godot_unusable_signals path_to_godot_repository`



I checked commit 0819657c3ba9de3328a18b52de1cf3c0b13f2d13

```
Signal dpi_changed is emitted but never added or connected
Signal drop_attempted is emitted but never added or connected

Signal screen_exited is emitted and added but never connected
Signal sleeping_state_changed is emitted and added but never connected
Signal interface_removed is emitted and added but never connected
Signal scene_closed is emitted and added but never connected
Signal scroll_started is emitted and added but never connected
Signal continued is emitted and added but never connected
Signal variant_field_changed is emitted and added but never connected
Signal camera_feed_removed is emitted and added but never connected
Signal frame_changed is emitted and added but never connected
Signal files_moved is emitted and added but never connected
Signal body_entered is emitted and added but never connected
Signal joy_connection_changed is emitted and added but never connected
Signal meta_hover_started is emitted and added but never connected
Signal animation_step_changed is emitted and added but never connected
Signal navigation_mesh_changed is emitted and added but never connected
Signal tab_selected is emitted and added but never connected
Signal editor_script_changed is emitted and added but never connected
Signal ramp_changed is emitted and added but never connected
Signal hide is emitted and added but never connected
Signal on_request_permissions_result is emitted and added but never connected
Signal peer_packet is emitted and added but never connected
Signal target_reached is emitted and added but never connected
Signal path_changed is emitted and added but never connected
Signal body_exited is emitted and added but never connected
Signal viewport_exited is emitted and added but never connected
Signal mesh_updated is emitted and added but never connected
Signal tracker_added is emitted and added but never connected
Signal physics_frame is emitted and added but never connected
Signal velocity_computed is emitted and added but never connected
Signal clear_selection is emitted and added but never connected
Signal released is emitted and added but never connected
Signal custom_nodes_updated is emitted and added but never connected
Signal camera_entered is emitted and added but never connected
Signal keying_changed is emitted and added but never connected
Signal viewport_entered is emitted and added but never connected
Signal text_change_rejected is emitted and added but never connected
Signal texture_changed is emitted and added but never connected
Signal ice_candidate_created is emitted and added but never connected
Signal input_event is emitted and added but never connected
Signal camera_feed_added is emitted and added but never connected
Signal tab_clicked is emitted and added but never connected
Signal resource_edit_request is emitted and added but never connected
Signal animation_changed is emitted and added but never connected
Signal transform_key_request is emitted and added but never connected
Signal node_unselected is emitted and added but never connected
Signal scene_changed is emitted and added but never connected
Signal area_entered is emitted and added but never connected
Signal data_channel_received is emitted and added but never connected
Signal tracks_changed is emitted and added but never connected
Signal area_shape_exited is emitted and added but never connected
Signal button_up is emitted and added but never connected
Signal item_focused is emitted and added but never connected
Signal connection_error is emitted and added but never connected
Signal preset_removed is emitted and added but never connected
Signal area_exited is emitted and added but never connected
Signal interface_added is emitted and added but never connected
Signal client_close_request is emitted and added but never connected
Signal scroll_ended is emitted and added but never connected
Signal button_release is emitted and added but never connected
Signal connection_established is emitted and added but never connected
Signal item_rmb_edited is emitted and added but never connected
Signal main_screen_changed is emitted and added but never connected
Signal body_shape_exited is emitted and added but never connected
Signal area_shape_entered is emitted and added but never connected
Signal folder_moved is emitted and added but never connected
Signal animation_finished is emitted and added but never connected
Signal tween_all_completed is emitted and added but never connected
Signal connection_closed is emitted and added but never connected
Signal camera_exited is emitted and added but never connected
Signal broadcast is emitted and added but never connected
Signal data_received is emitted and added but never connected
Signal custom_popup_edited is emitted and added but never connected
Signal animation_started is emitted and added but never connected
Signal session_description_created is emitted and added but never connected
Signal frame_post_draw is emitted and added but never connected
Signal tween_completed is emitted and added but never connected
Signal meta_hover_ended is emitted and added but never connected
Signal script_close is emitted and added but never connected
Signal body_shape_entered is emitted and added but never connected
Signal ready is emitted and added but never connected
Signal tween_started is emitted and added but never connected
Signal version_changed is emitted and added but never connected
Signal tween_step is emitted and added but never connected
Signal tree_entered is emitted and added but never connected
Signal screen_entered is emitted and added but never connected
Signal network_peer_packet is emitted and added but never connected
Signal preset_added is emitted and added but never connected
Signal completed is emitted and added but never connected
Signal navigation_finished is emitted and added but never connected
Signal server_close_request is emitted and added but never connected
Signal column_title_pressed is emitted and added but never connected
Signal tracker_removed is emitted and added but never connected

Signal clear_request is added but never emitted or connected
Signal item_lock_status_changed is added but never emitted or connected
Signal item_group_status_changed is added but never emitted or connected
Signal item_custom_button_pressed is added but never emitted or connected
Signal bake_finished is added but never emitted or connected
Signal copy_request is added but never emitted or connected
Signal search is added but never emitted or connected
Signal pause_pressed is added but never emitted or connected

Signal inputmap_changed is added and connected but never emitted
Signal multiple_properties_changed is added and connected but never emitted
Signal removed_from_graph is added and connected but never emitted
Signal export_presets_updated is added and connected but never emitted
Signal preview_invalidated is added and connected but never emitted
Signal group_edited is added and connected but never emitted
Signal localization_changed is added and connected but never emitted
Signal node_added is added and connected but never emitted
Signal autoload_changed is added and connected but never emitted
Signal property_edited is added and connected but never emitted
Signal node_removed is added and connected but never emitted
```

**Comment by DanielKriz** [comment]
I did the python rewrite of the godot_signal_checker script, https://github.com/DanielKriz/godot_signal_checker. But I don't know if it is still relevant. It has been tested towards the origin on the newest version of godot.

**Comment by akien-mga** [comment]
> Signals which are added and connected but never emitted

This category is wrong, all these are emitted via `add_do_method(..., "emit_signal", ...)` or `call_deferred("emit_signal", ...)`.
Sometimes via a String or StringName member variable to avoid repeating the string.

**Comment by akien-mga** [comment]
@DanielKriz I tried your script, it's helpful but it would be great if it could do this:
- Include the name of the class (or at least C++ file) where the signal was found
- Improve the checks as I see quite some false positives, possibly due to changes in the code since this was first authored in 2020 then ported (e.g. it doesn't seem to take `SNAME()` into account). Plus the points I raised above (not all easy to solve via regex, but some are).

**Comment by DanielKriz** [comment]
I am going to try to look into in after exams. It would be great if the script would be helpful in some way.
