### ISSUE TITLE
[TRACKER] RichTextLabel issues

### ISSUE THREAD

**Issue by HaSa1002** [godotengine/godot#39144]
# Rich Text Label Related Issues
 - [ ] #39101 RichTextLabel scrolling on android requires both "emulate touch from mouse" and "emulate mouse from touch" project settings [MRP](https://github.com/godotengine/godot/files/4691433/ScrollTest.zip)
 - [ ] #38846 [center] and [right] bbcode align tags in RichTextLabel causes text to overlap itself [MRP](https://github.com/godotengine/godot/files/4648142/RichTextLabel.Overlap.Bug.zip)
 - [ ] #38284 Deleting the text of a RichTextLabel by changing the size of its Custom Effects array within the editor [MRP](https://github.com/godotengine/godot/files/4543818/CustomEffects.zip) (**PR: #38383** Preserve RichTextLabel's text while modyfing Custom Effects)
 - [ ] #38169 RichTextLabel's append_bbcode stops animated rich text effects [MRP](https://github.com/godotengine/godot/files/4526781/RTLEffectsDemo.zip)
 - [ ] #38058 Infinite loop in rich_text_label.cpp
 - [ ] #36711 Text problem Bb Code Enabled / disabled [MRP](https://github.com/godotengine/godot/files/4272297/textTest.zip)
 - [ ] #36381 Some RichTextLabel getter methods only return a correct value on the next frame [MRP1](https://github.com/godotengine/godot/files/4482913/LabelBug.zip) [MRP2](https://github.com/godotengine/godot/files/4594302/RichTextLabel.zip)
 - [ ] #36134 scroll_to_line does not work while scroll active is disabled (**PR: #36366** RichTextLabel: allow 'scroll_to_line' when scroll_active is 'false')
 - [ ] #35961 Outlines go around shadows on (non-RichText) Labels [MRP](https://github.com/godotengine/godot/files/4167682/outline_text_bug.zip)
 - [ ] #35553 RichTextLabel's text is not copied on duplication (**PR: #36037** Check if bbcode is enable and filled before parsing and overwrite text property )
 - [ ] #35368 RichTextLabel can't clear bbcode text nor empty string
 - [ ] #35045 RichTextLabel Forced focus_mode when selection_enabled is active
 - [ ] #35040 RichTextLabel: Wrong meta link detection when used inside a fill tag [MRP](https://github.com/godotengine/godot/files/4050313/RichTextLabelTest.zip)
 - [ ] #34775 "visible_characters" property of Label and RichTextLabel behave differently; discrepancy between whether they acknowledge spaces or not [MRP](https://github.com/godotengine/godot/files/4018364/visible-characters-bug.zip)
 - [ ] #34308 RichTextLabel's [center] and [right] are still broken
 - [ ] #34130 RichTextLabel: BBCode [color] tags break DynamicFont extra Char spacing [MRP](https://github.com/godotengine/godot/files/3929689/DemoRTLDynamicFontCharSpacing.zip)
 - [ ] #34050 RichTextLabel doesn't translate [MRP](https://github.com/godotengine/godot/files/3908641/RichTextLabelLocalization.zip)
 - [ ] #32779 Underline in u and url tags in RichTextLabel don´t cover extra spacing while fill tag is enabled
 - [ ] #32753 url, b, u and i tags in RichTextLabel don´t respect the margin
 - [ ] #31211 Richtextlabel and Label shadow colors are not absolute [MRP](https://github.com/godotengine/godot/files/3483040/fonts.zip)
 - [ ] #31089 RichTextLabel - BBcode separates words for purpose of text-wrapping [MRP](https://github.com/godotengine/godot/files/3465735/Text.Reveal.Bug.zip)
 - [ ] #29813 RichTextLabel + tag [table] = all bags [MRP](https://github.com/godotengine/godot/files/3293565/Demo.zip)
 - [ ] #27896 Spaces are counted in RichTextLabel but not Label when using `get_total_character_count()` (**PR: #37969** Update label's character count to include space count)
 - [ ] #24305 RichTextLabel auto-inserts newlines when changing text alignment
 - [ ] #24027 GUI editor issue while code editing and do Ctrl + S [MRP](https://github.com/godotengine/godot/files/2623078/Tree.bug3.zip)
 - [ ] #23983 BBcode doesn't work well if the markers are closed in reverse order [MRP](https://github.com/godotengine/godot/files/2614732/Test.zip)
 - [ ] #23233 RichTextLabel clipping ignores rotation
 - [ ] #22580 RichTextLabel width changes on changing the window size [MRP](https://github.com/godotengine/godot/files/2432762/FontTest.zip)
 - [ ] #21488 RichTextLabel bbcode support evaluation
 - [ ] #21482 RichTextLabel auto-wrapping on chinese
 - [ ] #21285 RichTextLabel lists support
 - [ ] #18722 RichText: get_visible_line_count() returns wrong value
 - [ ] #18413 RichTextLabel bbcode_text doesn't reflect the actual text data
 - [ ] #18260 RichTextLabel doesn't set its size from the text bbox; uses 0×0 [MRP](https://github.com/godotengine/godot/files/1971235/richtextlabel-test.zip)
 - [ ] #17815 RichTextLabel::_process_line error makes Godot unresponsive during One-Click Deploy
 - [ ] #12884 RichTextLabel's bbcode_text property is not fully updated during _ready
 - [ ] #12882 RichTextLabel's bbcode_text property is not tag-stack-aware
 - [ ] #12881 RichTextLabel tag stack overwritten by bbcode_text manipulation
 - [ ] #10924 RichTextLabel does not perform well 'out of the box'
 - [ ] #5633 RichTextLabel: There's no option to VAlign text
 - [ ] #5632 RichTextLabel: Distance Field font gets rendered blurred [MRP](https://github.com/godotengine/godot/files/356222/gd-richtextlabel.tar.gz)
 - [ ] #5557 Ability to change font size in RichTextLabel without requiring separate font resources when using DynamicFont (**PR: #29762** Add ability to specify font size for RichTextLabel)

## Related to Rich Text Label Bugs
 - [ ] #26392 Can't reduce height of output window in IDE

**Comment by dalexeev** [comment]
Add #37720, please.

**Comment by Eoin-ONeill-Yokai** [comment]
>  #38169 RichTextLabel's append_bbcode stops animated rich text effects MRP

**Comment by HaSa1002** [comment]
Answering here for everybody else: (I already answered in #39248)
> When I find some time, I will solve this. I can't imagine it being too hard.
> Since you are currently refactoring the code, should I participate in that branch? Or as a separate MR?

I would wait with it, until the new structure is finalized, and work on top of it. We might integrate some bugfixes into the refractoring, depending on how the final design will be. The point I see in favor of adding bugfixes in this state is, that sometimes those will lead to a different and perhaps better design.

**Comment by Gerarama** [comment]
I only want #18260 To be fixed so i can optimize my script.
I hope someone give some time to it.

**Comment by Schweini07** [comment]
#38169 should be fixed trough #39485

**Comment by theoway** [comment]
Also mention this PR  #40217 . It fixes #18722

**Comment by theoway** [comment]
Mention this PR as well #40892 . It fixes #40207 .

**Comment by Janglee123** [comment]
One small feature request to add background color tag for BBcode. It will be really useful and have many use-cases. :)

**Comment by Calinou** [comment]
@Janglee123 Support for highlighting (background color) and redacting (overlay color) is implemented by https://github.com/godotengine/godot/pull/35608.

**Comment by Janglee123** [comment]
Also, Add this under BBcode issues #41474.

**Comment by theoway** [comment]
Add this issue #41963

**Comment by Calinou** [comment]
@theoway Done.

**Comment by theoway** [comment]
Add this as well #42656

**Comment by Calinou** [comment]
@theoway Done.

**Comment by lesleyrs** [comment]
With text to speech being added to Godot, is there any way to scroll a richtextlabel alongside the highlighted text?

I don't think it knows which line it's on, only which part has been spoken and what hasn't yet been.

Everytime I try to scroll manually it resets scroll when something becomes highlighted which is annoying, tts demo doesn't include it at all and just lets it cut off.

Also tts highlighting breaks if you press interrupt while it's already speaking and highlights everything. Not sure if this is something that can be worked around with gdscript or if it's something Godot needs to change?

**Comment by golddotasksquestions** [comment]
`[/indent] `not working: https://github.com/godotengine/godot/issues/71180

**Comment by nhold** [comment]
I'm not sure if this is already covered in the issues or is considered intentional?

<img width="1057" height="324" alt="Image" src="https://github.com/user-attachments/assets/b9561805-b831-4924-a875-7b4df34859bd" />
