### ISSUE TITLE
[TRACKER] C++ modules related issues

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#39196]
**Godot version:**
3.2, 4.0

**Issue description:**
There are some existing issues related to module dependencies which may cause run-time and compile-time errors, or need better user-friendly interface to ensure that certain modules cannot be disabled, or whether the usage of modules may reveal hidden built-in bugs (which can be either workaround on the module level or fixed on the core level, so these are not necessarily the responsibility of module authors, but which nonetheless worth to link).

## Bugs

- [ ] Crash on startup with `gdnavigation` module disabled #36091
- [ ] HeightMapShape error with disabled Bullet module on project startup #32217
- [ ] CylinderShape GodotPhysics error with disabled Bullet module on project startup #32216
- [ ] New Lightmapper denoising library doesn't support MSVC 14.1 (visual studio 2017) #39186
- [ ] Extra suffix is not appended at the end of a binary name with `mono` module enabled #37301
- [ ] Custom C++ module and XCode dSYM fail #37234
- [ ] server: pure virtual method called with --gdnative-generate-json-api #36582
- [ ] Oculus VR Module causes white screen on Windows 10 #35788
- [ ] If an error happens during ClassDB binding, the Mono module crashes the engine #35740
- [ ] Cannot build module with a reference to an int #33659
- [ ] Array overflow in svg module #33641
- [ ] Websockets: Restarting server project causes rpcp error spam that hangs the process (clients cannot connect). #33336
- [ ] Websocket server crashes when client disconnects (50% of the time). #33279
- [ ] Disabled modules shouldn't call pkg-config if they are set to be non-builtin #32265
- [ ] Can't compile Godot with asan, lsan, ubsan and disabled vorbis #31123
- [ ] Build error on FreeBSD related to libvpx #30333
- [ ] BMP loader fails to import images #30629
- [ ] Godot doesn´t compile for win x86 #28949
- [ ] Can't compile Godot with module_freetype_enabled=false #28650
- [ ] Editor crashes with custom C++ DLL module built under MSVC #25448
- [ ] webm module doesn't compile for iOS arm64 #13272

## Documentation

- [ ] Building the summator module from docs as shared module results in error #15675
- [ ] Having Trouble Compiling a module .dll #11766
- [ ] Module Question: How to write a module that replaces a core piece of the engine? #9949

## Proposals

Some issues remain in Limbo due to indecision regarding the philosophical principles of module development (what's deemed as a module now should be core, for instance see attempted fixes #32272), so it may not worth fixing some of the bugs at the moment (raising awareness for contributors).

- Godot's C++ modules should be self-contained godotengine/godot-proposals#569.

**Comment by madmiraal** [comment]
I would add #38759.

**Comment by Xrayez** [comment]
Created [a script to generate a random modules configuration](https://gist.github.com/Xrayez/c900ef441a538ba86ccb6186a6042c60) to "fuzzy test" compiling Godot that way.

**Comment by Anutrix** [comment]
#28949 closed.

**Comment by jxo** [comment]
@Xrayez modules may should be designed with dynamic loading, modules should be attached with dependency infos. Modules can be loaded or unloaded at runtime？More complicated but better to extend godot by user.

**Comment by Xrayez** [comment]
@jxo what you describe is more or less handled by GDNative. But there are certainly usability/portability/compatibility issues with using it. For this, you can refer to [proposals regarding GDNative](https://github.com/godotengine/godot-proposals/issues?q=is%3Aopen+is%3Aissue+label%3Atopic%3Agdnative).

You can also refer to godotengine/godot-proposals#565 for comparison between modules and GDNative approaches, and how they solve different use cases.

**Comment by Calinou** [comment]
@JXO See also [What is GDNative?](https://docs.godotengine.org/en/latest/tutorials/scripting/gdnative/what_is_gdnative.html) in the documentation.
