### ISSUE TITLE
[TRACKER] Ray casting related issues

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#39876]
**Godot version:**
3.2, 4.0+

**Issue description:**
I've been seeing various raycast issues popping up here recently, some of them share a lot of similarities so it's worth to track and potentially discuss those issues in a holistic way, and perhaps pin-point some duplicates.

- [ ] #39859 RayCast2D does not collide with CircleShape2D in CollisionShape2D, but does work with RectangleShape2D.
- [ ] #38873 RayCast2D and CollisionPolygon2D collisions are unreliable.
- [ ] #38343 Inconsistent RayCast2D collision results for different shapes.
- [ ] #37985 RayCast.get_collider_shape() doesn't actually return Shape ID.
- [ ] #37736 RayCast2D behaves erratically if a lot of exceptions are added.
- [ ] #36259 RayCast2D will not collide with TileMap unless it overlaps with Area2D(Parent).
- [ ] #35845 intersect_ray() result normal can be inverted or length 0.
- [ ] #35344 Tilemap world_to_map() does not get the correct tile in combination with Raycast2D.
- [ ] #31637 Why raycasts are disabled by default?
- [ ] #28032 Raycasting a BoxShape hints round edges/artifacts.
- [ ] #27282 PhysicsDirectSpaceState intersect_ray exclude does not work with GridMaps.
- [ ] #22891 Raycast2D.add_exception() not working with TileMap node.
- [ ] #19793 Raycast3D is very hard to see in editor.

**Comment by Anutrix** [comment]
#31637 can be marked fixed in this tracker now.

**Comment by Flarkk** [comment]
May this one be tracked here : « [Hardcoded maximum ray distance when Viewport processes 3d object picking #49735](https://github.com/godotengine/godot/issues/49735) » ?
