### ISSUE TITLE
[TRACKER] Indentation, line breaks and GDScript

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#40488]
**Godot version:**
3.2, 4.0

**Issue description:**
Anything related to indents and line breaks in GDScript.

## Proposals
- [ ] godotengine/godot-proposals#987 Highlight the error line in the script editor minimap
- [ ] godotengine/godot-proposals#1015 Line index color of empty lines should be white
- [ ] godotengine/godot-proposals#1209 Allow second line brackets

## Issues
- [ ] #15690 Folds don't work with non-indented content
- [ ] #20418 Blank/Comment lines at the beginning are considered "unsafe"
- [ ] #23667 Safe lines become unsafe when organized in multiple lines
- [ ] #33089 GDScript: Blank/comment script lines use up CPU cycles inside for loop
- [ ] #33687 Commenting multi-line code may lead to unnecessary warning
- [ ] #35007 Indentation errors loading space indented project into tab indented editor
- [ ] #35415 Parse error in multiline attribute expression
- [ ] #35416 Parse error in multiline dict with equal sign
- [ ] #35417 Parse error in multiline subscription expression
- [ ] #35975 GDScript parser reports named enum as having the line number after the closing brace
- [ ] #35994 "Auto brace complete" cause tokenizer error with strings as comments
- [ ] #39460 Automatic warning insertion ignores line continuation.

## PRs
- [ ] #35597 remove multiline indexing error
- [ ] #35976 Fix enum line number being the line after enum
- [ ] #36084 Blank/Comment lines at the beginning are considered "unsafe" #20418
- [ ] #36771 skip comments and whitespace when stepping with gdscript debugger

**Comment by Anutrix** [comment]
Any of this irrelevant in the new GDScript?

**Comment by dalexeev** [comment]
> Any of this irrelevant in the new GDScript?

No idea. @vnen?

**Comment by vnen** [comment]
I don't know. At one point I'll go through all GDScript issues to see what's fixed but right now I'm not sure.
