### ISSUE TITLE
[TRACKER] FBX Edits / Improvements

### ISSUE THREAD

**Issue by RevoluPowered** [godotengine/godot#40722]
**TODO post merge**
- [ ] (3DS Max Support)  Add geometric_translation/scaling/rotation into PivotTransform but abstract the algorithm away to prevent users being aware of it while fixing importer bugs. [more info](https://github.com/godotengine/godot/pull/39418#issuecomment-663980087)
- [ ] (FBX Locator Bones) Use bone->TARGET() from FBX to determine if this is from another skeleton and merge onto primary skeleton, deleting locator skeleton
- [x] (Materials) Implement 'global material' logger so we can dump all known FBX Material properties into a single file, with examples of the data. The point of this is so we know ALL formats of materials for FBX.
- [x] (SSC Improvements) Improve Inherit_Rrs (ignore parent scale to not exponentially raise values - unit testing required)
- [x] (Meshes) Optimize mesh import code to improve performance with nvidia lumberyard test model import time with debug builds.
- [ ] Enable/Disable toggle for nodes which are disabled by maya etc
- [x] Test Suite

We should ideally do each of these in a separate PR for 4.0 and 3.2

**Comment by fire** [comment]
> (Materials) Implement 'global material' logger so we can dump all known FBX Material properties into a single file, with examples of the data. The point of this is so we know ALL formats of materials for FBX.

My suggestion is that we implement something like https://github.com/godotengine/godot/pull/40474. Add support for materials dumping to meta.

**Comment by RevoluPowered** [comment]
> > (Materials) Implement 'global material' logger so we can dump all known FBX Material properties into a single file, with examples of the data. The point of this is so we know ALL formats of materials for FBX.
> 
> My suggestion is that we implement something like #40474. Add support for materials dumping to meta.
> 
> Edited:
> 
> Dumping it to a debug file is sketchy because it'll probably be json. Json isn't even a resource. Ask me if I should make json a resource..
> 
> Dumping it to the log will mean log spamming.

Nah I have some ideas how to bypass this being a 'spam' log, unique instances, and examples of the data are require along with the portion of the FBX file itself.

**Comment by RevoluPowered** [comment]
Closing, let's see what is requested by users and go from there. We have stabilization to do for the beta release.
