### ISSUE TITLE
[TRACKER] Error macros with cryptic messages due to not having proper custom messages defined

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#42719]
If you stumble upon difficult-to-understand error messages (regardless of your skill level with Godot), please report them here. In your comment, make sure to state:

- Your operating system and Godot version.
- What you were doing when you got the error message. *Always include code samples!*
- Ideally, a minimal reproduction project that returns the error message.

**Note that this issue isn't about reporting bugs, but reporting cryptic error messages.** This issue is about improving error messages so users can figure things out by themselves more easily. If you stumble upon a bug, please open a dedicated issue instead of commenting in this tracker issue.

See https://github.com/godotengine/godot/issues/24199 for background.

## Issues

- [x] https://github.com/godotengine/godot/issues/42948 
- [x] https://github.com/godotengine/godot/issues/42959 (https://github.com/godotengine/godot/pull/43076)
- [x] https://github.com/godotengine/godot/issues/50382
- [ ] https://github.com/godotengine/godot/issues/42719#issuecomment-886217688
- [x] https://github.com/godotengine/godot/issues/60602
- [ ] https://github.com/godotengine/godot/issues/62712

## For contributors

Even if you're a beginner in C++, you should be able to add error macros. This is why this issue has a `junior job` label :slightly_smiling_face: 

To add error explanations to existing errors, search for their origin in the source code (by reading the automatically-generated error message), suffix the error macro with `_MSG` and add a parameter with a custom message at the end.

We recommend adding context (such as provided arguments versus expected ones) whenever possible. Some examples:

```gdscript
# Best, do this whenever possible:
"Can't listen server on port 420000. The port number must be between 1 and 65535."

# OK:
"Can't listen server on port 420000."

# Bad, this doesn't give much context:
"Can't listen server."
```

Here are some real-world examples of improving error explanations: https://github.com/godotengine/godot/pull/41352/files, https://github.com/godotengine/godot/pull/35862/files

See [Error macros](https://docs.godotengine.org/en/latest/development/cpp/common_engine_methods_and_macros.html#error-macros) in the documentation for more information.

**Comment by theoway** [comment]
Add #41493 . I've also made a PR for the same

**Comment by Anutrix** [comment]
> File.eof_reached()` causes infinite while-loop on Android when read/write permissions aren't set #42959

Any idea where the error macro call should be? Is it at https://github.com/godotengine/godot/blob/6c173e2f7ffdb972ec3754b3d78fe51bfbfb4f22/core/bind/core_bind.cpp#L1374 replaced by `ERR_FAIL_COND_V_MSG(!f, String(), "File must be opened before use. In case you are on the Android, check if the app has file read-write permission.");`.

**Comment by Calinou** [comment]
@Anutrix Maybe we should change the error message with an `#ifdef`?

**Comment by Anutrix** [comment]
What's the difference between `__ANDROID__` or `ANDROID_ENABLED`? I'm assuming one of these must be used.

**Comment by Calinou** [comment]
@Anutrix We probably want to use `ANDROID_ENABLED` as we use `<platform>_ENABLED` for other platform defines.

**Comment by FlashDaggerX** [comment]
I would just like to point out that the link at the bottom of the [error macros page](https://docs.godotengine.org/en/latest/development/cpp/common_engine_methods_and_macros.html#error-macros) in the docs is dead as of #43385

**Comment by akien-mga** [comment]
Yes, most references to `core/` files in https://docs.godotengine.org/en/latest/development/cpp/index.html will need to be updated.

**Comment by LightningAA** [comment]
Godot 3.2.3, Windows 10

![image](https://user-images.githubusercontent.com/50304111/110226734-dea9a080-7eae-11eb-9ede-ea174c28880f.png)

**Comment by LightningAA** [comment]
Godot 3.2.3, Windows 10, GLES 2

![image](https://user-images.githubusercontent.com/50304111/110226901-27158e00-7eb0-11eb-852e-dd569474a19c.png)

**Comment by Calinou** [comment]
@LightningAA "high-end platform" means GLES3. We intentionally use a generic term as there may be several high-end platforms in the future.

**Comment by LightningAA** [comment]
I think it would make a lot more sense if it said something like `GLES2 does not support type Sampler3D`.

**Comment by Calinou** [comment]
@LightningAA The new error message I added today should fit the bill :slightly_smiling_face:

**Comment by Flarkk** [comment]
Another one : https://github.com/godotengine/godot/issues/50382

**Comment by yankscally** [comment]
@Calinou 

JacobianEntrySW: Condition "mAdiag <= realt(0.0)" is true.

I'm getting hundreds of these errors per second. I'm using lots of connected RigidBodys, with (mostly) 6DOA joints. GodotPhysics mode.

I have absolutely no idea what this means. I know its something to do with joints, but no idea what. The message is too abstract to fix the issue. This clogs up memory - after 10 mins my project will crash.

Here is the entire paste from the debugger

E 0:00:00.967 JacobianEntrySW: Condition "mAdiag <= realt(0.0)" is true.
<C++ Source> ./servers/physics/joints/jacobianentrysw.h:91 @ JacobianEntrySW()

**Comment by akien-mga** [comment]
Closing as there's not much actionable anymore in this old issue, so it's misleading as a `good first issue`.

**Comment by Calinou** [comment]
Reopening, so that users can report additional cryptic error messages.

**Comment by Arecher** [comment]
Going through some recent development screenshots of errors and the like, so I'm not 100% sure what caused this. But this is a good example.

![image](https://github.com/godotengine/godot/assets/10502115/e0e2e76a-f018-463f-bb18-aa3d402501eb)

1. Upon reading I'm not sure what this error means. Probably a text_edit is trying to set the caret to a position of -1? That'd be my best guess, but that's not actually what it says.
2. What node? What location? What script tried to set this to begin with? What is the text in the lineedit? 
Even if I understand that somewhere in my code I'm setting the caret of a lineedit wrong, that doesn't mean I know which of my currently spawned 30 lineedits causes this particular issue!

_Godot 3.5_

**Comment by Arecher** [comment]
![image](https://github.com/godotengine/godot/assets/10502115/5139a633-f112-4f9c-bc92-06394f1e5ffe)

1. What's the parent node that we're performing `get_child()` on? What script/function called this?

I completely understand what's going wrong, but the error doesn't lead me to being able to fix anything in it's current state.

**Comment by Arecher** [comment]
![image](https://github.com/godotengine/godot/assets/10502115/46ebd3ab-6f89-4817-82eb-6545b3a811e8)

1. What timer? What's it called, what is it's parent node? What tried to set this invalid Time?

**Comment by Arecher** [comment]
![image](https://github.com/godotengine/godot/assets/10502115/8551ff79-db69-4ee6-a45a-4c3ec8ee62bf)
1. What image (if saved)? Where (script, function) is it being used/created?

_Haven't had this one be an issue as often, it's often fairly easy to track down, because you're unlikely to be working with multiple in-progress functions that create images. But it fits in the list nonetheless. If somewhere in your project a random condition appears that makes an image 0px in height, I'd love to know where that came from_

**Comment by Arecher** [comment]
> This same error essentially happens for `move_child()` etc

Specifically this one
![image](https://github.com/godotengine/godot/assets/10502115/8fa87c86-c37f-474c-bcee-72014637f4c8)

1. What were we trying to add? To what parent node? What is that parents path? What script/function tried to add this?

**Comment by Arecher** [comment]
![image](https://github.com/godotengine/godot/assets/10502115/863fc49b-d0f6-4f01-b582-6265854ea751)

1. What method did we attempt to call? What tried to call it? What node are we trying to call it in?

**Comment by Arecher** [comment]
![image](https://github.com/godotengine/godot/assets/10502115/fcf866e9-29f0-4a75-b80f-0b063d6ef7c8)

1. What node is this tween being started from?

**Comment by Arecher** [comment]
![image](https://github.com/godotengine/godot/assets/10502115/97f92415-8279-4e32-9bab-bbbf1396ee0e)

1. What function/node called this? What's the name/type of the node that isn't inside the tree?

One of these cases where this could apply to any node in your project, and there is absolutely 0 indication of where to even start looking.

**Comment by Arecher** [comment]
![image](https://github.com/godotengine/godot/assets/10502115/cfcaf316-b953-4e8f-af76-edb8cb13f5e2)

1. What is the path of the file we're trying to open? What's the directory this file is in?

Usually not an issue that takes long to find/fix, but it should just be part of the error message to help you track down the correct issue faster.

**Comment by Arecher** [comment]
![image](https://github.com/godotengine/godot/assets/10502115/7119c3e3-8128-4c1a-95e4-5e35357f05ce)

1. No clue what it even means. From the notes it seemed to be an issue with `add_child()` on a separate thread. Nothing here even hints at that being a potential causation.
2. Where did this originate from? What function/script/node? I understand that's probably hard to pass, because this seems a very in-engine error, but as a user that receives this, I have no clue what I'm doing wrong, what even caused this to happen, what the results are, or how to fix it.

**Comment by MYNAMEISRADU** [comment]
![image](https://github.com/godotengine/godot/assets/38227348/21595623-5b60-4a4a-bd25-6f862e28e8dd)
`servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:777 - Parameter "mesh" is null.` is the error that gets continuously thrown in my project. 
The errors get thrown in one specific scene whenever I open it or when I just switch scene and switch back to this scene, around 90ish of em each time.

I've pinpointed the error to be due to the GridMap nodes I am using, specifically the ones sitting under the NavigationRegion3D node
![image](https://github.com/godotengine/godot/assets/38227348/a1ca1330-a79c-4f5c-b182-82879447f65a)
If I remove some of the nodes the amount of errors gets reduced, and if I delete them all the errors are gone. I have other GridMap nodes outside of the NavigationRegion3D node but they don't cause any problems. Moving the GridMap nodes outside of the NavigationRegion3D node and deleting the latter does not remove the errors, either.

The amount of errors seems quite arbitrary, I tried adding 7 new tiles to the scene and it only added 4 more errors upon refresh. Deleting these tiles also causes an error each time, but only if I delete them after refreshing the scene. But it gave an error upon deleting any of them, not just 4 of them.

This is about all the testing I've done, no mesh is missing from the Mesh Library, so I have no leads on what this could mean.

**Comment by AThousandShips** [comment]
Does it still happen in 4.2.2?

**Comment by Arecher** [comment]
![image](https://github.com/godotengine/godot/assets/10502115/32e7310d-bb4c-41e3-94c5-4e9710e97b32)

1. I don't even know what this means, or what it relates to.

**Comment by Arecher** [comment]
![image](https://github.com/godotengine/godot/assets/10502115/4cc822ba-8d9b-4589-a740-a15796c91840)

1. A nice engine issue, that I have no clue where to even start looking on how to solve it.

**Comment by Arecher** [comment]
![image](https://github.com/godotengine/godot/assets/10502115/929285c8-c5b3-4e54-801f-46766323e5cd)

1. What node(path)? What was this RPC and the function it is calling? Where did the RPC originate from?

**Comment by Arecher** [comment]
![image](https://github.com/godotengine/godot/assets/10502115/b19cabf5-dc88-4e46-8388-736b51e4d253)

1. What node made this rpc? What function is being called? What script?

**Comment by Arecher** [comment]
This error is already fairly usable in comparison, but it has an issue with not being specific enough about WHY it appears. The fact that it gives the nodepath AND the RPC function name makes it super helpful already.

![image](https://github.com/godotengine/godot/assets/10502115/f59fbb88-c691-443c-a746-65b51a8eaa8e)
This error happens when the function doesn't exist on this id.

![image](https://github.com/godotengine/godot/assets/10502115/fa8436bc-c10c-4f2f-b5ca-203727c313c8)
And this error happens when the function exists, but doesn't have the 'master' keyword or the 'puppet' keyword on one of the two sides.

These two should always clearly state the exact reason that they are failing, rather than a generalization. Right now it requires looking at the functions on the client and server, and checking whether it's on the right node, the right function, whether they all have keywords. It can fail in multiple difference places with the same error, which makes this one more effort to fix than it realistically should.

'mode is 0, master is 1' means almost nothing to me. I've been working with rpcs for years now, but I still do not understand what it's trying to tell me. It always says the exact same thing, without clearly explaining where things went wrong or what the issue is. All I know is that there is an issue with the setup, probably a wrong keyword on one of the two ends. It would be extremely helpful  if this was more readable and understandable to the average user, and if the errors were segmented a little more for specific common issues.

**Comment by Arecher** [comment]
![image](https://github.com/godotengine/godot/assets/10502115/4ee0752d-f98c-4674-9bad-3f8ecac299b7)

1. In what scene? 

And since this is basically always caused by changes in an edited scene, it should probably mention this. Telling a node has just vanished is pretty scary to a new user. I believe it was also changed to move the node to the root of the scene, so it should probably mention this instead.

**Comment by Calinou** [comment]
> I don't even know what this means, or what it relates to.

Regarding this "Response header too big message.", were you using an external editor? If so, which one (and which version of their respective extension were you using)?

**Comment by Arecher** [comment]
> Regarding this "Response header too big." message, were you using an external script editor when it happened?

Nope, we only use the Godot Editor for our scripts. This error was something my co-developer had in Godot, and when I asked him if he had any clue what could be causing it, he said he had no idea. So I'm afraid I don't currently have any other info. If we ever figure it out, I'll let you know.

**Comment by Arecher** [comment]
**Godot 4.2.2**

![image](https://github.com/user-attachments/assets/c335ee8f-5203-4572-a75a-66c2cc1117e5)

This seems to mean that you're trying to set a Node's `owner` to it's current `owner`. Basically, you're doing something inefficient. It should just say something along the lines of:

> Trying to set **Node** as the owner of **Node2**, but **Node** is already the owner of **Node2**

Although frankly, it would be better if it just:

1. Set it anyway, and didn't complain.
2. Skipped it.
3. Gave a warning instead.

I see no reason for this to throw an 'must fix' error, since setting any other variable to it's current value is allowed throughout the Engine.

**Comment by AThousandShips** [comment]
> This seems to mean that you're trying to set a Node's owner to it's current owner

No it means trying to set the owner of the node to itself, not its owner, it should have a description though saying that

**Comment by Arecher** [comment]
> No it means trying to set the owner of the node to itself

You're completely right, we read the script wrong. Setting a node as it's own `owner` was the first thing we suspected, but then we wrongly ruled that out. In that case it's definitely error worthy, but should more clearly state the mistake.

> Cannot set `Node` as it's own owner, at path: NodePath

Or something along those lines!

**Comment by AThousandShips** [comment]
Didn't add paths to the error messages in this PR, that's a major change in general to error messages so should be handled in a dedicated PR IMO

**Comment by Arecher** [comment]
> I think for adding node paths or names to errors it might be useful to instead add some helper macros or functions to make it standardized, rather than adding paths in various places, that would help clarify things and make it robust (the existing internal `get_description` method could be useful for this)

I completely agree, although such a large change will still take quite a while to be implemented, and would probably require a revisit to nearly all errors in the Engine. So for the meantime, if the information such as NodePaths or Node Names, etc are available, I would definitely add them. The manual additions can always be removed once a PR for such a standardized function/macro is implemented. 

Especially for extremely generic functions such as `move_child()`/`get_child()` this type of information can be extremely valuable, since they can crop up and be caused by one of thousands of calls.

**Comment by Arecher** [comment]
**Godot 4.2.2**
![image](https://github.com/user-attachments/assets/67b6cff5-48c8-4341-88b7-6d601a27fbea)

Unsure what caused this one, or what it's referring to.

**Comment by Arecher** [comment]
**Godot 4.2.2**
![image](https://github.com/user-attachments/assets/0739c20a-549c-4eeb-8075-a85954639bf6)

When calling `replace_by()` with as argument `get_parent()`.
_Didn't actually encounter this one in the wild, I was looking at the C++ code and doing some testing, but it's a great example of something that might be hard to figure out unless a readable message is supplied. Frankly all the `ERR_FAIL_COND_` errors could probably do with a custom message to make them easier to understand, even if additional clarification via node names/node paths/additional arguments is something that can only be added in the future._

`Failed to replace node [NodeName / at NodePath] with [NodeName / NodePath] . Replacement/new node cannot be an ancestor of the original node.`

**Comment by AThousandShips** [comment]
That's not what the error checks, the node replacing with cannot have a parent

**Comment by Arecher** [comment]
**Godot 4.2.2**
![image](https://github.com/user-attachments/assets/cfe5d38c-c72b-4777-80c6-ee81cdabe7b3)

Somewhere along the line something failed to instantiate. Would love information on what resource or scene failed, so I can make sure to reimport/restart, etc.

**Comment by AThousandShips** [comment]
Please show the surrounding errors, they might say what's going on

**Comment by akien-mga** [comment]
`Parameter "version" is null.` on shader compilation errors: https://github.com/godotengine/godot/issues/95443#issuecomment-2284851316

**Comment by Arecher** [comment]
**Godot 3.5**
![image](https://github.com/user-attachments/assets/53d078e1-82fa-48d5-b8e2-55514bcc0431)

Ran an `OS.execute()` command, probably with some wrong arguments. Hard to tell from this message!

**Comment by Arecher** [comment]
**Godot 3.5**
![image](https://github.com/user-attachments/assets/b32092f5-074e-41f3-b366-663810f9475f)

Attempted to execute Godot through the command line, while opening a specific scene. Guess the scene path was wrong, or something like that.

**Comment by robflop** [comment]
In Godot 4.3.stable (Steam), when calling `replace_by` on a node and give it a node as parameter that has a parent, you receive the error `p_node->data.parent` on its own (+ stacktrace), rather than a plain english error text or the like.

https://github.com/godotengine/godot/blob/7610409b8a14b8499763efa76578795c755a846d/scene/main/node.cpp#L2414

![2024-09-05_19-49-11](https://github.com/user-attachments/assets/e0b704eb-c665-4720-910f-df3dae3a99a6)

**Comment by Arecher** [comment]
**Godot 3.5**
![image](https://github.com/user-attachments/assets/0c9d0a30-60a0-4e02-9e62-10ccc68ec1e6)

The `Object was deleted while awaiting a callback` message should really be a warning or error, and could use more information on what the 'object' and the 'callback' are/were. Right now the only way to figure out what caused this is by looking at every `Container` in the entire project.

**Comment by Calinou** [comment]
> The Object was deleted while awaiting a callback message should really be a warning or error, and could use more information on what the 'object' and the 'callback' are/were. Right now the only way to figure out what caused this is by looking at every Container in the entire project.

The formatting for that message was changed by design to avoid infinite recursion: https://github.com/godotengine/godot/pull/89490

We could manually recreate the error message formatting specifically for it, but it might look a bit odd.

**Comment by SpockBauru** [comment]
Got this while messing with visibility range (begin/end margin and fade) of several objects scattered across the map:
```
E 0:00:11:0729   texture_create: Too many mipmaps requested for texture format and dimensions (5), maximum allowed: (4).
  <C++ Error>    Condition "required_mipmaps < format.mipmaps" is true. Returning: RID()
  <C++ Source>   servers/rendering/rendering_device.cpp:712 @ texture_create()
```

![image](https://github.com/user-attachments/assets/97fb7d30-20ab-4412-a815-3c7aa229b3a4)

Which texture? The name would help greatly. 
If possible, the faulty mesh and world position would also help, but just the name of the texture would help by a lot.

**Comment by AThousandShips** [comment]
This is a known limitation, the rendering server doesn't know the texture file or anything else like that (nor is it guaranteed to even be known), see:
* https://github.com/godotengine/godot-proposals/discussions/10190

**Comment by nan0m** [comment]
```
  ERROR: Can't save resource to empty path. Provide non-empty path or a Resource with non-empty resource_path
```
This appears when saving a very large scene (open world). It would be very helpful to know which resource is the problematic one.

**Comment by Wilker-uwu** [comment]
![A screenshot of an example code using a typed dictionary where classes are used as keys.](https://github.com/user-attachments/assets/b63e217e-ec25-4f25-9a15-6f61e6991b53)
![A screenshot of an interpreter error saying: `Error at (4, 5): Cannot have a key of type "Player" in a dictionary of type "Dictionary[Player, PackedScene]".](https://github.com/user-attachments/assets/6fc66aad-cd6b-4fb8-965f-8b4970d58028)

```gdscript
class_name MyClass extends RefCounted

static var: Dictionary[MyClass, int] = {
  MyClass: 1
}
```

in gd4.4: typed dictionaries using superclasses have confusing messages when inherited classes are used as keys.

i did it under the assumption that it would take the static instance as a key.

**Comment by lupuchard** [comment]
System info: Godot v4.4.rc1 - Linux Mint 22.1 (Xia) on X11 - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 6800 XT (RADV NAVI21) - AMD Ryzen 5 3600 6-Core Processor (12 threads)

![Image](https://github.com/user-attachments/assets/96a50897-874f-433f-a008-4b2d579fcdad)
The `/Pillar`s are MeshInstance3Ds inside a packed scene. I'm definitely not calling `get_node("../../../../../../../..")` in my own code, so I've no idea what the error means in this context, or what caused it, but nothing seems to be broken in-game.

**Comment by snowflower** [comment]
> System info: Godot v4.4.rc1 - Linux Mint 22.1 (Xia) on X11 - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 6800 XT (RADV NAVI21) - AMD Ryzen 5 3600 6-Core Processor (12 threads)
> 
> ![Image](https://github.com/user-attachments/assets/96a50897-874f-433f-a008-4b2d579fcdad) ![Image](https://github.com/user-attachments/assets/ce7e9a41-530d-4be0-8349-e0805b2caa54) The `/Pillar`s are MeshInstance3Ds inside a packed scene. I'm definitely not calling `get_node("../../../../../../../..")` in my own code, so I've no idea what the error means in this context, or what caused it, but nothing seems to be broken in-game.
> 
> Edit: Actually it might be this issue - [#102804](https://github.com/godotengine/godot/issues/102804)


I get this as well:
Godot v4.5.dev3 - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 32.0.15.6094) - AMD Ryzen 9 3950X 16-Core Processor (32 threads)

This happens constantly while trying to make packed sub-scenes (like a prefab building) where I will compose an object in the main game scene or a level sandbox, and then copy->paste those objects into a new fresh scene.
The geometry is just static meshes, but the editor seems to be constantly trying to assign a skeleton path reference like this:

![Image](https://github.com/user-attachments/assets/2d3e5659-9cb9-4c2a-8a51-40387b7d679e)

In my example and case the 'Node3D2' is the empty Node3D I made as a parent node to place all the meshes under for organizing the object, before I copy + paste to move it to another scene.

In the new scene, the node is either renamed or I copy all the children of it, so it doesn't have this reference in my new packed scene, and then drag that into another scene (game level/sandbox) I will get a ton of error spam like this:

![Image](https://github.com/user-attachments/assets/87363581-a7c8-4160-b1a1-4e840f546875)


These are randomly parented meshInstance3D's that are static world meshes, they have no skin, the skeleton node that getting set feels extremely random, and its something that can propagate through building a level with copy+paste easily.
I can clear the skeleton field in the offending nodes to nothing and fix the error, but this field getting set in the first place with static meshes just parented to Node3Ds or each other feels like a bug.
I feel like I need to write a tool script to recursively clear out all skeleton paths on static level geometry.

**Comment by Sithoid** [comment]
4.6.2, Wayland, 3D game with Forward+. I sometimes get this error spam during launch, or even in the editor when I'm messing with shaders. Can't really put my finger on the conditions; nothing else seems to be out of the ordinary (maybe this happens during crashes due to other errors?) In any case, this is as cryptic as they get

<img width="1068" height="208" alt="Image" src="https://github.com/user-attachments/assets/bf486ec1-6069-4e08-abf5-5b9c9f70ecb9" />

**Comment by d-bucur** [comment]
Getting this error that crashes the game when I change scenes. This looks like an engine error.
```
ERROR: Parameter "get_viewport()" is null.
   at: _notification (scene/main/node.cpp:193)
double free or corruption (!prev)
```

I'm not using `get_viewport()` anywhere near that call site. Here is my code for changing the scene. Notice that the calls are deferred to avoid weird behavior when calling from `_physics_process`, but the same error happens if they are not deferred

```gdscript
func main_menu():
	get_tree().change_scene_to_file.call_deferred("res://scenes/main_menu.tscn")

func change_scene(path: String, fallback_main_menu = true):
	var packed_scene = ResourceLoader.load(path)
	if packed_scene == null or not packed_scene is PackedScene:
		push_error("Level scene load failed: %s" % path)
		if fallback_main_menu: main_menu()
		return

	get_tree().change_scene_to_file.call_deferred(path)

```

**Comment by AegisTTN** [comment]
@d-bucur Could you tell what the code that calls these functions and gives the errors is. I'm not being able to get the error to appear just with the code above

**Comment by d-bucur** [comment]
@AegisTTN It's a big project, and it only happens some times. The calling code is very simple from a `gui_input` handle. I suspect this is related to a lot of context that is inside the scene when it is cleared, rather than the call site. It's hard to understand what causes it or replicate it even for me.

**Comment by Arecher** [comment]
While the message itself is clear, tracing it's origin is more work than it should be:

Godot 4.7.stable

<img width="995" height="46" alt="Image" src="https://github.com/user-attachments/assets/11578e69-2b41-4601-b0ef-1991d5f82506" />


Firstly it should probably specify whether this is specifically talking about a **Timer** or a **SceneTreeTimer**, or whether it could be either. If it originates from a node, it should show the node name/path or scene it belongs to (it might not be in the scene tree yet, but it likely does have parents that could help specify where the error occurs). If it's a SceneTreeTimer, an indication of what script/node spawned the timer and who its owner is would work too.
