### ISSUE TITLE
Core: disabled method bindings that were not compatible with the new system

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#43311]
**Godot version:**
`master` (424cd00f8b14aa51aad82c52996740d7648ae691)

**Issue description:**
#42780 changed and greatly simplified the binding system for the core API, but some problematic methods were lost in the process, as seen in #43310.

This issue lists them so that we can evaluate if they can be changed to be bound again, or if they should be dropped fully.

- [x] `Color.from_hsv()`: "FIXME: Color is immutable, need to probably find a way to do this via constructor (#54868)
- [x] `Quat.set_axis_angle()` and `Quat.set_euler()`: "FIXME: Quat is atomic, this should be done via constructor" (#45407)
- [x] `String.erase()`: "FIXME: String needs to be immutable when binding" (#54869)
- [x] `String.humanize_size()`: "FIXME: Static function, not sure how to bind" (#46378)

The above comments come from `core/variant_call.cpp`, which is where core methods are bound.

**Comment by aaronfranke** [comment]
I think `String.erase()` should just be removed. You can already get an empty string in GDScript using `String()`.

For `Color.from_hsv()`, however we bind it, we should consider changing Color8 and ColorN to be the same way.

**Comment by akien-mga** [comment]
> I think `String.erase()` should just be removed. You can already get an empty string in GDScript using `String()`.

That's not what it does though, it's `void erase(int p_pos, int p_chars);` - it removes a substring from the string.

**Comment by theoway** [comment]
> > I think `String.erase()` should just be removed. You can already get an empty string in GDScript using `String()`.
> 
> That's not what it does though, it's `void erase(int p_pos, int p_chars);` - it removes a substring from the string.

#37918. We've had a discussion about this method as it goes against the point of `String` being immutable. We've thought of removing this method and implementing something similar to `splice()` as in Javascript, while making sure that `String` remains immutable. You can drop your suggestions on the issue mentioned above :)

**Comment by vnen** [comment]
Now that #46378 is merged, `String.humanize_size()` is bound. We can move `Color.from_hsv()` to be static too. Probably the same can be done with Quat if the constructor isn't possible.

**Comment by akien-mga** [comment]
All fixed in 1aa3c8419b2405d81d04f4fb3ac142fcd355de85.
