### ISSUE TITLE
[TRACKER] Issues with inner classes in GDScript

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4399]
Listing of issues (and if relevant, PRs) relative to inner classes in GDScript:

- [x] #1110 Can't derive constants from other constants in inner classes
- [x] #1411 const of base class not accessible
- [ ] #3387 Initialization bugs in inner classes with several (2) levels of inheritance
- [x] #3766 Can't debug inner classes with breakpoints
- [x] #4026 extends on Subclass doesn't resolve relative Paths to GDScript
- [ ] #4472 A Inner class can not access its outer class's functions
- [x] #4756 Instancing inner classes directly from 'preload()' gives errors in editor, but works.

Feel free to edit/comment to add other relevant issues.

**Comment by reduz** [comment]
#3387 is not a bug, won't be done for now

**Comment by reduz** [comment]
#4472 is also not a bug

**Comment by reduz** [comment]
well, nothing else to do here, should this be closed? nothing will be done with #3387 and #4472 in the short term

**Comment by akien-mga** [comment]
I've unticked #3387 and #4472 as they're not fixed, but yeah the tracker can be closed I guess.
