### ISSUE TITLE
Multiple visual glitches with 'PopupMenu'

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#44894]
**Godot version:**
950dedb

**Issue description:**
Here's a comparison of `PopupMenu` between the 3.2 and master versions:
![popups](https://user-images.githubusercontent.com/30739239/103484153-7eca4700-4de4-11eb-91d1-3bcb4b5930b3.png)

- [x] Items with no text nor icon get completely flattened, even if those that are checkable. Fixed by #46081.
- [x] The highlight indicator has its sides cutoff. Fixed by #44905.
- [x] The popup's width does not fit its button if bigger. Fixed by #44906.

**Comment by Calinou** [comment]
cc @EricEzaM

**Comment by EricEzaM** [comment]
> *  The highlight indicator has its sides cutoff.
This is expected since a margin container is used for the layout now. Not a bug as far as I see it.

As For the others, my pr for popup menus did not touch drawing code afaik so not sure what happened there.

**Comment by YeldhamDev** [comment]
> This is expected since a margin container is used for the layout now. Not a bug as far as I see it.

If so, then the indicator should be changed so it's not cutoff.

> As For the others, my pr for popup menus did not touch drawing code afaik so not sure what happened there.

I believe that the empty item bug is a result of the RTL changes. CC @bruvzg

**Comment by EricEzaM** [comment]
> > This is expected since a margin container is used for the layout now. Not a bug as far as I see it.
> 
> If so, then the indicator should be changed so it's not cutoff.

Ah I see what you mean now, the border radius is not displayed/cut off.
