### ISSUE TITLE
[TRACKER] Bullet Physics issues

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#45022]
Kinematic body issues:
- [ ] https://github.com/godotengine/godot/issues/18433 - 3D KinematicBody slides with move_and_collide
- [ ] https://github.com/godotengine/godot/issues/26550 - KinematicBody slides on collision box, but doesn't on a plane
- [ ] https://github.com/godotengine/godot/issues/28717 - Seemingly inaccurate kinematic collision remainders in Bullet physics but not GodotPhysics
- [ ] https://github.com/godotengine/godot/issues/32182 - move_and_slide() causes jitter when colliding with corners
- [ ] https://github.com/godotengine/godot/issues/33833 - KinematicBody3D: is_on_floor() can become false when moving against a wall
- [ ] https://github.com/godotengine/godot/issues/34081 - move_and_slide_with_snap inconsistent is_on_floor
- [ ] https://github.com/godotengine/godot/issues/34436 - KinematicBody: move_and_slide_with_snap intersection edges problem
- [ ] https://github.com/godotengine/godot/issues/34596 - Jittering against two discrete, connected walls
- [ ] https://github.com/godotengine/godot/issues/35713 - GridMap collisions broke from 3.1.2 to 3.2
- [ ] https://github.com/godotengine/godot/issues/35780 - KinematicBody jitters up and down when walking along a flat gridmap

**Comment by smix8** [comment]
#43243
Softbody is Bullet only so I guess this is also a Bullet Physics issue to track?

**Comment by pouleyKetchoupp** [comment]
@smix8 I'll probably make a specific tracker for soft bodies. For info, the plan for 4.0 is to implement them in Godot Physics as well.

**Comment by DimitriyPS** [comment]
https://github.com/godotengine/godot/issues/45182

This bug is relevant for bullet physics.

**Comment by pouleyKetchoupp** [comment]
> 
> 
> #45182
> 
> This bug is relevant for bullet physics.

This tracker is for issues that are specific to Bullet, #45333 is for issues that are relevant to both.

**Comment by pouleyKetchoupp** [comment]
For info, I've just added an extra section at the end of the tracker for changes that will be needed in the Bullet server for 4.0 compatibility, since Bullet is disabled on master at the moment.

These changes will be needed either for the a Bullet plugin or for re-enabling it as a module before 4.0 release.

**Comment by Nekuromu** [comment]
Guess since it's bullet specific, #55503 belongs here instead!

**Comment by elvisish** [comment]
Here's another: https://github.com/godotengine/godot/issues/58260

**Comment by MJacred** [comment]
bullet physics issue: [#58409](https://github.com/godotengine/godot/issues/58409)
