### ISSUE TITLE
[TRACKER] Godot Physics 2D issues

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#45334]
This tracker is for all physics issues that affect Godot Physics 2D.

Note: Issues that are reported on both 2D and 3D are listed here and in #45333

Rigid body
- [ ] https://github.com/godotengine/godot/issues/2092 - Pile of RigidBody2Ds results in overlapping and shaking
- [ ] https://github.com/godotengine/godot/issues/10959 - RigidBody2D ignores set_position when switching between MODE_RIGID and MODE_STATIC/KINEMATIC
- [ ] https://github.com/godotengine/godot/issues/11925 - Inconsistent execution order of _integrate_forces
- [ ] https://github.com/godotengine/godot/issues/16414 - RigidBody2D#test_motion behaving weird
- [ ] https://github.com/godotengine/godot/issues/20105 - Collisions of RigidBody2D are offsetted when moving
- [ ] https://github.com/godotengine/godot/issues/25186 - 2D PhysicsMaterial bounce > 0, constantly agitated/vibrating when they should be at rest
- [ ] https://github.com/godotengine/godot/issues/27652 - Rigid Bodies passing through walls / objects
- [ ] https://github.com/godotengine/godot/issues/28438 - RigidBody2D bounces when passing on top of two perfectly aligned StaticBody2Ds
- [ ] https://github.com/godotengine/godot/issues/29303 - Rigid bodies using inertia become unstable
- [ ] https://github.com/godotengine/godot/issues/29639 - Colliding objects (RigidBody2d) gain energy
- [ ] https://github.com/godotengine/godot/issues/29888 - can't use Rigigbody2D's apply_impulse and apply_torque_impulse when in _ready() function
- [ ] https://github.com/godotengine/godot/issues/32158 - Bumpy issue when dealing with moving platforms and Animation Player
- [ ] https://github.com/godotengine/godot/issues/34215 - 2D Physics Collision is 'Squishy'
- [ ] https://github.com/godotengine/godot/issues/35514 - RigidBody2D rotates on collision in 3.2, works fine in 3.1
- [ ] https://github.com/godotengine/godot/issues/36294 - RigidBody2D tunnels CollisionShape2D and bounces back with even greater momentum
- [ ] https://github.com/godotengine/godot/issues/37427 - KinematicBody2D pushes RigidBody2D through the ground when standing on them
- [ ] https://github.com/godotengine/godot/issues/38646 - RigidBody2D does not clear forces at end of integration, RigidBody does
- [ ] https://github.com/godotengine/godot/issues/38780 - Physics2D weird CollisionPolygon2D interaction with 3 consecutive points on the same line
- [ ] https://github.com/godotengine/godot/issues/40495 - RigidBody2D and moving platforms
- [ ] https://github.com/godotengine/godot/issues/41024 - RigidBody2D cannot rotate after CollisionShape2D is disabled
- [ ] https://github.com/godotengine/godot/issues/45331 - Bounce property of RigidBody2D physics material is ignored after saving scene

Kinematic body
- [ ] https://github.com/godotengine/godot/issues/8757 - KinematicBody2D.move result in weird movement between KinematicBody2D
- [ ] https://github.com/godotengine/godot/issues/15243 - KinematicBody/2D uses any combination of layer-mask for move_* collision detection
- [ ] https://github.com/godotengine/godot/issues/21560 - KinematicBody2D using move_and_collide makes other colliding KinematicBody2D move
- [ ] https://github.com/godotengine/godot/issues/23140 - Kinematic body does not move when exactly in between two static bodies
- [ ] https://github.com/godotengine/godot/issues/24050 - Inconsistent floor collision
- [ ] https://github.com/godotengine/godot/issues/24335 - Kinematic bodies having collision normal problems against other Kinematic bodies
- [ ] https://github.com/godotengine/godot/issues/25759 - [2D physics] Random flipping of sprite when rotated
- [ ] https://github.com/godotengine/godot/issues/27537 - Experimenting with gravity and moving platforms, head gets stuck
- [ ] https://github.com/godotengine/godot/issues/31097 - 2D KinematicBody slides down slope with move_and_slide_with_snap
- [ ] https://github.com/godotengine/godot/issues/34345 - KinematicBody2D can push other KinematicBody2D
- [ ] https://github.com/godotengine/godot/issues/34869 - KinematicBody2D Will Suddenly Launch RigidBody2D
- [ ] https://github.com/godotengine/godot/issues/35275 - Joint2D doesn't react to KinematicBody2D
- [ ] https://github.com/godotengine/godot/issues/36290 - KinematicCollision2D is overriden even though the variable isn't reassigned
- [ ] https://github.com/godotengine/godot/issues/36432 - Collision detection not always working using move_and_collide on KinematicBody2D with save_margin at 0.001
- [ ] https://github.com/godotengine/godot/issues/36500 - Player KinematicBody2D (using Rayshape2D and move_and_slide) make moving platform(using move_and_collide) drop down slowly together
- [ ] https://github.com/godotengine/godot/issues/37118 - Jitter in projects
- [ ] https://github.com/godotengine/godot/issues/37798 - KinematicBody2D passing through tile when there is one cell between parallel tiles
- [ ] https://github.com/godotengine/godot/issues/38247 - move_and_slide properties in visual script disable the collision detection
- [ ] https://github.com/godotengine/godot/issues/40526 - RigidBody2D isn't detecting every collision
- [ ] https://github.com/godotengine/godot/issues/44882 - KinematicBody2D: odd move_and_slide behaviour when exactly on tile edge
- [ ] https://github.com/godotengine/godot/issues/45004 - KinematicBody2D slides with move_and_collide
- [ ] https://github.com/godotengine/godot/issues/45259 - 2D platform physics collision jitter

One way collision
- [ ] https://github.com/godotengine/godot/issues/25313 - One-way collision shape does not work with KinematicBody2D
- [ ] https://github.com/godotengine/godot/issues/27689 - KinematicBody2D and RayCastShape2D doesn't work on One Way Collision
- [ ] https://github.com/godotengine/godot/issues/28895 - One way platforms don't have consistent collision on edge
- [ ] https://github.com/godotengine/godot/issues/38675 - CollisionPolygon2D bug with one way collision
- [ ] https://github.com/godotengine/godot/issues/42765 - move_and_slide causes unexpected slide on edge of fast moving platforms
- [ ] https://github.com/godotengine/godot/issues/42914 - Moving through one way platforms jumps KinematicBody2D by one way margins
- [ ] https://github.com/godotengine/godot/issues/42916 - KinematicBody2D doesn't collide with one way platforms on corners in certain cases
- [ ] https://github.com/godotengine/godot/issues/43229 - A KinematicBody2D can push another KinematicBody2D through a moving one-way collision platform
- [ ] https://github.com/godotengine/godot/issues/43346 - KinematicBody2D doesn't collide with group of one way collision bodies
- [ ] https://github.com/godotengine/godot/issues/43973 - Vertical collision with one way collision platform when colliding with another body to the side

Sync to physics
- [ ] https://github.com/godotengine/godot/issues/43236 - KinematicBody collision doesn't update when parent moves and Sync To Physics is enabled
- [ ] https://github.com/godotengine/godot/issues/43834 - KinematicBody2D isn't moved by RemoteTransform2D if "sync to physics" is enabled, and the RemoteTransform2D doesn't update scale or rotation

Smooth steps
- [ ] https://github.com/godotengine/godot/issues/43368 - Godot 3.2.3 move_and_slide_with_snap() doesn't function correctly at 144fps
- [ ] https://github.com/godotengine/godot/issues/43800 - 2D physics objects have delay to their positions

Collision detection
- [ ] https://github.com/godotengine/godot/issues/5734 - RigidBody and RigidBody2D ignore scaling on runtime
- [ ] https://github.com/godotengine/godot/issues/9071 - Continuous CD not working
- [ ] https://github.com/godotengine/godot/issues/12335 - Issue with flipping 2D characters (non uniform scaling)
- [ ] https://github.com/godotengine/godot/issues/19353 - ERROR: set_data: Condition ' len % 2 ' is true
- [ ] https://github.com/godotengine/godot/issues/20576 - RigidBody2D won't detect collision sometimes when colliding with 2 StaticBody2D
- [ ] https://github.com/godotengine/godot/issues/23042 - Collision signals don't work on static and rigid RigidBody2D but do work between rigid and kinematic RigidBody2D
- [ ] https://github.com/godotengine/godot/issues/24663 - Unexpected behavior when setting negative scale in KinematicBody2D
- [ ] https://github.com/godotengine/godot/issues/32138 - Incorrect bounce angle of RigidBody2D when using the Cast Ray Continuous Cd mode
- [ ] https://github.com/godotengine/godot/issues/39653 - Ray slows down before the collision
- [ ] https://github.com/godotengine/godot/issues/41685 - Rotation/Scale/Translation mixes on CollisionShapes not consistently resulting in correct collision
- [ ] https://github.com/godotengine/godot/issues/43014 - RigidBody2D sometimes reports incorrect collision normal
- [ ] https://github.com/godotengine/godot/issues/43743 - Area2D's signals *_entered and *_exited do not fire predictably during movement dependent on speed and size
- [ ] https://github.com/godotengine/godot/issues/44348 - changing collision shape dynamically in _process delays detection

Area
- [ ] https://github.com/godotengine/godot/issues/11159 - Area2D does not report input events if it is not in a collision layer
- [ ] https://github.com/godotengine/godot/issues/12215 - Physics2DServer doesn't send body info to signals
- [ ] https://github.com/godotengine/godot/issues/14578 - Changing node parent produces Area2D signal duplicates
- [ ] https://github.com/godotengine/godot/issues/17238 - Area2D doesn't detect static bodies if "Monitorable" is disabled
- [ ] https://github.com/godotengine/godot/issues/19271 - Changing Area2D shape causes resend of body_exited and body_entered for enclosed body
- [ ] https://github.com/godotengine/godot/issues/23484 - Area2D doesn't update its overlapping areas when monitorable changes in the areas it's overlapping
- [ ] https://github.com/godotengine/godot/issues/25331 - area_entered, area_exited occurs at the same time with Area2D
- [ ] https://github.com/godotengine/godot/issues/25769 - Area2D duplicate signal when changing CollisionPolygon2D Polygon property
- [ ] https://github.com/godotengine/godot/issues/27441 - Area2D monitoring and monitorable are not working according to docs
- [ ] https://github.com/godotengine/godot/issues/33766 - Changing radius of RigidBody2D's shape ignores Area2D gravity
- [ ] https://github.com/godotengine/godot/issues/34085 - Duplicate collision detection when re-instancing Area2D nodes
- [ ] https://github.com/godotengine/godot/issues/41155 - Raycast can collide with area even if monitorable property is set to false
- [ ] https://github.com/godotengine/godot/issues/41648 - Area2D signals area_entered and body_entered not firing on same frame
- [ ] https://github.com/godotengine/godot/issues/44632 - regression in Area2D monitoring which results in callbacks missing

Joints
- [ ] https://github.com/godotengine/godot/issues/5418 - Time scale affects PinJoint2D's softness
- [ ] https://github.com/godotengine/godot/issues/31711 - PinJoint2D unpins when parent node moved
- [ ] https://github.com/godotengine/godot/issues/38434 - Pin Joints throw errors when freed

Raycasting
- [ ] https://github.com/godotengine/godot/issues/22891 - Raycast2D.add_exception() not working with TileMap node	
- [ ] https://github.com/godotengine/godot/issues/35845 - intersect_ray() result normal can be inverted or length 0
- [ ] https://github.com/godotengine/godot/issues/36259 - RayCast2D will not collide with TileMap if it's fully inside tile
- [ ] https://github.com/godotengine/godot/issues/36824 - Intersect ray hit RID is different each time
- [ ] https://github.com/godotengine/godot/issues/38343 - Inconsistent RayCast2D collision results for different shapes
- [ ] https://github.com/godotengine/godot/issues/38873 - RayCast2D and CollisionPolygon2D collisions are unreliable
- [ ] https://github.com/godotengine/godot/issues/39859 - Raycast2d does not collide with CircleShape2d in CollisionShape2d, but does work with RectangleShape2d
- [ ] https://github.com/godotengine/godot/issues/44003 - Raycasts inside Tilemaps only collide at the edge

Tilemap
- [ ] https://github.com/godotengine/godot/issues/17090 - Collision exceptions don't work with TileMap node
- [ ] https://github.com/godotengine/godot/issues/24739 - Area2D reports TileMap in the signals, when collide with the tiles
- [ ] https://github.com/godotengine/godot/issues/35550 - Moving platform with tilemap does not working properly
- [ ] https://github.com/godotengine/godot/issues/38297 - Tilemap: set_cellv(map_point, -1) does not work with Ysort
- [ ] https://github.com/godotengine/godot/issues/41245 - Physics2DDirectSpaceState.insersect_point() does not exclude TileMaps passed in the exclude parameter
- [ ] https://github.com/godotengine/godot/issues/43306 - Phantom tilemap collisions breaking game

Multi-threading
- [ ] https://github.com/godotengine/godot/issues/29364 - Test_move in KinematicBody2D cause game crash
- [ ] https://github.com/godotengine/godot/issues/29369 - Crash in destructor AreaPair2DSW with Multi-Threaded physics
- [ ] https://github.com/godotengine/godot/issues/35017 - Infinite loop in Physics2DServerSW::_update_shapes with Multi-Threaded physics

Other
- [ ] https://github.com/godotengine/godot/issues/3703 - CollisionObject2D _input_event ignores pause mode
- [ ] https://github.com/godotengine/godot/issues/23051 - Undefined propagation order for clicks on overlapped CollisionShape2D
- [ ] https://github.com/godotengine/godot/issues/24334 - Physics is not deterministic when using time scale
- [ ] https://github.com/godotengine/godot/issues/26181 - Area2D mouse_entered and mouse_exited signals not called in Viewport
- [ ] https://github.com/godotengine/godot/issues/26680 - Difficult to work with Area2D/PhysicsBody2D in C# due to duplicated code in Godot Engine
- [ ] https://github.com/godotengine/godot/issues/28318 - Collider returns an Object. no access to .Name
- [ ] https://github.com/godotengine/godot/issues/28922 - Export project crashes only when exporting without "Export with debug" option
- [ ] https://github.com/godotengine/godot/issues/31016 - Inconsistent physics delta
- [ ] https://github.com/godotengine/godot/issues/35052 - CollisionObject2D nodes inside CanvasLayer with FollowViewport enabled are not affected by movement
- [ ] https://github.com/godotengine/godot/issues/36499 - Collision shapes created through CollisionObject2D APIs are not visible
- [ ] https://github.com/godotengine/godot/issues/38339 - Trying to have composite rigidbodies 2D and imprecision issues with linear velocity
- [ ] https://github.com/godotengine/godot/issues/39216 - WARNING: cleanup: ObjectDB Instances still exist! when using GetWorld2d().DirectSpaceState

Editor
- [ ] https://github.com/godotengine/godot/issues/19558 - CollisionPolygon2D with polygon point count < 3 throw issue in debug console
- [ ] https://github.com/godotengine/godot/issues/29991 - Collision layer name doesn't update in the inspector when changed
- [ ] https://github.com/godotengine/godot/issues/43887 - Creating a CollisionPolygon2D from a Sprite has an incorrect offset is done from a Sprite with Region enabled

Documentation
- [ ] https://github.com/godotengine/godot/issues/26003 - KinematicBody2D: test_move breaks when parent is offset from (0, 0)
- [ ] https://github.com/godotengine/godot/issues/30824 - Documentation is unclear on how to move a RigidBody2D in Kinematic mode
- [ ] https://github.com/godotengine/godot/issues/31564 - Area2Ds ignore CollisionShape2D.one_way_collision
- [ ] https://github.com/godotengine/godot/issues/43202 - test_motion doesn't return collision with other RigidBody2D
- [ ] https://github.com/godotengine/godot/issues/44622 - PhysicsShapeQueryParameters2D collision_layer property is actually collision_mask
- [ ] https://github.com/godotengine/godot/issues/45131 - Area2D erroneously emits body_entered signal if collision mask *and* layer are reset

4.0 Refactoring
- [ ] https://github.com/godotengine/godot/issues/12353 - Center of mass for RigidBody2D
- [ ] https://github.com/godotengine/godot/issues/25254 - Shouldn't PhysicsMaterial properties correspond to individual shapes rather than the body?
- [ ] https://github.com/godotengine/godot/issues/30029 - move_and_slide() takes in velocity, while move_and_collide() takes in position offset
