### ISSUE TITLE
[TRACKER] Godot Physics 3D issues

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#45333]
This tracker is for all physics issues that affect Godot Physics 3D.

Note 1: Issues that are reported on both 2D and 3D, or on both Bullet and Godot Physics are listed here.

Note 2: Issues related to features that are currently Bullet-only are listed here when the plan is to implement them in Godot Physics too (soft body, heightmap).

Rigid body
- [ ] https://github.com/godotengine/godot/issues/25468 - Unstable RigidBody when adding/applying forces/torque
- [ ] https://github.com/godotengine/godot/issues/36703 - apply_impulse, add_force sometimes makes the RigidBody fly away
- [ ] https://github.com/godotengine/godot/issues/36847 - Rigidbody doesn't rotate when linear movement restriction on all axis is applied
- [ ] https://github.com/godotengine/godot/issues/40486 - Setting RigidBody global_transform into the `_input` function fails
- [ ] https://github.com/godotengine/godot/issues/41404 - RigidBody box collision shape failing collision detection through convex and concave shapes when impulse is applied
- [ ] https://github.com/godotengine/godot/issues/41617 - The Rigidbody cannot rotate after set the CollisionShape disabled first and enabled later
- [ ] https://github.com/godotengine/godot/issues/43605 - Low speed RigidBody overlaps StaticBody then bounces back when collision happens even with CCD enabled and 0 bounce

Kinematic body
- [ ] https://github.com/godotengine/godot/issues/15243 - KinematicBody/2D uses any combination of layer-mask for move_* collision detection
- [ ] https://github.com/godotengine/godot/issues/18433 - 3D KinematicBody slides with move_and_collide
- [ ] https://github.com/godotengine/godot/issues/30310 - Move_and_slide_with_snap steep slops problem
- [ ] https://github.com/godotengine/godot/issues/30311 - Move_and_slide_with_snap fails to follow a moving platform if stop_on_slope is set to true
- [ ] https://github.com/godotengine/godot/issues/34098 - KinematicBody player with RayShape does not respect snap argument in move_and_slide_with_snap()
- [ ] https://github.com/godotengine/godot/issues/34663 - RayShapes in 3D sometimes causes player to vibrate in place
- [ ] https://github.com/godotengine/godot/issues/36334 - Inaccurate behaviour of 3D KinematicBody move_and_slide_with_snap on vertical moving platform
- [ ] https://github.com/godotengine/godot/issues/45060 - KinematicBody3D with move_and_slide() move bumpy/jittering on flat surface
- [ ] https://github.com/godotengine/godot/issues/45219 - KinematicBody3D with move_and_slide() does unreliable is_on_floor() detection when nearly on platform's edge

Smooth steps
- [ ] https://github.com/godotengine/godot/issues/43368 - Godot 3.2.3 move_and_slide_with_snap() doesn't function correctly at 144fps

Collision detection
- [ ] https://github.com/godotengine/godot/issues/5734 - RigidBody and RigidBody2D ignore scaling on runtime
- [ ] https://github.com/godotengine/godot/issues/5910 - 3D KinematicBody is not correctly detecting collision with PlaneShape
- [ ] https://github.com/godotengine/godot/issues/16505 - Inaccurate physics with simple bodies (RigidBodies can temporarily penetrate other PhysicsBodies)
- [ ] https://github.com/godotengine/godot/issues/26890 - Scale or Rotate RigidBody should be locked, not just alerted
- [ ] https://github.com/godotengine/godot/issues/26906 - Godot physics performance issue when colliding with a ConvexPolygonShape generated from a SphereMesh
- [ ] https://github.com/godotengine/godot/issues/30481 - KinematicBody does not collide with new position of a moved KinematicBody - can tunnel through
- [ ] https://github.com/godotengine/godot/issues/37308 - RigidBody sometimes misses reporting a contact
- [ ] https://github.com/godotengine/godot/issues/39095 - Collision detection issues - multiple collision shapes, CCD
- [ ] https://github.com/godotengine/godot/issues/41685 - Rotation/Scale/Translation mixes on CollisionShapes not consistently resulting in correct collision
- [ ] https://github.com/godotengine/godot/issues/45182 - Insufficient processing of RigidBody in the physics engine (Bullet and Godot)

Area
- [ ] https://github.com/godotengine/godot/issues/30575 - RigidBody in an Area node with gravity point increases it's speed continuously
- [ ] https://github.com/godotengine/godot/issues/35595 - area_entered and area_exited emitted multiple times while still overlapping
- [ ] https://github.com/godotengine/godot/issues/41155 - Raycast can collide with area even if monitorable property is set to false

Joints
- [ ] https://github.com/godotengine/godot/issues/31864 - Joints slide
- [ ] https://github.com/godotengine/godot/issues/33083 - Generic6DOFJoint is behaving in a weird manner when rotating around the Y axis (it's working properly for the Z axis)
- [ ] https://github.com/godotengine/godot/issues/33707 - Angular limits in Generic 6DOF Joint doesn't work
- [ ] https://github.com/godotengine/godot/issues/34398 - Physics. Joints. Motor.
- [ ] https://github.com/godotengine/godot/issues/41398 - HingeJoints stop working when the scene containing them is reparented

Raycasting
- [ ] https://github.com/godotengine/godot/issues/27282 - PhysicsDirectSpaceState intersect_ray exclude does not work with GridMaps
- [ ] https://github.com/godotengine/godot/issues/36824 - Intersect ray hit RID is different each time

Gridmap
- [ ] https://github.com/godotengine/godot/issues/3284 - Collision section of GridMap is outdated when compared to TileMap
- [ ] https://github.com/godotengine/godot/issues/28801 - Octant physics negatively impact gridmap performance
- [ ] https://github.com/godotengine/godot/issues/33648 - Dynamic Gridmap unloading causes physics engine errors and FPS issues
- [ ] https://github.com/godotengine/godot/issues/43712 - GridMap reports errors to the Physic server on removing cells

CSG
- [ ] https://github.com/godotengine/godot/issues/22246 - CSGShape use_collision doesn't use collision layers and masks
- [ ] https://github.com/godotengine/godot/issues/30442 - Collision between CSGPolygon and ConcavePolygonShape not working
- [ ] https://github.com/godotengine/godot/issues/36893 - CSGShape doesn't have physics material
- [ ] https://github.com/godotengine/godot/issues/43251 - Broken collision with invisible CSGCombiners

Ragdoll
- [ ] https://github.com/godotengine/godot/issues/26618 - Move joint does not work
- [ ] https://github.com/godotengine/godot/issues/28707 - ragdoll simulation twitches in simple humanoid ragdoll
- [ ] https://github.com/godotengine/godot/issues/40076 - PhysicalBones do not move with skeleton when simulation is off
- [ ] https://github.com/godotengine/godot/issues/40549 - PhysicalBones broke themselves
- [ ] https://github.com/godotengine/godot/issues/40614 - Scaling Skeleton with PhysicalBones results in math errors
- [ ] https://github.com/godotengine/godot/issues/42010 - Having BoneAttachment node before a Physical Bone for the same bone throws error
- [ ] https://github.com/godotengine/godot/issues/44589 - PhysicalBone is delayed if it has not ragdolled parent

Soft body
- [ ] https://github.com/godotengine/godot/issues/21190 - Weird behaviours with soft body node under kinematic parent
- [ ] https://github.com/godotengine/godot/issues/22160 - softbody mesh got stucked
- [ ] https://github.com/godotengine/godot/issues/26611 - SoftBody pinned point indices not corresponding to mesh vertices due to removal of duplicate mesh vertices
- [ ] https://github.com/godotengine/godot/issues/27039 - Soft bodies do not collide with each other
- [ ] https://github.com/godotengine/godot/issues/33485 - vulkan - 4.0 dev - SoftBodies are broken
- [ ] https://github.com/godotengine/godot/issues/36693 - SoftBody is not affected by space override
- [ ] https://github.com/godotengine/godot/issues/37125 - Softbodies do not work when run in headless mode
- [ ] https://github.com/godotengine/godot/issues/41194 - SoftBody doesn't follow the fixed point in real time
- [ ] https://github.com/godotengine/godot/issues/41390 - SoftBody shoots from point zero [GLES2]
- [ ] https://github.com/godotengine/godot/issues/42487 - SoftBody It has error get_global_transform
- [ ] https://github.com/godotengine/godot/issues/44883 - SoftBody ignores translation when using GLES2

Vehicle
- [ ] https://github.com/godotengine/godot/issues/34567 - VehicleBody behaves weirdly with CollisionPolygon
- [ ] https://github.com/godotengine/godot/issues/34856 - Wrong physics when accelerating and braking using vehicle wheel
- [ ] https://github.com/godotengine/godot/issues/37018 - Vehicle Wheel doesnt spin on air
- [ ] https://github.com/godotengine/godot/issues/37816 - godot 3.2 VehicleBody and VehicleWheel engine_force strange behavior
- [ ] https://github.com/godotengine/godot/issues/42253 - VehicleBody not react to collision layers

Heightmap
- [ ] https://github.com/godotengine/godot/issues/37337 - HeightMapShape collision does not update properly when the body is translated
- [ ] https://github.com/godotengine/godot/issues/40664 - Cannot create a HeightMap CollisionShape in Godot physics
- [ ] https://github.com/godotengine/godot/issues/43625 - HeightmapShape gets KinematicBody stuck, unlike BoxShape or ConcavePolygonShape

Multi-threading
- [ ] https://github.com/godotengine/godot/issues/26900 - ARVR image shakes when Multithreaded and ARVROrigin is attached to RigidBody

Other
- [ ] https://github.com/godotengine/godot/issues/22064 - Severe lag when adding a collider to a physics object with many colliders
- [ ] https://github.com/godotengine/godot/issues/31016 - Inconsistent physics delta
- [ ] https://github.com/godotengine/godot/issues/34000 - Procedural Generation for Android app
- [ ] https://github.com/godotengine/godot/issues/35913 - 3.2 Bug - NAN Error randomly spams console, then crashes
- [ ] https://github.com/godotengine/godot/issues/37850 - Window freezes when using PhysicsServer in background thread
- [ ] https://github.com/godotengine/godot/issues/41076 - Performances issues when adding lot of convex shapes to a RigidBody

Editor
- [ ] https://github.com/godotengine/godot/issues/29991 - Collision layer name doesn't update in the inspector when changed
- [ ] https://github.com/godotengine/godot/issues/32216 - CylinderShape and HeightMapShape GodotPhysics error on project startup (due to EditorHelp generation)
- [ ] https://github.com/godotengine/godot/issues/40885 - Discrepancy between physics joints behavior and editor gizmo
- [ ] https://github.com/godotengine/godot/issues/40962 - Debugger RayCast Reference Crash segfault in ::_get_property_listv
- [ ] https://github.com/godotengine/godot/issues/41522 - Creating convex collision from a mesh results in duplicate vertices
- [ ] https://github.com/godotengine/godot/issues/43744 - When raycasting in editor (Tool), collisions only register within bodies' original bounding box area
- [ ] https://github.com/godotengine/godot/issues/44090 - Lag spike when creating collision shape for mesh instance

Documentation
- [ ] https://github.com/godotengine/godot/issues/34395 - Joints spring settings
- [ ] https://github.com/godotengine/godot/issues/40887 - Instancing of a scene does not instance a new ConcavePolygonShape in a collision shape
- [ ] https://github.com/godotengine/godot/issues/45268 - RigidBody freezes in rotating Spatial

4.0 Refactoring
- [ ] https://github.com/godotengine/godot/issues/20276 - body_test_motion not available in gdscript on PhysicsServer
- [ ] https://github.com/godotengine/godot/issues/21634 - apply_impulse is not intuitive
- [ ] https://github.com/godotengine/godot/issues/25254 - Shouldn't PhysicsMaterial properties correspond to individual shapes rather than the body?
- [ ] https://github.com/godotengine/godot/issues/30029 - move_and_slide() takes in velocity, while move_and_collide() takes in position offset

**Comment by Demindiro** [comment]
I think #35877 should be added here too?

**Comment by josefkaragoli** [comment]
Will you completely rewrite godotphysics from scratch or just address the issues in the tracker?

**Comment by Calinou** [comment]
> Will you completely rewrite godotphysics from scratch or just address the issues in the tracker?

I don't think it'll be rewritten completely, even if parts of GodotPhysics may receive a refactoring. Instead, issues will be fixed individually.

**Comment by golddotasksquestions** [comment]
Is it possible to add these two issues as well?
https://github.com/godotengine/godot/issues/14578
https://github.com/godotengine/godot/issues/27441

**Comment by pouleyKetchoupp** [comment]
@golddotasksquestions They are already in the 2D physics tracker.

**Comment by josefkaragoli** [comment]
Is there a repo or somewhere we can see progress?

**Comment by Calinou** [comment]
> Is there a repo or somewhere we can see progress?

Progress on the physics engine itself occurs on this very repository.

**Comment by Saitodepaula** [comment]
I know it is not an issue, it is a proposal, but could this one be included too? 
https://github.com/godotengine/godot-proposals/issues/945

**Comment by Calinou** [comment]
> As a side question/note: is it documented that Godot Physics handles center of mass in a different way than Bullet? I've read it somewhere, but can't find it now: that Godot Physics takes all the collision shapes of a body and calculates the center of mass from them.
Yes: https://github.com/godotengine/godot/pull/41563

**Comment by Einlander** [comment]
Can #46610 be added to the csg section?

**Comment by Calinou** [comment]
> Can #46610 be added to the csg section?

This isn't a physics-related issue. Do we have a tracker issue for CSG?

**Comment by snouk-z** [comment]
Can this one be added to ?
https://github.com/godotengine/godot-proposals/issues/483

Enabling calls to the physics API from multiple threads would be an awesome addition.

**Comment by RabidTunes** [comment]
>  @golddotasksquestions commented on 20 Feb
Is it possible to add these two issues as well?
#14578
#27441

> @pouleyKetchoupp commented on 20 Feb
They are already in the 2D physics tracker.

As I pointed out in one of #14578 comments, this also happens in 3D with the correspondent 3D nodes. Maybe should I create another separated issue for 3D?

**Comment by lewis-conroy** [comment]
Sorry if this already exists, but KinematicBodies moved with `move_and_slide()` slide down slopes regardless of the value of `stop_on_slope`. Is there an issue open for this already?

**Comment by Calinou** [comment]
> Sorry if this already exists, but KinematicBodies moved with `move_and_slide()` slide down slopes regardless of the value of `stop_on_slope`. Is there an issue open for this already?

Yes: https://github.com/godotengine/godot/issues/31097

**Comment by nezvers** [comment]
Didn't find mention of this issue #49323

**Comment by Nekuromu** [comment]
I have opened another issue on ConvexPolys related to RigidBodies #55503

**Comment by elvisish** [comment]
I had a bunch of bugs with Godot Physics that seem to have gone with switching to Bullet. I'm using a custom stair stepping implementation and it's not triggering incorrectly with bullet, nor is weird slope handling happening.

**Comment by Calinou** [comment]
> I had a bunch of bugs with Godot Physics that seem to have gone with switching to Bullet. I'm using a custom stair stepping implementation and it's not triggering incorrectly with bullet, nor is weird slope handling happening.

Can you upload a minimal reproduction project somewhere?

**Comment by elvisish** [comment]
[gp_vs_bullet.zip](https://github.com/godotengine/godot/files/7916004/gp_vs_bullet.zip)
Here, try walking slowly on the ramp with GP, there will be some weird glitching and popping out and occasionally you can get the player to spawn underground. The bullet physics are smooth as silk, although GP is much better for step handling as there isn't that slight move_and_slide drift if you walk up them slowly.

**Comment by akien-mga** [comment]
@elvisish Could you open a dedicated bug report for this? This issue is a tracker issue to get an overview over existing bug reports. So the workflow would be that you open a bug report about your Godot Physics specific issue, and we'll add it to the list.

**Comment by elvisish** [comment]
> @elvisish Could you open a dedicated bug report for this? This issue is a tracker issue to get an overview over existing bug reports. So the workflow would be that you open a bug report about your Godot Physics specific issue, and we'll add it to the list.

Sure, give me a few minutes I'll write one up and use this as my test project. It's a shame, Godot Physics is MUCH better for stairs precision and it snaps up so smoothly where bullet fails but there's a bunch of other issues that I'll mention.

**Comment by elvisish** [comment]
> @elvisish Could you open a dedicated bug report for this? This issue is a tracker issue to get an overview over existing bug reports. So the workflow would be that you open a bug report about your Godot Physics specific issue, and we'll add it to the list.

As @Calinou edited, I've opened an issue. Of note is the last video, you can see the seam/edge issue where the body falls through and gets stuck irreparably, this happens without my up_stepping function and only happens with Godot Physics, not Bullet.

**Comment by elvisish** [comment]
I’ve since found box collider to be a lot more stable than capsule or cylinder, I still need to test this although I’m not the first to have noticed: https://www.reddit.com/r/godot/comments/pgt0wg/kinematic_body_using_godot_physics_gets_caught_on/

**Comment by elvisish** [comment]
Are Godot Physics still planned on being fixed now @pouleyKetchoupp is no longer working on them? I'm having to go ahead with GP instead of Bullet, but GP gets stuck in so many gaps it's hard to really work with it in any stable sense, but I imagine it will need to be improved for GD4?

**Comment by Calinou** [comment]
> Are Godot Physics still planned on being fixed now @pouleyKetchoupp is no longer working on them?

Yes, but only if a motivated contributor steps up and opens pull requests :slightly_smiling_face: 

I don't have time (or experience) to work on the physics engine myself.

**Comment by elvisish** [comment]
> > Are Godot Physics still planned on being fixed now @pouleyKetchoupp is no longer working on them?
> 
> Yes, but only if a motivated contributor steps up and opens pull requests slightly_smiling_face
> 
> I don't have time (or experience) to work on the physics engine myself.

What is the recommended physics engine to use as of now? Both GP and Bullet implementations have different yet equally problematic bugs right now and with no guarantee either will ever be fixed, I'm uncertain which way to proceed.

GP is frequently recommended since Bullet will be eventually depreciated, but currently it has game breaking bugs that are very easy to cause... in fact, it's harder to not have issues with GP right now. Conversely, Bullet is pretty rock solid but it's future is uncertain and there's many issues with margins that make physics queries completely unreliable.

**Comment by Calinou** [comment]
> What is the recommended physics engine to use as of now?

There is no specific recommendation for 3.x – use the one that works the best for your use cases.

**Comment by elvisish** [comment]
> > What is the recommended physics engine to use as of now?
> 
> 
> 
> There is no specific recommendation for 3.x – use the one that works the best for your use cases.

That's just the problem, neither works best right now, they both have different flaws that makes it very difficult to pick one over the other.

I would say Bullet is at the very least production ready, but using it for any precise space state work is unreliable. Conversely, GP is very smooth for space state work but has game breaking bugs with general collision and overlaps during movement which makes it totally unusable for production work.

**Comment by Gastronok** [comment]
It seems to me a strange allocation of resources to see all these updates on new 3D rendering techniques while it looks like the fundamental ability to move around in 3D environments is so unreliable.

Are there plans to re-aquire a dedicated physics contributor or is that not a priority?

**Comment by elvisish** [comment]
> It seems to me a strange allocation of resources to see all these updates on new 3D rendering techniques while it looks like the fundamental ability to move around in 3D environments is so unreliable.
> 
> 
> 
> Are there plans to re-aquire a dedicated physics contributor or is that not a priority?

I agree, currently only basic 3D physics work is possible since Bullet can't be used for anything precise (and definitely no space state work) and GP is in alpha mode as bodies get stuck on anything and everything that isn't super basic geometry.

**Comment by reduz** [comment]
There will definitely be more focus on bug fixing after beta.

**Comment by elvisish** [comment]
Just tried Godot 4.0 beta 3 and *still* getting stuck in weird geometry, and without Bullet as a backup there's not much hope other than to ensure any terrain or meshes for walking on are absolutely bug tested to ensure there cannot be any strange surfaces to get stuck on. I'd have thought this would have been a far greater priority now there's no fallback physics engine and 4.0 is onto beta 3.

**Comment by timshannon** [comment]
FWIW, @elvisish I think there are a lot of bugs with the cylinder implementation and maybe capsule.  All of my getting stuck with my character body issues went away with a cube collision shape.  It's not ideal, but it works better than a cylinder.

**Comment by elvisish** [comment]
> FWIW, @elvisish I think there are a lot of bugs with the cylinder implementation and maybe capsule.  All of my getting stuck with my character body issues went away with a cube collision shape.  It's not ideal, but it works better than a cylinder.

Thanks, I was using capsule as I want to go over some rocky terrain but... Godot 4.0 still doesn't have stair stepping, hmm.

**Comment by Saitodepaula** [comment]
> It seems to me a strange allocation of resources to see all these updates on new 3D rendering techniques while it looks like the fundamental ability to move around in 3D environments is so unreliable.
> 
> Are there plans to re-aquire a dedicated physics contributor or is that not a priority?

I have been using Godot for 3 years now, developing a game, opening some issues, watching development in many areas, and even created open source demos for physics based games. I've never complained about some features in the physics area progressing slowly (or not progressing at all), because I understand that, this being FOSS, that's how it works: if there are capable people wanting to do something, it gets done. If there are no people, nothing happens.

But now that Godot 4 is in beta 3, rendering seems to be evolving well, subjects like double precisions for large worlds getting an exclusive blog post (a subject I would think only a few games would need), wouldn't it be nice to have a roadmap of where physics is intended to go?

I'm not even asking for development in this area, because this is FOSS. But some information about what the project leaders think is the most probable route from now on. Just a few examples: vehicle body, is it going to stay? Joints in general, are they going to be fixed?

**Comment by qdeanc** [comment]
Just some context:

The Godot team had initially hired a skilled contributor who was seemingly going to fix all of these bugs, but that person ended up accepting a job working on the Rockstar Games physics engine as far as I'm aware.

As far as I know, collision detection (especially continuous collision detection) and stable collision/constraint solvers are especially complicated to program. It's probably hard to find another specialist willing to take on such a challenge remotely and for a low rate.

**Comment by elvisish** [comment]
I think our only hope in the immediate future is for PhysX or Rapier or something to be ported as an extension to provide something extremely stable that, while perhaps not as well integrated or optimised for game work as GP, would at least be fail safe for production work until GP is 100% reliable in all conditions.

**Comment by timshannon** [comment]
> I think our only hope in the immediate future is for PhysX or Rapier or something to be ported ...


I'm keeping my eye on https://github.com/jrouwe/JoltPhysics personally.  I'm hoping GDExtension opens up a lot of possibilities.

**Comment by golddotasksquestions** [comment]
@timshannon @elvisish 
Regarding JoltPysics there is a discussion regarding Godot integration here: https://github.com/godotengine/godot-proposals/discussions/5161#discussioncomment-3473609

**Comment by elvisish** [comment]
Quick reminder that this minimal test project I uploaded a year ago-ish is all you need to test if physics are working or not; if it goes up stairs while crouching or doesn't get stuck behind the stairs, we done: https://github.com/godotengine/godot/issues/58260

**Comment by alfredbaudisch** [comment]
Should I create bug report for this or is there already something related?

Colliding agains ConcaveShapes or ConvexHulls with `move_and_slide` with a very simple CharacterBody3D controller makes everything sloppy or frozen from 10ms to 2 seconds.

Notice how the game just freezes when hitting the barrel:

https://user-images.githubusercontent.com/248383/208972088-0e9d9e46-06ff-47e8-89c2-bd9d9d061cec.mp4

![imagen](https://user-images.githubusercontent.com/248383/208972359-ab2eb5e9-b5bb-4bda-a178-ba8b7a5a9b14.png)

**Comment by Zireael07** [comment]
@alfredbaudisch How complex is that collider on the barrel?

**Comment by alfredbaudisch** [comment]
> @alfredbaudisch How complex is that collider on the barrel?

I attached the image of the wireframe, the collider is closer to the mesh structure, it's around 700 vertices, which should not cause this kind of slow-down.

**Comment by alfredbaudisch** [comment]
@Zireael07 it's indeed related to [#48587](https://github.com/godotengine/godot/issues/48587) and https://github.com/godotengine/godot/issues/66354

**Comment by CornbreadWithMarmalade** [comment]
Can #67801 be added to the collision detection section

**Comment by GrauBlitz** [comment]
I am a bit shocked to see a v4 RC1 with all this open issues, meanwhile my Bean Character still get's stuck on the edge of an cube...

**Comment by Lippanon** [comment]
> There will definitely be more focus on bug fixing after beta.
Since this comment, 3 more issues were added to the tracker, 0 were checked as fixed, and a bunch more physics-related were created that aren't in the tracker. There's an ever increasing issue list, with multiple regressions from betas that don't get fixed before new versions get pushed. I appreciate that Godot relies on willing contributors but why are Release Candidates already being put out? Is there a deadline? It feels like Godot 4 is being rushed for no good reason.

**Comment by elvisish** [comment]
> stabilize what we have now and which is already usable by many

I'm just not sure Godot Physics are currently usable (for production work), prototypal maybe.

**Comment by Calinou** [comment]
> I am a bit shocked to see a v4 RC1 with all this open issues, meanwhile my Bean Character still get's stuck on the edge of an cube...

Box colliders tend to be a lot more reliable than capsules currently. I recommend sticking to a box collider (and make sure it's not rotated during gameplay).

**Comment by elvisish** [comment]
> Box colliders tend to be a lot more reliable than capsules currently. I recommend sticking to a box collider (and make sure it's not rotated during gameplay).

This is very true, and I've exclusively used box colliders that don't rotate (AABB, basically) using a child gimbal that's rotated to determine direction of movement. However, the engine is still plagued with issues using a box collider; as far as I'm aware it's still impossible to walk into an angled corridor or into a sloped ceiling that becomes thinner or shorter than the collider without irreparably getting stuck and having to reload the scene.

**Comment by GrauBlitz** [comment]
> > Box colliders tend to be a lot more reliable than capsules currently. I recommend sticking to a box collider (and make sure it's not rotated during gameplay).
> 
> This is very true, and I've exclusively used box colliders that don't rotate (AABB, basically) using a child gimbal that's rotated to determine direction of movement. However, the engine is still plagued with issues using a box collider; as far as I'm aware it's still impossible to walk into an angled corridor or into a sloped ceiling that becomes thinner or shorter than the collider without irreparably getting stuck and having to reload the scene.

But switching to a box collider should not be necessary for a fully v4 imho, as a capsule collider is a typical Character Controller shaped and recommended in every tutorial, especially for the Unity folk which is watching this engine to switch on v4. Releasing with an instable physics engine could leave many people behind or scare them away.

I am still experiencing many issues, my character controller is getting stuck on any a bit steep angle, independent from the collision shape. I can't walk normally on a procedural generated terrain, i can't walk or jump over a cube without issues, ... i think these are very basic Physic engine usecases and nothing special.

**Comment by Zireael07** [comment]
> But switching to a box collider should not be necessary for a fully v4 imho

True, but unfortunately "fully v4" won't be what 4.0 is. 4.0 has already been in the works for so long and trying to iron out all the bugs would only delay it by another three months or more IMHO - which is not worth it.

> Releasing with an instable physics engine could leave many people behind or scare them away.

Physics have had issues back in 3.x too (actually, most of the problems in the tracker exist in 3.x too). Somehow that didn't scare people away from using 3.x

**Comment by elvisish** [comment]
> > > my character controller is getting stuck on any a bit steep angle, independent from the collision shape. I can't walk normally on a procedural generated terrain, i can't walk or jump over a cube without issues

I don't think you can use anything but boxes for floors right now, slightly sloped boxes might work but it can't change shape over the shape like terrain would or you'll get stuck.

**Comment by elvisish** [comment]
L> True, but unfortunately "fully v4" won't be what 4.0 is. 4.0 has already been in the works for so long and trying to iron out all the bugs would only delay it by another three months or more IMHO - which is not worth it.

If a major (and physics is major) component is completely broken, what is the purpose of releasing 4.0? It's just a number, and there's no shareholders or investors to please so it makes no sense to rush release something that isn't ready yet.
> 
> 
> 
> Physics have had issues back in 3.x too (actually, most of the problems in the tracker exist in 3.x too). Somehow that didn't scare people away from using 3.x

Besides the complacency of this, nobody uses Godot Physics in 3.x as it's broken, they use Bullet which isn't broken and was removed in 4.0 (for no particular reason).

**Comment by GrauBlitz** [comment]
> > But switching to a box collider should not be necessary for a fully v4 imho
> 
> True, but unfortunately "fully v4" won't be what 4.0 is. 4.0 has already been in the works for so long and trying to iron out all the bugs would only delay it by another three months or more IMHO - which is not worth it.
> 
> > Releasing with an instable physics engine could leave many people behind or scare them away.
> 
> Physics have had issues back in 3.x too (actually, most of the problems in the tracker exist in 3.x too). Somehow that didn't scare people away from using 3.x

I never had any issues with v3, but for me 3D development in v4 is plain unusable with the physics and i would not call this "iron out all the bugs" but more like providing a basic feature set of physics. Maybe I'm just not competent enough to setup a simple Character Controller with the v4 templates but I will have to skip v4 and wait for the next versions so i don't understand why releasing v4 in this state is even an option.

**Comment by akien-mga** [comment]
So I already answered all this here:

https://github.com/godotengine/godot/issues/45333#issuecomment-1424045229

This discussion is going nowhere, so locking. This is a tracker to keep an overview of bug reports, not to rant about Godot's release policy.

We're doing what we can, most other areas are release ready and while physics still has significant known issues, it's not the end of the world and they will be worked on and fixed in future 4.x releases. If you're making a physics based game that can't work in 4.0, you can simply skip this release and wait for a future 4.x release which will fix your issues - but there's no reason to hold the release for the many other use cases which work fine.
