### ISSUE TITLE
[TRACKER] DirAccess bugs

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4727]
This issue is meant to list all bugs to ``DirAccess``/the ``Directory`` GDScript API, so that they can be investigated all at once:

- [x] #1680 Inconsistent support for user:// vs res:// directory operations
- [x] #1872 DirAccess fails on make_dir and dir_exists with user://
- [x] #1938 No ../ when entering the folder without permissions to read
- [x] #4617 Directory::get_space_left() does not return consistent "failure" values
- [x] #4705 Directory.dir_exists() always fails on res:// type paths even though Directory.open() works

See also discussion about paths in #4700.

*Existing PRs:*

- #584 Globals::localize_path was calling change_dir to check if path exists

**Comment by reduz** [comment]
closing this due to bingo
