### ISSUE TITLE
[TRACKER] Remote scene tree dock issues

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#47369]
## Bugs

- [ ] https://github.com/godotengine/godot/issues/13219
- [ ] https://github.com/godotengine/godot/issues/25375
- [ ] https://github.com/godotengine/godot/issues/28353
- [ ] https://github.com/godotengine/godot/issues/29965
- [ ] https://github.com/godotengine/godot/issues/34844
- [ ] https://github.com/godotengine/godot/issues/39847
- [ ] https://github.com/godotengine/godot/issues/41442
- [ ] https://github.com/godotengine/godot/issues/44853
- [ ] https://github.com/godotengine/godot/issues/47237

## Enhancements

- [ ] https://github.com/godotengine/godot/issues/23132
- [ ] https://github.com/godotengine/godot/issues/23768
