### ISSUE TITLE
[TRACKER] Drag & Drop related issues

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#4774]
### This is a tracker for drag drop related issues:
- [x] Drag and Drop reparenting bug https://github.com/godotengine/godot/issues/4712 (bug)
- [x] Bug with drag&drop in the Scene tab https://github.com/godotengine/godot/issues/4628 (bug)
- [x] D&D Incorrect new index when arranging children in Scene Tree https://github.com/godotengine/godot/issues/4633 (bug)
- [x] D&D FileSystem error on moving gdscript file to another folder https://github.com/godotengine/godot/issues/4786 (bug)
- [x] AutoLoad, Drag and Drop https://github.com/godotengine/godot/issues/3543 (feature request)
- [x] D&D to re-order tabs https://github.com/godotengine/godot/issues/1030 (feature request)
- [x] FileSystem drag and drop can easily lead to missing dependencies issues #5684 (bug)
- [x] D&D Ability to reorder scripts in script view https://github.com/godotengine/godot/issues/4775 (feature request)
- [x] drag/drop meshes into viewport #4945 (feature request)
- [x] D&D a node from the scene panel, into a gdscript to get its path https://github.com/godotengine/godot/issues/2505 (feature request)
- [ ] Drag & Drop node to scripts sometimes handles incorrectly (bug) https://github.com/godotengine/godot/issues/33704

**Comment by AlexHolly** [comment]
Ubuntu 14.04
In FileSystem I want to move tileset.gd to my /scripts folder

```
move file res://tileset.gd -> /tileset.gd
found files to remap: 0
moving file res://tileset.gd to /tileset.gd
ERROR: add_io_error: Error moving file:
res://tileset.gd

   At: tools/editor/editor_node.cpp:4003.
call rescan!
```

**Comment by akien-mga** [comment]
Please open another issue for that @AlexHolly, this one is meant to link to other issues.

**Comment by pwab** [comment]
As only the last one is left is this tracker still needed?

**Comment by Anutrix** [comment]
Add https://github.com/godotengine/godot/issues/41768.

**Comment by KoBeWi** [comment]
Yeah tracker with single open issue is not very useful.
