### ISSUE TITLE
[TRACKER] Scene Inheritance related issues

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#4778]
This is a tracker for issues related to Scene Inheritance:

- [ ] "Parse Error: Unexpected end of file" in inherited .tscn files https://github.com/godotengine/godot/issues/3897 (bug)
- [ ] Inherited scenes: float variables always seen as custom, can't be reset https://github.com/godotengine/godot/issues/4759 (bug)
- [ ] Inherited scene saving parent nodes in incorrect order https://github.com/godotengine/godot/issues/3945 (bug)
- [ ] Tscn/tres: Inconsistencies in the extension filters of the save/open file dialogs https://github.com/godotengine/godot/issues/2946 (enhancement)
- [ ] Ability to extend base scene script easily for inherited scenes https://github.com/godotengine/godot/issues/4585 (enhancement)
- [ ] Document new scene inheritance concept https://github.com/godotengine/godot/issues/3354 (docs)

**Comment by kubecz3k** [comment]
2.1 milestone since at least bug fix should be considered for 2.1

**Comment by reduz** [comment]
done with the bugs

**Comment by kubecz3k** [comment]
Updated the list, hopefully I didn't miss anything.

**Comment by reduz** [comment]
would be nice to see how much of this changed

**Comment by kubecz3k** [comment]
Actually have this on my todo list :) I will update it at the beginning of the next week!

**Comment by kubecz3k** [comment]
I was searching today for new scene inheritance related issues in order to update tracker. But I haven't found anything new...  (only one issue that I submitted earlier today)

**Comment by LikeLakers2** [comment]
#3354 is fixed.

**Comment by pwab** [comment]
#10147 is fixed and documentation for making resources unique is tracked by [godot-docs/issues/581](https://github.com/godotengine/godot-docs/issues/581)

**Comment by rcorre** [comment]
> Ability to modify Animation player in inherited scenes #6169 (enhancement)

Is this fixed? Even importing animations as separate files only persists changes until the next time you export your scene, at which point all your added tracks are wiped out.

@akien-mga's [last comment](https://github.com/godotengine/godot/issues/6169#issuecomment-419920679) was

> AnimationTreePlayer is deprecated in Godot 3.1 and will be removed in Godot 3.2. It is replaced by AnimationTree, which was written from scratch and likely fixes/deprecates this issue.

However, I'm unclear on how `AnimationTree` can replace the need for adding audio/call tracks to animations. I mentioned some use cases on https://github.com/godotengine/godot/issues/28275, maybe that issue should be part of this list?
