### ISSUE TITLE
[TRACKER] Removal of the editor's debugging prints

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#5031]
The Godot editor currently has many debugging prints that don't serve real purposes to users, such as:
- [x] "found bug?"
- [x] "LANG IS (language code)"
- [x] "TESTING (language code)"
- [x] "ok translation"
- [x] "DPI MODE: (something)"
- [x] "VBoxContainer: 136,100"
- [x] "bind toptions"
- [x] "settings changed"
- [x] "********\* listening on port 6007"
- [x] "OK! 23"
- [x] "has connection!"
- [x] "pre-removing print handler..."
- [x] "removing print handler..."
- [x] "found"
- [x] "CLOSING CONNECTION"
- [x] "performing reparent"
- [x] "returned: 19840, waiting for: 19840"
- [x] "parent function"
- [x] "Built in type constant"

Some of those messages will even be printed in exported projects. I suggest that those messages are hidden from `release` and `release_debug` builds at least.

_Once the message has been removed, the checkbox can be checked next to it._

**Comment by J08nY** [comment]
I think it would be best to either remove all messages like these, or establish some consistent style/rules for having them. For example, have a `print_debug(...)` macro, that will print only on _DEBUG_ENABLED_ and will print nice messages like: "Godot v2.1: message". Errors are printed nicely, so having these in release code is sure pretty pointless.

**Comment by akien-mga** [comment]
I agree. There is also a `-d`, `-debug` command line switch that should typically be used to print such debug info. We should get the source code rid of all `print_line` calls.

**Comment by J08nY** [comment]
I can get on this. How about:

1. Replace all `print_line` calls currently used for debugging with `print_debug`. I don't yet know how and where all `print_line` is used, so I will be only replacing obvious debugging lines.
2. `print_debug` will:
 - only print if _DEBUG_ENABLED_ or godot was started with _-d_?
 - print lines like: `"Godot v2.1: message..."`

**Comment by akien-mga** [comment]
Oh, I was sure we already had a function for debug prints, but I can't find one actually (at least by `ack -i`'ing for "debug"). We have nice macros for ``WARN_PRINT`` and ``ERR_PRINT``, maybe we should think a bit about what we want for debug prints, information prints, etc. Maybe we need to add several levels of verbosity for information/debug/warning/errors (especially for release builds).

@reduz Is it something you had given some thought to already, or should we just design what we feel is best? :)

> will print nice messages like: "Godot v2.1: message".

What's the interest in printing `Godot v2.1:` before all messages though? Printing the version once on initialization might be relevant for logs, but not repeating it in each message.

**Comment by J08nY** [comment]
I just checked and it seems that: 

- None of these prints are enabled in `target=release` however they are enabled in `target=debug` and `target=debug_release`. 
- Also the _-d_ switch turns on both the `print_line` prints and a debug mode. So this behaves as expected.

My aim with the `Godot $version:` prefix was to differentiate messages printed by Godot and message printed from scripts running.
I think we can agree that removing these prints listed above is a good thing to do.

**Comment by MarianoGnu** [comment]
Even when TOOLS_ENABLED is defined, these errors should only be listed on test builds, custom and official editor builds should not shot all the noise, probably another flag is worth?

**Comment by reduz** [comment]
feel free to remove any prints unless it's really meant to be a print

**Comment by vnen** [comment]
One less after fea9511bc6be3135ee80f6aef03b4323110826e9

**Comment by akien-mga** [comment]
Alright, all the prints listed in OP are now removed. Keeping this tracker open though so that we can continue listing prints we want to remove.

Generally speaking, I think we should review the various methods we have to output stuff to the terminal (there's a least `print`, `printf`, `print_line`, `print_debug`, `WARN_PRINT`, ERR_PRINT`, likely a couple others), and decide what should be used in what case, and use that accordingly. Adding an `INFO_PRINT` method might be nice too for the "legit" `print_line` that we want to keep. Then maybe a `DEBUG_PRINT` that would print user-relevant debug info when using the tools in debug mode, and for the "programmer's debugging", use `print_debug` maybe.
