### ISSUE TITLE
[TRACKER] Project settings that should be marked as "basic" following the basic/advanced split

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#50620]
### Issue description

Godot now has project settings marked as "basic" and "advanced" (non-basic), for the purposes of displaying only basic settings by default.

The initial selection of settings considered "basic" is quite small and needs many adjustments. Feel free to report which settings you think should be marked basic. At the same time, remember that not everything can be marked basic – there needs to be a sufficient difference with the Advanced Settings toggle :slightly_smiling_face: 

To make an advanced setting basic, replace its `GLOBAL_DEF()` call with `GLOBAL_DEF_BASIC()`.

*A :tada: reaction from @Calinou means the comment was incorporated into this post.*

### Steps to reproduce

Use the Godot editor and look for settings that most users will need to adjust at some point in their project.

### Advanced settings to mark as basic

- [x] `application/boot_splash/*` https://github.com/godotengine/godot/pull/61974
- [x] `application/run/main_scene` https://github.com/godotengine/godot/pull/61974
- [x] `display/mouse_cursor/*` https://github.com/godotengine/godot/pull/61974
- [x] `physics/2d/default_gravity` https://github.com/godotengine/godot/pull/61974
- [x] `physics/3d/default_gravity` https://github.com/godotengine/godot/pull/61974
- [x] `rendering/anti_aliasing/quality/msaa` https://github.com/godotengine/godot/pull/61974
- [x] `rendering/anti_aliasing/quality/screen_space_aa` https://github.com/godotengine/godot/pull/61974
- [x] `rendering/driver/driver_name` https://github.com/godotengine/godot/pull/61974
  - Since the project creation dialog allows changing the rendering backend, it should be exposed in the Project Settings immediately as well.
- [x] `rendering/environment/defaults/default_clear_color` https://github.com/godotengine/godot/pull/61974

### Basic settings to mark as advanced

- [x] `gui/fonts/dynamic_fonts/use_oversampling`
  - This setting generally only needs to be changed when you encounter bugs with font oversampling. You don't need it to have a pixelated font rendering when using the `viewport` stretch mode, or when using a font that's *designed* to look pixelated in the first place.
  - We'll have to remove the warning message that's printed on startup if we make this setting advanced.
- [ ] ~~`layer_names/*`~~
  - ~~Changing render or physics layer names generally doesn't need to be done by beginners.~~

**Comment by foxydevloper** [comment]
I think anti aliasing (`rendering/anti_aliasing/quality/msaa`, `rendering/anti_aliasing/quality/screen_space_aa`) should be under basic, I enable it on projects often, and it seems like a relatively basic and easy to use setting.

**Comment by foxydevloper** [comment]
Went through to find some more I think should be added to basic:
- `application/boot_splash/*`
- `editor/node_naming/name_casing`, maybe also `editor/node_naming/name_num_separator`, it's a niche setting, but very simple to understand and useful if you prefer your nodes and scenes to have a similar naming scheme as resources and scripts
- `physics/2d/default_gravity`
- `physics/3d/default_gravity`
- `rendering/environment/defaults/default_clear_color`, for changing the background color in 2D
- `display/mouse_cursor/*`, easy way for beginners to add custom mouse cursors

Also:
- Since `audio/buses/default_bus_layout` is in basic mode, it makes sense for `rendering/environment/default_environment` to be as well, or for both of them to not be basic
- `gui/fonts/dynamic_fonts/use_oversampling` probably shouldn't be a basic setting

**Comment by Calinou** [comment]
> editor/node_naming/name_casing, maybe also editor/node_naming/name_num_separator, it's a niche setting, but very simple to understand and useful if you prefer your nodes and scenes to have a similar naming scheme as resources and scripts

I'm not sure about that one. I'm of the opinion that settings that deviate from the Godot style guide should not be exposed as basic settings, for two reasons:

- New users should not be exposed too many stylistic options. Pick good defaults automatically.
- We want as many people as possible to follow the Godot style guide, so deviating away from it needs to have a good reason behind it.

**Comment by filipworksdev** [comment]
Hey guys the new Project preferences looks great. I would also like to propose the following changes: 

### Basic
`application/config/icon` move to Basic (straightforward app icon)
`application/run/low_processor_mode`  by itself should be moved to Basic (this functionality is beginner friendly on/off and is easy to understand) 
`application/boot_splash/image` move to Basic
`rendering/environment/defaults/default_clear_color` this is fairly straightforward and has immediate impact on the project
`display/window/size/always_on_top` move to Basic

I would also propose the gravity values for 2d and 3d would make more sense as basic specifically
`physics/2d/gravity`
`physics/3d/gravity` 

Additionally if you plan to have multiple physics engines or renderers perhaps the specific dropdowns should become visible in Basic:
`physics/2d/physics_engine`
`physics/3d/physics_engine`
`rendering/driver/driver_name` 

### Advanced
`layer_names/*` entire category should be Advanced
`gui/*` everything in gui should be in Advanced some of that functionality like Oversampling or Snap Controls to Pixels requires specific understanding

**Comment by filipworksdev** [comment]
Also I was thinking Basic could also display all the tooltips right underneath their respective properties instead of on mouse over. When switching to Advanced they will only show up on mouse over like they do now.

**Comment by Calinou** [comment]
> `application/config/icon` move to Basic (straightforward app icon)

You generally do not need to change this setting. Instead, replace `icon.png` at the project root with your icon. I'd prefer to encourage a "convention over configuration" approach like this when possible :slightly_smiling_face: 

> `application/run/low_processor_mode` by itself should be moved to Basic (this functionality is beginner friendly on/off and is easy to understand)

Games should generally not use this project setting (with rare exceptions). I fear it may be counterproductive to expose this as a basic setting, as enabling this in a game will likely make it appear less smooth.

The rest sounds good to me.

**Comment by foxydevloper** [comment]
I don't think layer names should be made advanced. Otherwise, it'd be very easy for people to mess up what layers are for what. I've used layer names every time I've used layers before. If layer names are in the way, it's very simple for someone to collapse the whole category.

**Comment by Calinou** [comment]
Now that https://github.com/godotengine/godot/pull/61974 has been merged, are there any outstanding project settings settings that should be marked as basic?

**Comment by Maran23** [comment]
Looks like this tracker is done?
I feel like we are good here.
TBH the only setting I would still see as basic is the custom theme and theme font, both are things you mostly change.
Still overall we are good here.
