### ISSUE TITLE
[TRACKER] Command line-related issues

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#51393]
### Godot version

N/A

### System information

N/A

### Command-line argument handling

- [ ] https://github.com/godotengine/godot/issues/17778

### Command-line debugger

- [ ] https://github.com/godotengine/godot/issues/19775
- [ ] https://github.com/godotengine/godot/issues/32693
- [ ] https://github.com/godotengine/godot/issues/32713
- [ ] https://github.com/godotengine/godot/issues/50170
- [ ] https://github.com/godotengine/godot/issues/51387

### Steps to reproduce

N/A

**Comment by hinlopen** [comment]
I think it's worth mentioning #49362, although I am not sure what's going to happen to it. In general, an issue I found was that the CLI tool was not just executing a tool, but actually initializing the editor.
