### ISSUE TITLE
[TRACKER] new commands to add into Command Palette.

### ISSUE THREAD

**Issue by Bhu1-V** [godotengine/godot#52009]
### Godot version

master

### System information

Any OS

### Issue description

Godot now has a Command Palette. But only all the commands are not added to the palette. 

Below are some commands that are currently in the Command Palette. Feel free to report which Commands(mostly shortcuts) you think should be added to the command palette. 

### Editor
- [ ] `editor/reload_current_project`
- [ ] `editor/reopen_closed_scene`
- [ ] `editor/unlock_selected_nodes`
- [ ] `editor/ungroup_selected_nodes`
### Script Editor
- [ ] `script_editor/reset_zoom`
- [ ] `script_editor/previous_script`
- [ ] `script_edior/next_script`
- [ ] `script_ediot/find_in_files`
- [ ] `script_editor/new`
- [ ] `script_editor/open`

### Steps to reproduce

look for Editor Settings > Shortcuts that need to be added into the command palette.

**Comment by dploeger** [comment]
I'd like to have a switch between the editor modes (2d/3d/script), open scene and start game and start current scene in there. Thanks!

**Comment by vini-guerrero** [comment]
Any chance to have a "Close All Open (Scripts/Scenes)" feature?

**Comment by me2beats** [comment]
As a plugin dev I'd love to have all of them in the palette list (or as much as possible) and be able to run them from a plugin.

This would be a great feature, now unfortunately most of commands cannot be called from the plugin (without some ugly workarounds).

**Comment by jasonwinterpixel** [comment]
Export targets could be accessible in here. Ie Export <Export Name>. Open editor settings, open project settings.

**Comment by MallocStudio** [comment]
in a mono build, I’d like a command that just Builds (compiles) the code without running the game if there’s no such shortcut already. This helps me with compilation error checking when I don’t have intellisense enabled or something like that.

That’d be fantastic. Thank you!

**Comment by Calinou** [comment]
> in a mono build, I’d like a command that just Builds (compiles) the code without running the game if there’s no such shortcut already. This helps me with compilation error checking when I don’t have intellisense enabled or something like that.
> 
> That’d be fantastic. Thank you!

Is this what the **Build** button does in the top-right corner of the editor?

**Comment by MallocStudio** [comment]
Yes. Is there a keyboard shortcut for that? Or for now is that button the only way of compiling?

**Comment by Calinou** [comment]
> Yes. Is there a keyboard shortcut for that? Or for now is that button the only way of compiling?

According to the source code, there isn't any shortcut for it yet: https://github.com/godotengine/godot/blob/e95fa21b455a5e2c512fe6e054f86df1f01e5bd3/modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs#L420-L427

Please open a proposal for this on the [Godot proposals](https://github.com/godotengine/godot-proposals/issues) repository.

**Comment by boruok** [comment]
from "editor" tab, tried to select _must have_ shortcuts for palette
```
close scene
distraction free mode
open 2D editor
open 3D editor
open script editor
editor settings
export
quit
toggle fullscreen
new inherited scene 
play
play custom
play custom scene
project settings
reload saved scene
save all scenes
save scene
save scene as
stop
take screenshot
visible collision shapes
visible navigation
```
i'm wondering. command-palette must support checkboxes/flags, for example: visible collision shape and navigation must have visual feedback for usability.

**Comment by dploeger** [comment]
> i'm wondering. command-palette must support checkboxes/flags, for example: visible collision shape and navigation must have visual feedback for usability.

That would be great. I know this feature from IntelliJ and it's pretty awesome.

Thinking about it, changing the theme would help for switching between dark and light mode. But there's no flags toggle currently for that, so this would expand command palette features to include select boxes as well.

That might be a too big feature set for the first version maybe.

**Comment by Vivalzar** [comment]
For now, the command palette contains only 2 entries for the Script Text Editor:

- `Find...`
- `Replace...`

Is there any reason to not have all the menus in the script editor (`File`, `Edit`, `Search`, ...) like in **vs-code**? Commands like `Move Up`, `Upper Case`, ... would be nice to have.
