### ISSUE TITLE
[TRACKER] Moving arrays of properties edition to the Inspector.

### ISSUE THREAD

**Issue by groud** [godotengine/godot#52463]
### Godot version

master

### System information

any

### Issue description

Since https://github.com/godotengine/godot/pull/52277 is implemented, we can now move several arrays of properties to this new system. This tracker aims to list all properties to either expose, move from a custom editor, or format as an array in the inspector. Basically, anythings that would benefit from the new property arrays implementation can go here.

So here is the list:
- [ ] ItemList node items
- [ ] OptionPopup node items (https://github.com/godotengine/godot-proposals/issues/368 )
- [ ] MeshLibrary resource items
- [ ] Tabs node items
- [ ] AnimatedTexture frames

Potential includes to discuss:
- [ ] Line2D, Line3D, CollisionPolygon2D, Path2D, Path3D, Polygon2D, NavigationPolygon, CurveTexture, CurveXYZTexture points
- [ ] AnimationPlayer
- [ ] SpriteFrames animations
- [ ] Gradients points
- [ ] LayeredTexture
...

Don't hesitate to comment anything you would like to be added here.

### Steps to reproduce

/

### Minimal reproduction project

/

**Comment by KoBeWi** [comment]
> Line2D, Line3D, CollisionPolygon2D, Path2D, Path3D, Polygon2D, NavigationPolygon, CurveTexture, CurveXYZTexture

These are already array properties, so I don't think it applies here.

**Comment by groud** [comment]
> These are already array properties, so I don't think it applies here.

Ah yeah that's true. Removing.

**Comment by barbaros83** [comment]
i cant select the items in the itemlist, is it a know issue ? related to this ? or should i open a new issue ?

**Comment by guyguy2001** [comment]
> GraphNode has slots property that could also use property array. ...

I want to be able to move the slots around - for example, if I add a new child to the node, and place it at the start, I would want to move the new slot to the start as well, to move the other slots alongside the old children.

I believe that a generic array property control would allow for that? If it does, then I'll be really happy if GraphNode would get this treatment
