### ISSUE TITLE
[TRACKER] SDFGI issues

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#55327]
### Godot version

s

### System information

s

### Bugs

- [ ] https://github.com/godotengine/godot/issues/40617
- [ ] https://github.com/godotengine/godot/issues/49836
- [ ] https://github.com/godotengine/godot/issues/52411
- [ ] https://github.com/godotengine/godot/issues/54176
- [ ] https://github.com/godotengine/godot/issues/54892
- [ ] https://github.com/godotengine/godot/issues/54978
- [ ] https://github.com/godotengine/godot/issues/55104
- [ ] https://github.com/godotengine/godot/issues/55322

### Enhancements

- [ ] https://github.com/godotengine/godot/issues/39961
- [ ] https://github.com/godotengine/godot/issues/41154
- [ ] https://github.com/godotengine/godot/issues/50770
- [ ] https://github.com/godotengine/godot/issues/50773

### Steps to reproduce

s
