### ISSUE TITLE
[TRACKER] VoxelGI issues

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#55328]
### Godot version

s

### System information

s

### Bugs

- [ ] https://github.com/godotengine/godot/issues/36702
- [ ] https://github.com/godotengine/godot/issues/38020
- [ ] https://github.com/godotengine/godot/issues/41642
- [ ] https://github.com/godotengine/godot/issues/47794
- [ ] https://github.com/godotengine/godot/issues/50029
- [ ] https://github.com/godotengine/godot/issues/50751
- [ ] https://github.com/godotengine/godot/issues/52791
- [ ] https://github.com/godotengine/godot/issues/53348
- [ ] https://github.com/godotengine/godot/issues/53529

### Enhancements

- [ ] https://github.com/godotengine/godot/issues/50842
- [ ] https://github.com/godotengine/godot/issues/52114
- [ ] https://github.com/godotengine/godot/issues/52115

### Steps to reproduce

s
