### ISSUE TITLE
[TRACKER] Vulkan Mobile backend-specific issues

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#55871]
### Godot version

x

### System information

x

### Issue description

This issue tracks issues specific to the Vulkan Mobile backend (such as bugs and undocumented missing features), **regardless of the host platform**.

See also https://github.com/godotengine/godot/issues/39033, which is specific to Android-only issues.

### Bugs

- [ ] https://github.com/godotengine/godot/issues/55867
- [ ] https://github.com/godotengine/godot/issues/55868
- [ ] https://github.com/godotengine/godot/issues/55870

### Steps to reproduce

x

**Comment by mrjustaguy** [comment]
Lights don't render on Mobile in github artifacts, tho work fine (with forced lambert shading) on Remi's Pre-Alphas

**Comment by Calinou** [comment]
> Lights don't render on Mobile in github artifacts, tho work fine (with forced lambert shading) on Remi's Pre-Alphas

Directional and point lights seem to render fine on my end (check the issues with screenshots I created today).

**Comment by mrjustaguy** [comment]
Here I've made an issue https://github.com/godotengine/godot/issues/55892 with the current Nightly Build. I suspect GPU architectural issues if people on newer GPUs don't have this issue.

**Comment by SimplyPhy** [comment]
Should this [and #39033] be with Milestone 4.0? Or perhaps 4.1.

**Comment by Calinou** [comment]
> Should this [and #39033] be with Milestone 4.0? Or perhaps 4.1.

I added milestone 4.0. However, I can't promise that all Vulkan mobile rendering bugs will be fixed for 4.0 – some of those will have to wait for 4.1.
