### ISSUE TITLE
[TRACKER] LightmapGI issues

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#56033]
### Godot version

x

### System information

x

### Issue description

This is a tracker issue for the GPU-based lightmapper in the `master` branch. See https://github.com/godotengine/godot/issues/55328 for VoxelGI issue and https://github.com/godotengine/godot/issues/55327 for SDFGI issues.

**This tracker only tracks issues in the `master` branch** (what will become 4.0 in the future), not `3.x`.

### Bugs

- [ ] https://github.com/godotengine/godot/issues/49936
- [ ] https://github.com/godotengine/godot/issues/52257
- [ ] https://github.com/godotengine/godot/issues/53436
- [ ] https://github.com/godotengine/godot/issues/53818
- [ ] https://github.com/godotengine/godot/issues/54679
- [ ] https://github.com/godotengine/godot/issues/55867
- [ ] https://github.com/godotengine/godot/issues/55868
- [ ] https://github.com/godotengine/godot/issues/56027
- [ ] https://github.com/godotengine/godot/issues/56030

### Missing features compared to `3.x`'s BakedLightmap

- [ ] https://github.com/godotengine/godot/issues/49935
- [ ] https://github.com/godotengine/godot/issues/49968
- [ ] https://github.com/godotengine/godot/issues/50568
- [ ] https://github.com/godotengine/godot/issues/50569
- [ ] https://github.com/godotengine/godot/issues/50570
- [ ] https://github.com/godotengine/godot/issues/50938
- [ ] https://github.com/godotengine/godot/issues/52199

### Enhancements

- [ ] https://github.com/godotengine/godot/issues/53818

### Steps to reproduce

x

**Comment by jcostello** [comment]
@clayjohn consider to set 4.1 for the milestone of the lightmaps fixes as they are really important for realistic lighting and mobile performance

**Comment by clayjohn** [comment]
> @clayjohn consider to set 4.1 for the milestone of the lightmaps fixes as they are really important for realistic lighting and mobile performance

It would be amazing if someone tackled these for 4.1! But I can't promise that someone will, volunteers work on what they are interested in working on. 4.x basically means that anything here can get merged as soon as someone makes a PR. 4.1 means that we will have PRs ready to close this issue by 4.1 which is just not realistic.

**Comment by CharlesLove** [comment]
I've found that I can get the temporarily "fix" the issue by turning the denoiser off. Anything else is pure black no matter what.

Here is my setup:
- Godot Engine v4.2.1.stable.official.b09f793f5
- Vulkan API 1.3.246 - Forward+ - Using Vulkan Device #0: Intel - Intel(R) UHD Graphics 620 (KBL GT2)
- NixOS 23.11.2217.d02d818f22c7 (Tapir) x86_64

**Comment by SpockBauru** [comment]
Maybe #82642 also belongs here
