### ISSUE TITLE
[TRACKER] BakedLightmap (CPU lightmapper) issues

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#56080]
### Godot version

x

### System information

x

### Issue description

This is a tracker issue for the CPU-based lightmapper in the `3.x` branch. See https://github.com/godotengine/godot/issues/56033 for issues related to the GPU-based LightmapGI in `master`.

**This tracker only tracks issues in the `3.x` branch**, not `master`.

### Bugs

- [ ] https://github.com/godotengine/godot/issues/23948
- [ ] https://github.com/godotengine/godot/issues/28350
- [ ] https://github.com/godotengine/godot/issues/45296
- [ ] https://github.com/godotengine/godot/issues/46442
- [ ] https://github.com/godotengine/godot/issues/47209
- [ ] https://github.com/godotengine/godot/issues/56078

### Enhancements

- [ ] https://github.com/godotengine/godot/issues/55681

### Steps to reproduce

x

### Minimal reproduction project

x

**Comment by Sleggie** [comment]
Is there any progress or news on this? Or perhaps an alternative for making specularity work with lightmaps? :)

**Comment by Sleggie** [comment]
> > Is there any progress or news on this? Or perhaps an alternative for making specularity work with lightmaps? :)
> 
> The CPU lightmapper isn't being actively worked on, as most of the focus is going towards the GPU lightmapper (which is still missing some features compared to the CPU lightmapper). There's a [GSoC project](https://godotengine.org/article/gsoc-2022-progress-report-1) currently working on the GPU lightmapper.

That sounds fantastic. But from what I understood, those developments are for the 4.0 version only,  am I correct?

**Comment by Calinou** [comment]
> But from what I understood, those developments are for the 4.0 version only, am I correct?

Yes – the GPU lightmapper won't be backported to 3.x, as it relies on functionality only found in Vulkan (and other modern graphics APIs).
