### ISSUE TITLE
[TRACKER] Vulkan BaseMaterial3D (StandardMaterial3D + ORMMaterial3D) issues

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#56333]
### Godot version

x

### System information

x

### Issue description

This is a tracker issue for the default 3D material implementation in Godot 4.0 (formerly SpatialMaterial). BaseMaterial3D provides StandardMaterial3D and ORMMaterial3D.

**This tracker only tracks issues in the `master` branch** (what will become 4.0 in the future), not `3.x`.

### Bugs

- [ ] https://github.com/godotengine/godot/issues/14403
- [ ] https://github.com/godotengine/godot/issues/48123
- [ ] https://github.com/godotengine/godot/issues/49841
- [ ] https://github.com/godotengine/godot/issues/50124
- [ ] https://github.com/godotengine/godot/issues/50231
- [ ] https://github.com/godotengine/godot/issues/50232
- [ ] https://github.com/godotengine/godot/issues/53444
- [ ] https://github.com/godotengine/godot/issues/55161
- [ ] https://github.com/godotengine/godot/issues/55771
- [ ] https://github.com/godotengine/godot/issues/56008
- [ ] https://github.com/godotengine/godot/issues/56332

### Missing features compared to `3.x`'s SpatialMaterial

- [ ] https://github.com/godotengine/godot/issues/51625

### Steps to reproduce

x

**Comment by tinmanjuggernaut** [comment]
Shouldn't these issues be on the GD4 roadmap? Also some of them are out of date, eg #56008 which has been fixed. And here's a new one: #63675
