### ISSUE TITLE
[TRACKER] Vulkan Decal issues

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#57284]
### Godot version

x

### System information

x

### Issue description

This is a tracker issue for the 3D Decal node in Godot 4.0's Vulkan renderer.

### Bugs

- [ ] https://github.com/godotengine/godot/issues/49639
- [ ] https://github.com/godotengine/godot/issues/49647
- [ ] https://github.com/godotengine/godot/issues/54496
- [ ] https://github.com/godotengine/godot/issues/54506
- [ ] https://github.com/godotengine/godot/issues/56590
- [ ] https://github.com/godotengine/godot/issues/56657

### Enhancements

- [ ] https://github.com/godotengine/godot/issues/49188
- [ ] https://github.com/godotengine/godot/issues/51299
- [ ] https://github.com/godotengine/godot-proposals/issues/1162
- [ ] https://github.com/godotengine/godot-proposals/issues/2188
- [ ] https://github.com/godotengine/godot-proposals/issues/3326

### Steps to reproduce

x

### Minimal reproduction project

x
