### ISSUE TITLE
[TRACKER] Vulkan automatic mesh LOD issues

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#57416]
### Godot version

x

### System information

x

### Issue description

This tracker is about issues related to **automatic** mesh LOD performed at import-time. This tracker does not cover issues related to manual (H)LOD performed using visibility ranges.

### Bugs

- [ ] https://github.com/godotengine/godot/issues/53818
- [ ] https://github.com/godotengine/godot/issues/54885
- [ ] https://github.com/godotengine/godot/issues/57404

### Enhancements

- [ ] https://github.com/godotengine/godot-proposals/issues/2600
- [ ] https://github.com/godotengine/godot-proposals/issues/3860
- [ ] https://github.com/godotengine/godot-proposals/issues/3861

### Steps to reproduce

x

### Minimal reproduction project

x

**Comment by fire** [comment]
Crashes in lod. https://github.com/godotengine/godot/issues/57362

**Comment by tinmanjuggernaut** [comment]
How do we generate lods and enable automatic use on already imported meshes? I have hundreds of assets already, stored in Godot's native resource format and saved in text scenes or as text resource files for git.

**Comment by Calinou** [comment]
> How do we generate lods and enable automatic use on already imported meshes? I have hundreds of assets already, stored in Godot's native resource format and saved in text scenes or as text resource files for git.

Automatic LOD generation is only supported when importing 3D scenes (glTF/Collada/FBX), not when loading pre-made meshes or importing 3D meshes (OBJ).

You can import OBJ as a 3D scene if you need LOD generation for OBJ.

**Comment by tinmanjuggernaut** [comment]
Thanks for the answer, but you're not supporting core features on your own native format (arraymesh)? There are tons of projects right around the corner from migrating to gd4 that won't be able to use lod without manually reimporting a ton. Many of them have meshes stored in scene files as arraymeshes without realizing they are disconnected from their import file. 

How do I know? Because the engine pushes you into the native format, because I've continually seen people on my team not realizing they are disconnecting resources from files which get saved in scene files, and because I've seen people do it on github issues.

They're all expecting autolod to just work and apparently it is not going to unless they first discover it's not working, troubleshoot it, write up an issue, then manually reimport every asset, then the setting up all of the auxiliary components again: physicsbodies, collision, materials, layers, parameters, etc. 

There is an unusable `surfacetool.generate_lod()`, but it says `Deprecated. Unused internally and neglects to preserve normals or UVs.` There is an `ImporterMesh.generate_lods()`, and the class can output an arraymesh, but I see no way to pass in an arraymesh.

**Comment by fire** [comment]
In the godot architecture, many procedures are ran on the raw scene before the final output. I was developing the gltf export code but it currently has a duplication nodes bug. I don’t have a good solution to rerunning the import process. Magbe marking as escn?

**Comment by fire** [comment]
For clarity.

1. Import this glb from https://github.com/KhronosGroup/glTF-Sample-Models/raw/master/2.0/Fox/glTF-Binary/Fox.glb
2. Make local and save as a scn/tscn
3. Go to the filesystem and rename to be .escn
4. It will use the import dialog

**Comment by tinmanjuggernaut** [comment]
Thanks for the suggestion. I took one asset, a single MeshInstance, saved it as a tscn, renamed it to escn, brought it back into a scene and saw the import dialog and brought it in w/ Generate LODs. However, no LODs were generated. Moving the camera back and forth, watching w/ Information and Wireframe turned on in the viewport, the mesh and info did not change. 

By the way, I probably have 1000 assets. Manually reimporting them one at a time is a very big ask. It's an unreasonable process considering:
* LOD generation is already in the engine
* The process above suggests a way to use LOD Generation on already imported assets is already or mostly implemented, so should continue towards full support
* The native format (arraymesh) should be treated as a first class citizen for reasons given in my last comment above.

**Comment by fire** [comment]
I would try to get escn to operate on mesh instances instead of the importermeshinstance. It's a bug.

**Comment by tinmanjuggernaut** [comment]
Thanks I'll follow the issue. If you want to get LOD generation to work on a meshinstance, rather than arraymesh, then workflow-wise, it would be reasonable to right-click the mesh instance and select Generate Lods. Or left-click the MeshInstance, click the Mesh menu, and Generate LODs. That should be the same as saving as escn and reopening, but would save developers a lot of clicks and manual work. Doing it once isn't a big deal, but it adds up if you have to do it hundreds of times.

**Comment by fire** [comment]
Does anyone know which issue describe lod generation being slow?

Profiles suggest https://share.firefox.dev/3ZY1DSC that:

1. SurfaceTool::generate_tangents takes 73% of the total runtime
