### ISSUE TITLE
[TRACKER] Collada export/import issues

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5808]
This is a tracker for Collada export/import issues. Some of those might have to be addressed directly at https://github.com/godotengine/collada-exporter, but since I have little experience with this I can't really judge if issues are at the export or import step.
- [x] Collada Importing Problem #507
- [x] import/export issue of scene (attached) #1077
- [x] "Triangulate" option of Better Collada Exporter not compatible with "Shape-Keys" (morph) animations. #1312
- [x] Mesh animation distortion when importing Collada (from blender export) #1316
- [x] DAE export/import problem with multimesh skeletons and meshes having shape keys #1333
- [x] Collada files import into Godot with missing geometry (OpenCollada exporter) #3357
- [x] Trimesh Static bodies generated incorrectly #3947
- [x] Importing COLLADA file with armature controlling multiple meshes causes segfault #6222
- [ ] Importer keeps -loop and -cycle suffixes in animation names but removes suffixes in nodes #6582
- [ ] The "-lod:dist" import flag does not work. #7523
- [x] (slighly unclear) 3D armature import is broken #4120
- [x] collada importer should replace . or / with another for node name #9477

**Comment by bojidar-bg** [comment]
I think you might want to add #3947, #6222, #6582, #7523, and maybe #4120

**Comment by LikeLakers2** [comment]
#6222 and #4120 are both fixed/closed.

**Comment by fire** [comment]
All the tracked issues are closed.
