### ISSUE TITLE
[TRACKER] Physics interpolation usability improvements

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#60818]
### Godot version

3.5

### System information

All

### Issue description

As a result of feedback I'm building up a list of areas that can be improved for 3.5 to make things as easy to use as possible, and to eliminate "boiler plate" jobs that can be done automatically. Let me know any other ideas so they can be discussed and possibly added to the list.

- [ ] Auto `reset_physics_interpolation` on adding children to `SceneTree`
- [ ] Option to `reset_physics_interpolation` automatically on unhiding `Nodes`
- [ ] Auto change mode to physics (or display warnings) for `Tween`
- [ ] Auto change mode to physics (or display warnings) for `AnimationPlayer`

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by lawnjelly** [comment]
> I think the Auto Change mode for AnimationPlayer is a tricky one - you can animate things that should run in physics and things that should run in process in one AnimationPlayer.

Yes this is definitely a bit tricky. Movements are interpolated so need to go in the physics tick, but many properties are not (currently) interpolated so are better changed at idle (such as colors etc).

One that I already identified in the demos was setting animation blend amounts in `AnimationTree`, which is not currently interpolated. But making any property interpolated means you need a corresponding way of resetting it, so it is a bit of a bag of worms. This is something we will have to think through carefully for Godot 4, because ideally, almost any non-binary property should be able to be interpolated, and reset.

It is possible to get around this by doing interpolation yourself manually for these properties, and that is what I did when converting 3D platformer demo.

**Comment by mieko** [comment]
> Auto change mode to physics (or display warnings) for Tween

I've definitely appreciated these warnings that are now implemented, but I think an opt-in API something like the following could be useful:

```gdscript
Tween.default_process_mode = Tween.TWEEN_PROCESS_PHYSICS
```
