### ISSUE TITLE
[TRACKER] Plugin system related issues

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6276]
This is the tracker for specific issues related to Godot plugin system:

- [ ] Get_local_mouse_pos() offset bug in the editor https://github.com/godotengine/godot/issues/1885 (bug)
- [ ] Error instancing scene as editor tool https://github.com/godotengine/godot/issues/6006 (bug) 
- [ ] Plugin reload doesn't keeps variables https://github.com/godotengine/godot/issues/5969 (bug)
- [ ] Editor not removing name from menu https://github.com/godotengine/godot/issues/5754 (bug)
- [ ] Ability to refresh editor Filesystem tree from plugin https://github.com/godotengine/godot/issues/6219 (enhancement)
- [ ] Ability for plugins to add entry under right mouse click context menu  https://github.com/godotengine/godot/issues/6128 (enhancement)
- [ ] Add a API to add/remove items to the "Tools" menu https://github.com/godotengine/godot/pull/6065 (enhancement)
- [ ] Ability to create plugin that is based on a scene https://github.com/godotengine/godot/issues/3895 (enhancement)
- [ ] No way to edit plugin.cfg in editor https://github.com/godotengine/godot/issues/5096 (enhancement)
- [ ] Plugin API feature request (text editor extensions) https://github.com/godotengine/godot/issues/3869 (enhancement)
- [ ] EditorPlugins for main editors need a way to know the "main screen" parent https://github.com/godotengine/godot/issues/5786 (enhancement)

*Couple others more wide issues*:
- [ ] *TheHX*: Suggestions for the Plugin API  https://github.com/godotengine/godot/issues/4276
- [ ] *Zatherz*: Better custom EditorPlugin nodes https://github.com/godotengine/godot/issues/6067

**Comment by SeleckyErik** [comment]
The list should be updated:
-  #9969 has been closed by #17576
-  #5096 has been closed since it's fixed in 3.1

**Comment by SeleckyErik** [comment]
Also docs should be updated, since it still states that Godot can only open script files.

http://docs.godotengine.org/en/3.0/tutorials/plugins/editor/making_plugins.html

**Comment by willnationsdev** [comment]
Docs should also be updated to showcase the new plugin creation dialog.

**Comment by MikeSchulze** [comment]
Hi any update here?
I need a way to extend the file system dock context menu to add new functionallity via plugin.
