### ISSUE TITLE
[TRACKER] TODOs in class documentation

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot#65576]
### Godot version

master branch

### System information

-

### Issue description

I randomly stumbled upon one of these documentation TODOs, and I couldn't find an issue tracking these... 

Current state of the class docs in master branch:

- [x] [Control.xml:11](https://github.com/godotengine/godot/blob/master/doc/classes/Control.xml#L11) - `[b]FIXME:[/b] No longer valid after DisplayServer split and Input refactoring.`
  - Fixed by #65424 
- [x] [Geometry2D.xml:161](https://github.com/godotengine/godot/blob/master/doc/classes/Geometry2D.xml#L161) - `// TODO: This code is not valid right now. Ping @aaronfranke about it before Godot 4.0 is out.`
  - @aaronfranke not sure if this comment still applies?
- [x] [ProjectSettings.xml:1700](https://github.com/godotengine/godot/blob/master/doc/classes/ProjectSettings.xml#L1700) - `[b]FIXME:[/b] No longer valid after DisplayServer split:`
  - Should probably be replaced by `OS.get_current_rendering_driver_name` but this method is not currently bound.
  - Fixed by #65541
- [ ] [RenderingServer.xml:3376](https://github.com/godotengine/godot/blob/master/doc/classes/RenderingServer.xml#L3376) - `FIXME: The method seems to be non-existent.`
  - Can't find any `set_attach_to_screen_rect` or related method in the current code base. Not sure what the new approach for this is.
- [ ] [SurfaceTool.xml:89](https://github.com/godotengine/godot/blob/master/doc/classes/SurfaceTool.xml#L89) - `[b]FIXME:[/b] Document possible values for [param flags], it changed in 4.0. Likely some combinations of [enum Mesh.ArrayFormat].`
  - Seems to be all `ARRAY_FLAG_*` but I can't really confirm.
  - Parameter is called `p_compress_flags` in C++, so the bound argument name might need to be updated as well?
- [x] [RenderingDevice.xml:1774-1794](https://github.com/godotengine/godot/blob/master/doc/classes/RenderingDevice.xml#L1774-L1794)
  - Needs clarification on differences between uniform types.

### Steps to reproduce

Search `*.xml` documentation files for `(TODO|FIXME)` to find them.

**Comment by atirut-w** [comment]
I ran VSCode's search tool for "TODO" and there are 1385 results across 568 files and 245 results across 151 files for "FIXME". VSCode even hung up for a moment.

How the hell did it get *this* bad?

**Comment by akien-mga** [comment]
@atirut-w This issue is about the class documentation so you should filter on `*.xml` only.

Other TODOs in code can be there for a variety of reasons, quite often as a hint for future self or future contributors that things could be improved in terms of code quality/performance. It's not particularly "bad" as you point it out, it's one aspect of code documentation to be able to point out what could be improved even if it's not critical to do it at a given point in time. In other cases, it does point at missing features / bugs that need to be solved, and those cases can be worth tracking in dedicated issues.

Finally, you should exclude thirdparty code when you search, we don't care about other projects' internal hints for future potential work.

```
$ rg "TODO" | wc -l
1374
$ rg "TODO" -g'!thirdparty' | wc -l
510
```
