### ISSUE TITLE
[TRACKER] 4.0 OpenGL renderer issues

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#66458]
### Godot version

x

### System information

x

### Issue description

- [ ] https://github.com/godotengine/godot/issues/58927
- [ ] https://github.com/godotengine/godot/issues/65702
- [ ] https://github.com/godotengine/godot/issues/65977
- [ ] https://github.com/godotengine/godot/issues/66455
- [ ] https://github.com/godotengine/godot/issues/66456
- [ ] https://github.com/godotengine/godot/issues/66457

### Steps to reproduce

x

### Minimal reproduction project

This issue tracks issues specific to the OpenGL renderer **in Godot 4**. Godot 3 issues are not tracked here.

See also https://github.com/godotengine/godot/issues/55871, which is specific to Vulkan Mobile-only issues.

**Comment by acedogblast** [comment]
Missing issue #71799.

**Comment by mrjustaguy** [comment]
Says Projectors, Reflection Probes and Lightmaps are not supported but planned in warnings but not here

**Comment by mrjustaguy** [comment]
also https://github.com/godotengine/godot/issues/83313

**Comment by TokisanGames** [comment]
How about adding the standard OpenGLES integer texture formats, since they are supported by hardware, the RenderingDevice, and shaders? Since we don't have buffers, textures are the only options, and floats are cumbersome and wasteful to work with when you want bit-packed integer based data blocks or control maps without texture filtering or float conversion.

**Comment by Lasuch69** [comment]
@Calinou could you please include reflection probes in missing features. Thanks in advance! :) 

https://github.com/godotengine/godot/issues/86318

**Comment by Chaosus** [comment]
@Lasuch69 I've fixed it (not sure why tags are not rendered).

**Comment by mrjustaguy** [comment]
New issue to add - Compatibility Positional Shadows assigning wrong Shadow maps - https://github.com/godotengine/godot/issues/92486
