### ISSUE TITLE
[TRACKER] Vulkan ReflectionProbe issues

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#66628]
### Godot version

s

### System information

s

### Issue description

s

### Steps to reproduce

This is a tracker issue for reflection probes in the `master` branch. See https://github.com/godotengine/godot/issues/55328 for VoxelGI issues and https://github.com/godotengine/godot/issues/55327 for SDFGI issues. See https://github.com/godotengine/godot/issues/56080 for issues specific to the CPU-based BakedLightmap in `3.x`.

**This tracker only tracks issues in the `master` branch** (what will become 4.0 in the future), not `3.x`.

### Bugs

- [ ] https://github.com/godotengine/godot/issues/38442
- [ ] https://github.com/godotengine/godot/issues/49117
- [ ] https://github.com/godotengine/godot/issues/50751
- [ ] https://github.com/godotengine/godot/issues/56635
- [ ] https://github.com/godotengine/godot/issues/56657
- [ ] https://github.com/godotengine/godot/issues/60019
- [ ] https://github.com/godotengine/godot/issues/64683
- [ ] https://github.com/godotengine/godot/issues/65690
- [ ] https://github.com/godotengine/godot/issues/66624

### Enhancements

- [ ] https://github.com/godotengine/godot/issues/54449

### Pull requests

- [ ] https://github.com/godotengine/godot/pull/55929

**Comment by mrjustaguy** [comment]
https://github.com/godotengine/godot/issues/50195 is missing

**Comment by myaaaaaaaaa** [comment]
Should godotengine/godot-proposals#6180 be tracked here?
