### ISSUE TITLE
[TRACKER] Vulkan temporal antialiasing (TAA) issues

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#69494]
### Godot version

x

### System information

x

### Issue description

This issue tracks issues related to temporal antialiasing (TAA) in the Godot 4 Vulkan renderer.

### Bugs

- [x] https://github.com/godotengine/godot/issues/65479
- [ ] https://github.com/godotengine/godot/issues/69492
- [ ] https://github.com/godotengine/godot/issues/69493

### Steps to reproduce

x

### Minimal reproduction project

x

**Comment by mrjustaguy** [comment]
https://github.com/godotengine/godot/issues/104622 should be added to this list (affects both FSR and TAA)
