### ISSUE TITLE
[TRACKER] Vulkan fog and volumetric fog issues

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#69579]
### Godot version

x

### System information

x

### Issue description

This issue tracks issues related to standard (non-volumetric) fog in the Vulkan and OpenGL renderers, as well as volumetric fog in the Vulkan Clustered backend.

### Bugs

- [ ] https://github.com/godotengine/godot/issues/44466
- [ ] https://github.com/godotengine/godot/issues/54496
- [ ] https://github.com/godotengine/godot/issues/54893
- [ ] https://github.com/godotengine/godot/issues/55870
- [ ] https://github.com/godotengine/godot/issues/59262
- [ ] https://github.com/godotengine/godot/issues/61222
- [ ] https://github.com/godotengine/godot/issues/62794
- [ ] https://github.com/godotengine/godot/issues/63739
- [ ] https://github.com/godotengine/godot/issues/64634
- [ ] https://github.com/godotengine/godot/issues/66456
- [ ] https://github.com/godotengine/godot/issues/66459
- [ ] https://github.com/godotengine/godot/issues/66462
- [ ] https://github.com/godotengine/godot/issues/66934
- [ ] https://github.com/godotengine/godot/issues/69565

### Discussions

- [ ] https://github.com/godotengine/godot/issues/56374

### Enhancements

- [ ] https://github.com/godotengine/godot-proposals/issues/1698
- [ ] https://github.com/godotengine/godot-proposals/issues/2643
- [ ] https://github.com/godotengine/godot-proposals/issues/3429
- [ ] https://github.com/godotengine/godot-proposals/issues/4619
- [ ] https://github.com/godotengine/godot-proposals/issues/5079
- [ ] https://github.com/godotengine/godot-proposals/issues/5214

### Steps to reproduce

x

### Minimal reproduction project

x
