### ISSUE TITLE
[TRACKER] OpenXR in Godot 4

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#69647]
### Godot version

4.0 dev (f3e6750a7e4702918e05f42b1376e30e652f2f90)

### System information

Any

### Issue description

We've identified several outstanding issues with OpenXR. Just raising this issue to keep track of them.

# Core features

- [x] VRS being made available even when not supported #69091
- [ ] Query OpenXR for a density map once supported

# Extensions

- [ ] add support for various composition layers (as extra (2D) Viewports rendering to XRSwapChains)
- [ ] add support for Dpad bindings in Action map: https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#XR_EXT_dpad_binding
- [ ] Port performance settings extension from Godot 3 plugin: https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#XR_EXT_performance_settings
- [ ] Implement render models API once core version becomes available

# Depth buffer

OpenXR allows supplying the depth buffer, the XR runtime can use this information to perform more accurate re-projection when framerates are not met. On Quest the depth buffer can be combined with a motion vector buffer to enable application spacewarp, a more advanced version of re-projection. Motion vector support is not yet available on the mobile renderer but solving the issues already found will be paramount to solving this.

- [ ] Left eye depth buffer is supplied for the right eye
- [ ] Mobile renderer is not resolving MSAA depth buffer to final depth buffer
- [ ] Clustered renderer fails to resolve MSAA depth buffer to final depth buffer if compute shaders are used, it's not possible to set the `VK_IMAGE_USAGE_STORAGE_BIT`

# Vulkan specific

# OpenGL specific

- [ ] Image flip issue when presenting preview image on desktop #69581

# DX12 specific

# Misc

### Steps to reproduce

.

### Minimal reproduction project

.

**Comment by RadixSeven** [comment]
The two issues linked in the "Depth Buffer" section are marked as merged, and the "Submit Depth Buffer" checkbox exists in 4.0.1.stable. Should the "Depth Buffer" section of this issue be checked off? It looks like we can also check off #68469, #65864, and #62738 under "core features".

**Comment by BastiaanOlij** [comment]
@RadixSeven there were still a few issues with this. #78550 fixes a major issue, I'm still looking into a few resolve issues when MSAA is being used.
