### ISSUE TITLE
[TRACKER] Raster occlusion culling issues

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#70533]
### Godot version

s

### System information

s

### Issue description

This tracker issue tracks issues related to *raster* occlusion culling (the kind of Embree-based occlusion culling used in 4.0). It does not track issues related to portals and rooms occlusion culling, or geometry occlusion culling featured in 3.x.

### Bugs

- [ ] https://github.com/godotengine/godot/issues/53288
- [ ] https://github.com/godotengine/godot/issues/63771
- [ ] https://github.com/godotengine/godot/issues/70373
- [ ] https://github.com/godotengine/godot/issues/70375
- [ ] https://github.com/godotengine/godot/issues/70516

### Enhancements

- [ ] https://github.com/godotengine/godot/issues/50154
- [ ]

### Steps to reproduce

s

### Minimal reproduction project

s
