### ISSUE TITLE
[TRACKER] HiDPI-related issues

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#7295]
This is a tracker of issues related to displays with high DPI values.

- [x] Very small project manager window size on hiDPI displays (https://github.com/godotengine/godot/issues/8543)
- [x] More DPI scaling options should be available (https://github.com/godotengine/godot/issues/7293)
- [x] Add a new vector-based default editor theme (https://github.com/godotengine/godot/issues/7294)
- [x] HighDPI mode is scaling too much on high resolution display (Windows) (https://github.com/godotengine/godot/issues/6601)
- [x] HiDPI automatically used on FullHD screens, makes the UI too big (https://github.com/godotengine/godot/issues/6096)
- [x] HiDPI Screen option on Low DPI screen will break UI (https://github.com/godotengine/godot/issues/6130)
- [x] Documentation to support HIDPI in project (https://github.com/godotengine/godot/issues/5916)

**Comment by toger5** [comment]
@Calinou a lot of those issues are fixed. (1. 2. 3. are at least pretty good now)

**Comment by Anutrix** [comment]
#6130 is closed.

**Comment by Calinou** [comment]
I'll close this tracker since all issues on it have been solved.
