### ISSUE TITLE
[TRACKER] Navigation test plan

### ISSUE THREAD

**Issue by Scony** [godotengine/godot#73132]
### Godot version

master latest

### System information

N/A

### Issue description

In the upcoming weeks, I'm going to work on test cases for the navigation area. I'm going to use this issue as a progress tracker but also as a place where anyone can propose scenarios to implement.

Please note that many scenarios will be tested in 3D only since quite a lot of navigation code is common for 2D and 3D so we don't need to duplicate test cases in many instances.

# Server tests

## `NavigationServer3D`

- [ ] Server should be empty when initialized - checking if the internal state of server is correct after initialization
- [ ] (...)

## `NavigationServer2D`

- [ ] Server should be empty when initialized - checking if the internal state of server is correct after initialization
- [ ] (...)

# Node tests

`NavigationAgent3D`
--------------------------------

- [ ] New agent should have valid RID
- [ ] New agent should attach to default map
- [ ] (...)

`NavigationAgent2D`
--------------------------------

- [ ] New agent should have valid RID
- [ ] New agent should attach to default map
- [ ] (...)

# PRs

- https://github.com/godotengine/godot/pull/73121

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by smix8** [comment]
Looking for navigation related benchmark ideas.

Benchmark ideas are written in format like this:
TYPE: [Groups it Belongs]: Name: Description

Examples:
- Exclusive:AStar3D: Create random map with 1000 inter connected points (probably using Delaunay3D), Benchmark solving it 1000 times from random 2 points
- Exclusive:Navigation:  On a premade map, solve 1000 random paths between two points on the surface of the shapes. 
- Agents: Benchmark 1000 moving agents in a map with local collision avoidance.

**Comment by Scony** [comment]
> Looking for navigation related benchmark ideas.
> 
> Benchmark ideas are written in format like this: TYPE: [Groups it Belongs]: Name: Description
> 
> Examples:
> 
> * Exclusive:AStar3D: Create random map with 1000 inter connected points (probably using Delaunay3D), Benchmark solving it 1000 times from random 2 points
> * Exclusive:Navigation:  On a premade map, solve 1000 random paths between two points on the surface of the shapes.
> * Agents: Benchmark 1000 moving agents in a map with local collision avoidance.

Some more examples to consider:

- Exclusive:Navigation[Agents]: Benchmark 10 maps with 100 moving agents each and with local collision avoidance.
- Exclusive:Navigation[Agents]: Benchmark 100 maps with 10 moving agents each and with local collision avoidance.
- Exclusive:Navigation[Agents]: Benchmark 1000 moving agents in a map with local collision avoidance and with 100 triangular, static obstacles spread across the map.
- Exclusive:Navigation[Agents/Queries]: Benchmark 1000 moving agents in a map with local collision avoidance while changing desired location (path recalculation) for 100 of them every second for 10 seconds.

**Comment by maityyy** [comment]
Still actual?
