### ISSUE TITLE
[TRACKER] StateMachines/SubStateMachine is not working correctly

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#73534]
### Issue description

This is a tracker for problems with mainly nested StateMachines not behaving as expected.

May be solved by:
- https://github.com/godotengine/godot-proposals/issues/6130

```[tasklist]
- [ ] https://github.com/godotengine/godot/issues/68986
- [ ] https://github.com/godotengine/godot/issues/71562
- [ ] https://github.com/godotengine/godot/issues/62576
- [ ] https://github.com/godotengine/godot/issues/69063
- [ ] https://github.com/godotengine/godot/issues/58822
- [ ] https://github.com/godotengine/godot/issues/73643
- [ ] https://github.com/godotengine/godot/issues/73648
- [ ] https://github.com/godotengine/godot/issues/57223
- [ ] https://github.com/godotengine/godot/issues/45635
- [ ] https://github.com/godotengine/godot/issues/51408
- [ ] https://github.com/godotengine/godot/issues/74752
```

If there is anything else, please comment.

**Comment by thiolliere** [comment]
related https://github.com/godotengine/godot/issues/74752

**Comment by TokageItLab** [comment]
Completed!
