### ISSUE TITLE
[TRACKER] Blending with AnimationPlayer is not working correctly

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#73537]
### Godot version

4.0

### System information

Any

### Issue description

This is a tracker for a problem with AnimationPlayer blending not working as expected.

May be fixed by:
- https://github.com/godotengine/godot-proposals/issues/5972

List:
- [ ] https://github.com/godotengine/godot/issues/70207
- [ ] https://github.com/godotengine/godot/issues/72484
- [ ] https://github.com/godotengine/godot/issues/50280
- [ ] https://github.com/godotengine/godot/issues/36279
- [ ] https://github.com/godotengine/godot/issues/27509
- [ ] https://github.com/godotengine/godot/issues/70123

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by narren96c** [comment]
#76127 is related.

**Comment by TokageItLab** [comment]
The most major issues have been resolved, but some of the rest will need a bit major fixes for minor updates, so I would punt them to 4.3.

**Comment by bertodelrio256** [comment]
I'm using 4.3 and noticed intermittently the custom blend time when calling .play() is ignored/defaulted. weird thing is I tried to create an MRP calling .play() at different times with different blend times, but it seemed to work fine so I canceled the issue. but in my production project, I'm seeing some blends just being ignored while others work fine. perhaps I'm not understanding how it works.. my assumption is the if I call .play("anim1",  0.3f) in process and then called .play("anim2",  3.0f) it should take 3 seconds to blend to that one right? I'm making many calls to animations before they finish with different blend times, could that be causing the issue? does the blend need to be reset somehow first?

**Comment by bertodelrio256** [comment]
> > I'm making many calls to animations before they finish with different blend times
> 
> @bertodelrio256 If you are calling the same animation many time before finish blending, I assume there is some problem, related #72484.

ahh interesting. So a queue is filled when calling multiple. I think my issue could be resolved perhaps by only doing one call to .play() per physics tick and just have my states just change the string that it uses one that one call. 

anyway looking forward to what you come up with in the new blending system. I hate using animation trees. honestly being able to everything in code would be a dream.

**Comment by bertodelrio256** [comment]
I just wanted to mention that I was able to resolve all of the blending issues by only calling .play once if the animation changed. looks like you cannot call .play every frame or the blends wont work...

```cs
if(anim_player.AssignedAnimation != current_clip)
		{
			anim_player.Play(current_clip, current_clip_blend);
		}
		```
