### ISSUE TITLE
[TRACKER] Navigation Roadmap

### ISSUE THREAD

**Issue by DarkKilauea** [godotengine/godot#73566]
### Godot version

4.x

### System information

N/A

### Issue description

Here is a list of the major items the navigation team is aiming to tackle in the 4.x time frame.  It will not contain every issue we plan to fix or enhancement we want to add, but is intended to communicate major changes and reworks we have planned.

### 4.1

- [ ] #70724 
- [ ] #69988

### 4.x

- [ ] https://github.com/godotengine/godot-proposals/issues/5635
- [ ] https://github.com/godotengine/godot-proposals/issues/5542
- [ ] #66891
- [ ] #69881

Anything in the 4.x bucket may be moved up to 4.1 the work is completed and accepted in time.

Plans are subject to change, please let us know if there is something major that you see missing from the list.  Please make sure that you have an open proposal for any such changes.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Scony** [comment]
Minor TODO: https://github.com/godotengine/godot/pull/79485#discussion_r1264402385

**Comment by MJacred** [comment]
Something major missing: https://github.com/godotengine/godot-proposals/issues/5116

**Comment by Scony** [comment]
TODO: Replacing `NavigationRegion[23]D::bake_navigation_mesh(false)` with `NavigationServer3D.parse_source_geometry_data` and `NavigationServer3D.bake_from_source_geometry_data` requires extra `NavigationServer3D.region_set_navigation_mesh` call in order to sync up changes - that should be unified.

**Comment by Scony** [comment]
TODO: Adding `append=false` parameter to `NavigationServer3D.parse_source_geometry_data()` so that data can be appended to existing geometry resource

**Comment by Scony** [comment]
- [ ] https://github.com/godotengine/godot/pull/89034#discussion_r1518555324

**Comment by Scony** [comment]
- [ ] https://github.com/godotengine/godot/pull/85965#issuecomment-2323355234
