### ISSUE TITLE
API refactorings for 3.0 -- continued

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#7516]
List of things that were forgotten / overlooked in #5696 and #6523, and should either be changed or disagreed with:

## Confusing names

- [x] Input.get_mouse_speed() returns the speed of the last non-null mouse motion, not the current one. It could be renamed to Input.get_last_mouse_speed() or similar.
- [x] Tween.set_speed() is confusing as it returns a scale, could be renamed to set_speed_scale() (#2060) Same with the property (#6935).
- [x] OS.get_ticks_msec() => should be named get_time_msec(), the name makes it hard to find it (it was for me) because no one would search for tick to get the current ms-precise time. (@Zylann)
- [x] Why File.get/store_***(content) instead of File.read/write_***(content) as any other I/O API? (@Zylann)
- [x] Vector2::get_aspect should probably become Vector2::aspect, since none of the other methods in the class have the get_ prefix. (@bojidar-bg)
- [x] set_send_address should be set_destination_address. When I first saw this function I thought I will be able to set packet origin IP/Port (so I can later listen on that port - I'm trying to do UDP hole punching). Sadly it's something different. (@Marqin)
- [x] rotation setters and getters must be standarized:, currently there are many variations like: set_rot, set_rotation, set_rotation_deg, set_rotationd, set_rotd (@djrm)
- [x] In String we have `get_base_dir()` `get_file()`. Why not the same with `basename() -> get_basename()` `extension() -> get_extension()` (@AlexHolly)
- [x] set_enable_monitoring( bool enable ) to set_monitoring( bool enable ) (@jtaart)
- [x] Rename `rang_range` to `randi_range` and add `randf_range`, to match `randi` and `randf` (#6235)

## Functions to change

- [x] DirAccess::list_dir_begin should return Error like other functions of this kind.
- [x] SceneTree.call_group() (and notify_group()) requires flags as the first argument, which pretty much just results in many zeros in the code, I'd suggest an alternative call_group_flags() or something to mitigate this, and remove the flags argument from call_group(). (@WalasPrime)

## Functions to remove

- [x] OS.set_video_mode() (https://github.com/godotengine/godot/issues/3778#issuecomment-233447010).
- [x] OS.get_fullscreen_mode_list() (https://github.com/godotengine/godot/pull/4624#issuecomment-218515473).

## Properties to remove

- [x] Expand from TextureFrame. The Strech Mode property is much more flexible and can do some things that already override the Expand settings.

## Bug

- [x] Many nodes override inherited methods, which makes the said methods uncallable from GDScript.
Here is a small list: Viewport::get_viewport, CanvasItem::get_viewport, EditorPlugin::get_name (@bojidar-bg)

## Refactoring

- [x] Add proper support for static methods like `File.file_exists()` instead of `File.new().file_exists()`

#### Constants in global scope that could be namespaced

Some constants have redundant naming, for example in VisibilityEnabler2D, all identifiers have the ENABLER_ prefix, but it seem useless since they already are scoped in the class.
On the opposite side, there are a lot of consts that are outside of any class, and it can be confusing. For example, the first time I looked for button codes I was trying to get them from Input, or InputEvent, to no avail. So I eventually used the raw numbers, to finally find they are in global scope like KEY_A or BUTTON_LEFT. (@Zylann)

**Comment by reduz** [comment]
Ticks is generally used for this, as it means the time it passed since application started.

SDL uses the same nomenclature:

https://wiki.libsdl.org/SDL_GetTicks

**Comment by reduz** [comment]
rotations/setters/getters/etc for that stuff has already been fixed

**Comment by reduz** [comment]
randi_range does not make much sense because of the integer limit, I would probably leave it as is

**Comment by reduz** [comment]
I would leave file ops as they are, read/write are generally socket functions. I don't think it's worth changing them just for the sake of it.

**Comment by Zylann** [comment]
@reduz, I don't know other framework naming the current time `ticks`. Unity uses `timeSinceStartup`, Java `currentTimeMillis()`, C# `DateTime.Now.Millisecond`, and it's still hard to find it by typing "time" in the built-in search.

**Comment by reduz** [comment]
| Add proper support for static methods like File.file_exists() instead of File.new().file_exists()

Undoable, as there is no support for static methods in GDScript

**Comment by reduz** [comment]
| Expand from TextureFrame. The Strech Mode property is much more flexible and can do some things that already override the Expand settings.

I have no idea what this means

**Comment by akien-mga** [comment]
@reduz Pro-top: Use `>` in front of quoted paragraphs to get them formatted as quoted text.

> Like that.

:)

**Comment by bojidar-bg** [comment]
@reduz About the static methods, it would be really nice if we actually add support for them in GDScript (one can make static methods in GDScript, but cannot make them in C++? :laughing: )

**Comment by reduz** [comment]
TADA! Complete.

**Comment by reduz** [comment]
static methods in base classes is considerable work, and there are too few of them to make it worth it, maybe for future versions

**Comment by toger5** [comment]
don't know if it's already to late...
``` gdScript
void	add_color_override ( String name, Color color )
void	add_constant_override ( String name, int constant )
void	add_font_override ( String name, Font font )
void	add_icon_override ( String name, Texture texture )
void	add_shader_override ( String name, Shader shader )```
I was searching much too long today. went through a lot of source code and searched for` set_` ...

so:
```gdScript
void	set_constant_override ( String name, int constant )
```
would be much better for me

**Comment by toger5** [comment]
Why Color8 & ColorN in GDScript ?
if there are Color constructors
