### ISSUE TITLE
[Tracker] Validation layer errors

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#78497]
### Godot version

Current master (329652b)

### System information

All systems when using Vulkan-based backends

### Issue description

I am opening this issue report to keep track of various validation layer reports in one place. 

I have a strong feeling that resolving the validation layer errors we get currently will either resolve or help us resolve https://github.com/godotengine/godot/issues/71929
```[tasklist]
- [ ] https://github.com/godotengine/godot/issues/66857
- [ ] https://github.com/godotengine/godot/issues/54541
- [ ] https://github.com/godotengine/godot/issues/54540
- [ ] https://github.com/godotengine/godot/issues/54539
- [ ] https://github.com/godotengine/godot/issues/54538
- [ ] https://github.com/godotengine/godot/issues/54537
- [ ] https://github.com/godotengine/godot/issues/54535
```

### Steps to reproduce

Run the engine with validation layers enabled. 

To reproduce all the reports ensure that you use the "Vulkan Configurator" (comes with the SDK) to enable all validation layers

### Minimal reproduction project

N/A - see individual reports
