### ISSUE TITLE
[TRACKER] ModificationStack2D issues

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#78600]
### Godot version

any

### System information

any

### Issue description

- [ ] https://github.com/godotengine/godot/issues/75820
- [ ] https://github.com/godotengine/godot/issues/75337
- [ ] https://github.com/godotengine/godot/issues/75224
- [ ] https://github.com/godotengine/godot/issues/73888
- [ ] https://github.com/godotengine/godot/issues/73242

### Steps to reproduce

tracker

### Minimal reproduction project

tracker
