### ISSUE TITLE
[TRACKER] Better integration into OSX

### ISSUE THREAD

**Issue by CoalaJoe** [godotengine/godot#7884]
**Operating system or device - Godot version:**
OSX - 2.1.2

**Issue description:**
- [x] Smooth or normal scrolling (currently scrolls too fast in script-editor)
- [x] Pinch to zoom in 2D and 3D.
- [x] Hi-DPI Logo of Godot. (Very visible when switching between applications. cmd+tab)
- [ ] Basic keyboard-shortcut.

**Comment by toger5** [comment]
see:
 - implemented scrolling factor for precision trackpads #7864

I'm currently also thinking about the Input handling in Godot in general and have a couple of ideas to make a clean implementation for touch screens and trackpads. 
I will do a mockup this weekend and will propose it to the devs. maybe I will implement it than.

**Comment by toger5** [comment]
here is the mockup 
## [GoogeDocs](https://docs.google.com/document/d/1kaGrSedZ9S2UThjvGIPYonRCivsBDm_KvUAEb-zdVp4/edit?usp=sharing)

**Comment by CoalaJoe** [comment]
:+1:

**Comment by FuzzyRhombus** [comment]
May I also propose:

- Support trackpad 3 finger click as middle mouse button (i.e for panning in 2D)
> I like the pinch to zoom as well, assuming scroll would then be used for scrolling the view (panning). Maybe both should be supported with an option
- Send scroll events to appropriate panel without focus
> On native OSX applications, scrolling events propagate regardless of window focus. For example, if I want to scroll the `Inspector` panel when focused on another app, I have to focus Godot, then click that panel to focus *within* Godot, then I can scroll
- Open settings using native (or assignable) shortcut (**⌘,**)

----
I realize the inactive scrolling is a bigger task, but I feel it is something that should be supported at some point

**Comment by alvaromunoz** [comment]
Can confirm latest 2.1.4 beta fixes "Smooth or normal scrolling (currently scrolls too fast in script-editor)"

**Comment by toger5** [comment]
Also the logo is fixed in 3.0

**Comment by zinkkrysty** [comment]
Could I suggest one thing for this list:

- [ ] On OS X, scrolling using touch bar while holding CMD key is zooming the editor font and it is too sensitive

Now, that wouldn't be bad in itself if implemented properly. However I find myself triggering it by mistake so many times, like so:
1. I scroll using touch bar. I release the touch bar, but the window is still scrolling (because of inertia)
2. I press CMD (because I want to press CMD+Tab) while the window is still scrolling from the inertia, and the font gets huge.

![godot3_mac_scrolling_font_zooming_bug](https://user-images.githubusercontent.com/570771/29941387-b328754a-8e92-11e7-8abd-7e086f167d2a.gif)

I am using Godot 3 built from master.

**Comment by jonathanhirz** [comment]
Since there's already a topic on OS X improvements, could there be a way to a way to flip the x and y scrolling in 3D when using the trackpad? I noticed this option in Blender today, called "Natural Trackpad Scrolling" if you want to see what I mean.

**Comment by eduardonunesp** [comment]
Just tested the following item and it is working as expected:

- [x] Pinch to zoom in 2D and 3D.

Tested on `mac OS 10.15.4`

**Comment by eduardonunesp** [comment]
This one will be nice to have:
 - [ ] Open settings using native (or assignable) shortcut (⌘,) (Suggested initially by @FuzzyRhombus)

**Comment by bruvzg** [comment]
> Open settings using native (or assignable) shortcut (⌘,) (Suggested initially by @FuzzyRhombus)

It's already include into global menu PR - https://github.com/godotengine/godot/pull/38044

**Comment by akien-mga** [comment]
I think this can now be closed as most of the points have been implemented.

For the remaining ones, I would suggest to open a feature proposal for each point on [godot-proposals](https://github.com/godotengine/godot-proposals).
