### ISSUE TITLE
[TRACKER] 3.0 Import system issues

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#8000]
This is a tracker issue for the import system bugs, so they don't go unnoticed. (some of them might need to be retested for 3.0)

- [x] #3872 - Looping samples is a bit unintuitive currently (closed as obsolete)
- [x] #4816 - Imported materials' colors are not corrected
- [x] #5640 - .csv chokes on CRLF/windows-1251
- [x] #5990 - (probably invalid) Custom plugins used for importing get stuck into reimport loop sometimes
- [x] #6509 - PNG flags might need to be tristate - on/off/default, or be always saved
- [x] #7175 - Post-import scripts are not executed properly
- [x] #7755 - Audio import errors out on 96KHz samples
- [x] #8075 - .dae not applying material on import
- [x] #9267 - Normal Maps do not import correctly
- [x] #9939 - Normals artifacting issue on collada exported models
- [x] #10017 - Reimport 3D models doesn't update assets in opened scene
- [x] #10038 - Deleting an asset/resource should remove imports & related files as well 
- [x] #10070 - Importing some textures crashes Godot 3
- [x] #11557 - glTF importer fails to import models with armatures
- [ ] #10132 - gltf importer doesn't support hinting through node names
- [x] #10742 - gltf importer fails to import textures
- [x] #10780 - glTF import crashes when importing models with cameras
- [x] #11452 - Default material import settings don't work as expected
- [x] #14636 - glTF import bug
- [x] #14725 - GLTF file fails to import correctly
- [ ] #17848 - Cannot import resources outside of res:// (e.g. from user://)

And here are some discussions about what the new system might have:

- [x] #7408 - Where it all started
- [x] #4826 - .svg vector graphics import
- [x] #6339 - Support non-csv translation formats
- [ ] #7883 - .blend files direct import (via assimp)
- [x] #7952 - glTF format import (export?)

**Comment by bojidar-bg** [comment]
Ok, here is one more: (also, updated the list, for email subscribers..)

- [ ] #8000 - A list of various bugs about the import system (please, do not check unless it is closed)

Finally, when all the above issues are checked, we can close this one.

**Comment by kubecz3k** [comment]
Next one I think:
- [ ] #10017 - Reimport 3D models doesn't update assets in opened scene

**Comment by toger5** [comment]
- [ ] #9267 - Normal Maps do not import correctly

**Comment by LikeLakers2** [comment]
#9939, #10017, #10070, #10130, #10742, and #10780 are all fixed/closed.

**Comment by NathanWarden** [comment]
You may want to add this one to the list. https://github.com/godotengine/godot/issues/11452

**Comment by tagcup** [comment]
#10130 was closed without being actually fixed and #11557 is the new issue

**Comment by tagcup** [comment]
Also #10132

**Comment by Overblob** [comment]
A couple more for Wavefront formats:
#17759 - Obj importer is broken 
#13978 - FileSystem cache error when importing an OBJ file

**Comment by aaronfranke** [comment]
The rest of the issues in the OP are missing features, not bugs, and likely won't be solved in time for 3.2. The only bugs here are from @Overblob's comment which links two more issues. Consider either adding those issues to the OP and/or bumping this tracker (+ #17848) to the 4.0 milestone

> Ok, here is one more: (also, updated the list, for email subscribers..)
> - [ ] #8000 - A list of various bugs about the import system (please, do not check unless it is closed)

Why are you linking this issue to itself? This is already #8000

**Comment by bojidar-bg** [comment]
> Why are you linking this issue to itself?

It was supposed to be a joke, but, man, did it take a long time for someone to notice?

**Comment by akien-mga** [comment]
Almost everything is fixed in this tracker, so closing.
