### ISSUE TITLE
[TRACKER] AnimationMixer brings latent bugs from the old AnimationTree into AnimationPlayer

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#83401]
### Godot version

4.2.beta1

### System information

Any

### Issue description

```[tasklist]
- [ ] https://github.com/godotengine/godot/issues/83166
- [ ] https://github.com/godotengine/godot/issues/85088
- [ ] https://github.com/godotengine/godot/issues/85571
- [ ] https://github.com/godotengine/godot/issues/73342
- [ ] #84106
- [ ] https://github.com/godotengine/godot/issues/84612
```

**Comment by darthstelz** [comment]
On upgrading project to 4.2 beta I'm getting tons of these errors on all my animations. 

![image](https://github.com/godotengine/godot/assets/147906517/7d568042-7469-4ba0-8ef5-5fffd7616e38)

**Comment by TokageItLab** [comment]
@darthstelz That's will be fixed by https://github.com/godotengine/godot/pull/83417

**Comment by TokageItLab** [comment]
@darthstelz I forwarded it to https://github.com/godotengine/godot/issues/83418, as it seems to be an issue unrelated to this tracker.
