### ISSUE TITLE
[TRACKER] Collision Shape issues for 3.0

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#8811]
This issue tracks improvements, bugs and compatibility breaks related with Collision Shapes and Godot 3.x

- [x] Rigidbodies in linked scenes use linked collision shapes, even if the collision shape is changed in the parent scene #9105
- [x] CollisionShapes cannot be rotated #8153 
- [x] Collision shapes overridden in inherited scenes are not used by physics, but display fine. #8103
- [x] Godot 3.0 Collisions Shapes (CollisionShape2D / CollisionPolygon2D) dont get drawn on the editor or debug, except RectangleShape2D, RayShape2D or LineShape2D #8033
- [x] Shape2D added to CollisionObject2D do not appear with Visual Collision enabled. #7281
- [x] Collision shapes are drawn in wrong color and collision contact points are not drawn at all #8607
- [x] Add one-way collision to tile-set/tile-map (2.1) #8558
- [x] Collision shape gizmo isn't updated upon changing the shape #8910
- [x] User imported 3D Collision Shapes only interact with primitives and not each other #4591
- [x] Physic Body Instanced scene doesn't use CollisionShapes #2314
- [x] CollisionShape2D does not exist at run-time after reparent/duplication #1183
- [x] Trimesh Static bodies generated incorrectly #3947
- [x] Poor optimizations in the physics engine #7690
- [x] Instanced CollisionPolygon2D's cannot perform collision detection #8896
- [ ] Error 3D physics, violation collision mesh RigidBody and other body #4831
- [ ] Collision with edges between convex/planar face pair #7701
- [x] Collision shapes persist after they've been deleted #7693
- [x] Buggy collision detection when ConvexPolygonShape2D is given a concave polygon with set_points() #8611
- [x] Convex collision shapes + kinematic body + look_at + move = cpu catches fire #8750 (unconfirmed)
- [ ] Bad collision against StaticBody2D with LineShape2D #7920
- [ ] CollisionShape2D trigger doesn't behave as expected #4393
- [ ] "Create convex static body/collision sibling" freezes the editor if used on sphere mesh #21141

**Improvements / Suggestions**

- [x] Scaled RigidBody should show a node warning in the scene tree as it's something that should not be done #7615
- [ ] "Collision Groups" handling Collision Layers & Masks #7793
- [ ] Expose collision resolution bias in editor for rigid bodies/collision shapes #7700
- [x] Attaching CollisionShapes to bones #8318
- [ ] Shape Colision Editor Suggestions #8227

**Comment by nunodonato** [comment]
@eon-s added in, thanks!

**Comment by Einlander** [comment]
Does godot 3 still ignore scaled collision shapes?

**Comment by DimitriyPS** [comment]
More on topic:
https://github.com/godotengine/godot/issues/4831
https://github.com/godotengine/godot/issues/4591

**Comment by nunodonato** [comment]
@DimitriyPS added, thanks!

**Comment by eon-s** [comment]
Tested #7644 , affects 3 too.

**Comment by nunodonato** [comment]
@eon-s, @akien-mga asked to keep this tracker focused specifically on CollisionShapes and not collisions in general, so I guess that one doesn't qualify :)

**Comment by LikeLakers2** [comment]
#9105, #8153, #8103, #7281, #8607, #8558, #8910, #4591, #2314, and #1183 are all fixed/closed. (This list is in the same order as they're listed in the tracker.)

**Comment by Einlander** [comment]
There is also this one. https://github.com/godotengine/godot/issues/3947

**Comment by gururise** [comment]
Another collision bug #13835

**Comment by LinuxUserGD** [comment]
possible #12521

**Comment by LinuxUserGD** [comment]
#4831 is Godot 2.1.3

**Comment by Chaosus** [comment]
Added #21141

**Comment by williamd1k0** [comment]
I just found this one #14599

**Comment by eon-s** [comment]
This may need to be closed and make a new one for 3.1 and 3.2/4.0

**Comment by Chaosus** [comment]
@eon-s It could be simply renamed

**Comment by Chaosus** [comment]
Sorry, my mind is a bit chaotic today )

**Comment by Chaosus** [comment]
I recreated this list here (for better visibility) - #24816 - all fixed issues are removed + re-targeted to 3.2
