### ISSUE TITLE
[TRACKER] Typos and UI Paper Cuts

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot#91521]
### Tested versions

N/A

### System information

N/A

### Issue description

As per https://github.com/godotengine/godot-proposals/issues/9648, this issue tracks tiny issues which can easily be fixed and are not opinionated changes. This includes:

- A misspelling in the user interface or class reference
- A misspelling in the code (comment, variable name, class name, etc. as long as it is not a breaking change)
- Adding or tweaking the property hint of a property
- Giving names to unnamed method arguments

It does NOT include any functional changes, such as refactoring or reordering code.
Purpose of tracking these is NOT for users to make PRs for fixing them directly, but rather:

1. For maintainers to periodically fix all of the listed issues in larger batches, instead of doing small PRs for individual issues.
2. For contributors that are already touching code near a known issue, to fix it while they're at it.

A task list is used to keep track of how many issues there are, but you can simply remove the bullet points when done instead of checking them, to keep this tracker clean and re-usable.

# Issues

- [ ] `editor/plugins/script_editor_plugin.h`
  - replace `edited_resourse` with `edited_resource` (private variable)
- [ ] `scene/main/node.h` declaration of `Node::replace_by`
  - replace `p_keep_data` with `p_keep_groups` (private API, inconsistency with .cpp and bound method name)
- [ ] `modules/lightmapper_rd/lightmapper_rd.cpp`
  - replace `lightprobes` with `light probes` (UI string)
- [ ] `core/string/translation.cpp` inside of `TranslationServer::setup()`
  - Add property hint `ProjectSettings::get_singleton()->set_custom_property_info(PropertyInfo(Variant::STRING, "internationalization/locale/test", PROPERTY_HINT_LOCALE_ID, ""));`

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by LunarTides** [comment]
Can you add this to the tracker?

https://github.com/godotengine/godot/blob/96a386f3c424af96d950ee5098b4b0e4907c9508/doc/classes/DisplayServer.xml#L1753

```diff
-Transient window is will be destroyed...
+Transient window will be destroyed...
```

**Comment by tetrapod00** [comment]
Grammar issues:
Likely intended to be "...representing a GLTF accessor...": https://github.com/godotengine/godot/blob/96a386f3c424af96d950ee5098b4b0e4907c9508/modules/gltf/doc_classes/GLTFAccessor.xml#L7
Likely intended to be "...representing a GLTF bufferView...": 
https://github.com/godotengine/godot/blob/96a386f3c424af96d950ee5098b4b0e4907c9508/modules/gltf/doc_classes/GLTFBufferView.xml#L7

**Comment by tetrapod00** [comment]
Many uses of `camelCase` instead of `snake_case` in this function:
https://github.com/godotengine/godot/blob/e4e024ab88efe74677769395886bc1b09eccbac7/editor/plugins/visual_shader_editor_plugin.cpp#L3306

**Comment by EAinsley** [comment]
There are a lot of string concatenations that should be changed to `vformat` as suggested in the [documentation](https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/common_engine_methods_and_macros.html#format-a-string). Maybe we should add this into the tracker as well?

**Comment by RedMser** [comment]
> Maybe we should add this into the tracker as well?

Not sure if there is an easy way to find all these occurrences across the repository. But indeed these are the kind of changes that shouldn't be done as tiny PRs that change 1 place, but rather one large PR that fixes this on a broader scale, so it makes sense to do it together with tiny typo fixes like those listed here.

**Comment by AThousandShips** [comment]
One thing to search for would be: `" + String` it won't necessarily be very narrow or complete but it'd catch a lot I suspect, I'll take a look at some fixes myself

**Comment by EAinsley** [comment]
That would be too laborious. It would be better if someone just fix a little bit when they saw those code while working on a big commit and commit them alongside.

**Comment by AThousandShips** [comment]
If it touches the area sure, but only then, but these changes are best handled systematically

**Comment by akien-mga** [comment]
All currently listed typos / minor issues should be handled by #99799.

**Comment by Calinou** [comment]
<img width="393" height="75" alt="Image" src="https://github.com/user-attachments/assets/450da06a-d3ba-4929-a42c-92452537df23" />

"Physical location" should use title case here ("Physical Location").

**Comment by tomsterBG** [comment]
<img width="1083" height="228" alt="Image" src="https://github.com/user-attachments/assets/c98a0ca0-6586-42bc-b011-5813beb5aeed" />

`Node.find_children()` should say "descendants" instead of "ancestors".

**Comment by fstxz** [comment]
https://github.com/godotengine/godot/blob/816ec99355ef404451b30eb9a87fe450a3d09a14/doc/classes/FoldableContainer.xml#L50

"becomes" -> "become" (or remove the first "will", I don't know what is more correct)

https://github.com/godotengine/godot/blob/9dde5688a566775df338df8ae7023cb69b6cfe6d/platform/macos/export/export_plugin.cpp#L1087

Remove one ">" at the end

**Comment by LateNightIceCream** [comment]
https://github.com/godotengine/godot/blob/816ec99355ef404451b30eb9a87fe450a3d09a14/doc/classes/Resource.xml#L169

"[...] relative to **the this** resource's scene"

Remove "the" or "this"

**Comment by tomsterBG** [comment]
# Entries that have been fixed and shall be removed from the tracker (https://github.com/godotengine/godot/pull/116543):
- "Physical location" -> "Physical Location"
https://github.com/godotengine/godot/blob/df6235838b63dd49f448547406e339848455c140/editor/settings/input_event_configuration_dialog.cpp#L810
https://github.com/godotengine/godot/blob/df6235838b63dd49f448547406e339848455c140/editor/settings/input_event_configuration_dialog.cpp#L820
- "bi" -> "bit" in ustring (can't find line, but searching for bi gives no results)
- Array.xml: "countary" -> "contrary"
https://github.com/godotengine/godot-docs/issues/11452#issuecomment-3844754743
- "becomes" -> "become" (or remove "will")
https://github.com/godotengine/godot/blob/df6235838b63dd49f448547406e339848455c140/doc/classes/FoldableContainer.xml#L48
- Remove ">" at the end https://github.com/godotengine/godot/blob/df6235838b63dd49f448547406e339848455c140/platform/macos/export/export_plugin.cpp#L1178
- "[...] relative to the this resource's scene" (remove the or this)
https://github.com/godotengine/godot/blob/df6235838b63dd49f448547406e339848455c140/doc/classes/Resource.xml#L175
- Node.xml: Node.find_children() "If type is not empty, only ancestors ..." should say "descendants" instead of "ancestors". (yay! this is the one i had found before)
https://github.com/godotengine/godot/blob/df6235838b63dd49f448547406e339848455c140/doc/classes/Node.xml#L309

**Comment by dalexeev** [comment]
`BoneAttachment3D.xml` and `ModifierBoneTarget3D.xml` contain Cyrillic `А` instead of Latin `A`.

`doc/classes/BoneAttachment3D.xml`

```diff
@@ -1,7 +1,7 @@
 <?xml version="1.0" encoding="UTF-8" ?>
 <class name="BoneAttachment3D" inherits="Node3D" api_type="core" keywords="tag" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
 	<brief_description>
-		А node that dynamically copies or overrides the 3D transform of a bone in its parent [Skeleton3D].
+		A node that dynamically copies or overrides the 3D transform of a bone in its parent [Skeleton3D].
 	</brief_description>
 	<description>
 		This node selects a bone in a [Skeleton3D] and attaches to it. This means that the [BoneAttachment3D] node will either dynamically copy or override the 3D transform of the selected bone.
```

`doc/classes/ModifierBoneTarget3D.xml`

```diff
@@ -1,7 +1,7 @@
 <?xml version="1.0" encoding="UTF-8" ?>
 <class name="ModifierBoneTarget3D" inherits="SkeletonModifier3D" api_type="core" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
 	<brief_description>
-		А node that dynamically copies the 3D transform of a bone in its parent [Skeleton3D].
+		A node that dynamically copies the 3D transform of a bone in its parent [Skeleton3D].
 	</brief_description>
 	<description>
 		This node selects a bone in a [Skeleton3D] and attaches to it. This means that the [ModifierBoneTarget3D] node will dynamically copy the 3D transform of the selected bone.
```

**Comment by williamchange** [comment]
Extra space in this comment

https://github.com/godotengine/godot/blob/f964fa714f503bd063b96f6194eb3e45355c1084/platform/visionos/display_server_visionos.mm#L92

**Comment by Calinou** [comment]
"Create C# solution" should be "Create C# Solution" here:

<img width="944" height="118" alt="Image" src="https://github.com/user-attachments/assets/368b2772-8c45-4a27-8b2a-62eb934a6919" />
