### ISSUE TITLE
[TRACKER] GPU/driver-specific issues

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#9444]
This tracker lists GPU driver-specific issues that affect the new renderer in Godot 3.x.

- [x] OpenGL error: GL_INVALID_OPERATION in DisableVertexAttribArray [intel, Windows] #7906
- [x] Stream of errors when enabling refraction and SSS [radeon, Windows] #9139 
- [x] GL error spam when using a viewport (Sampler object 0 is bound to non-depth texture 0) [nvidia, Linux] #9335
- [x] OpenGL fragment and vertex shader error spam [nvidia, Windows] #9434
- [x] graphical issues with material_tester demo [intel, Linux] #9525
- [x] Poor performance on Intel GPUs #9725
- [x] Scenes with 3D nodes do not start on Android with Adreno 3xx GPU #12816

**Comment by vnen** [comment]
I have #7906 and #9139. I assume they're driver related too.

**Comment by alibix** [comment]
I have #7906 when I try to use 3.0 - the same stream of errors that make the application unusable as it becomes very slow.

`ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1282        Severity: High  Message: Error has been generated. GL error GL_INVALID_OPERATION in DisableVertexAttribArray: (ID: 3860911800) Generic error
   At: drivers/gles3/rasterizer_gles3.cpp:123`

**Comment by tagcup** [comment]
#9725 maybe?

**Comment by LikeLakers2** [comment]
#7906 and #9525 are fixed.

**Comment by reduz** [comment]
This will probably be solvable mostly in 3.2

**Comment by akien-mga** [comment]
All these issues are fixed, so closing.

That doesn't mean that there aren't any GPU specific issues left, but this tracker has outlived its initial purpose.
