### ISSUE TITLE
[TRACKER] Direct3D 12 rendering driver issues

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#95775]
### Tested versions

This is a tracker for issues related to the Direct3D 12 (D3D12) rendering driver.

```[tasklist]
### Bugs
- [ ] https://github.com/godotengine/godot/issues/94251
- [ ] https://github.com/godotengine/godot/issues/95053
- [ ] https://github.com/godotengine/godot/issues/95619
- [ ] https://github.com/godotengine/godot/issues/95767
```

```[tasklist]
### Enhancements
- [ ] https://github.com/godotengine/godot-proposals/issues/10078
```

### System information

x

### Issue description

x

### Steps to reproduce

x

### Minimal reproduction project (MRP)

x

**Comment by TokisanGames** [comment]
Please add https://github.com/godotengine/godot/issues/98527 to the list.

**Comment by Bonkahe** [comment]
Probably #102192 is warranting of being on this list?

**Comment by allenwp** [comment]
I'm having a hard time finding any issues tracking "Device does NOT support GPU UPLOAD heap." and "PSO caching is not implemented yet", so I created an issue here: https://github.com/godotengine/godot/issues/113238
