### ISSUE TITLE
[TRACKER] Rendering issues with deep scenes

### ISSUE THREAD

**Issue by Flarkk** [godotengine/godot#98655]
### Tested versions

-

### System information

-

### Issue description

This is a tracker dedicated to issues experienced when rendering **deep scenes**, i.e. scenes involving very large camera far distance, very large and very far away geometry, lights with very long range, and all kinds of very large numbers in general.

This kind of scene is very common in **space settled games**, **open words**, **at-scale planets**, and similar applications.
Godot currently offers a rather low level of support for this kind of applications, due to the many places **numerical precision issues** arise.

Sometimes those issues can be worked around with the double precision build, but many actually involve a combination of floating point precision issues in the shaders as well, which makes double precision in the core engine of little help.

*Note : applications involving deep scenes rendering usually come along with other related requirements like floating origin management, quadtree / octree scene partitioning or resource streaming. These are broader concerns than specific rendering issues and should not be tracked here.*

Feel free to comment on this thread if you've identified or resolved issues not yet mentioned below !

### Camera
 - [ ] https://github.com/godotengine/godot-proposals/issues/10515 (#95944)
 - [ ] Camera far distance is limited to `1000000` (1 million) in editor

### Lighting
 - [ ] Very far away point lights get culled (#98641)
 - [ ] Shadows are broken on very far away geometry
   - [ ] #81877

### Shading
 - [ ] `VIEW` is `NaN` on very far away fragments (#95944)

### Geometry
 - [ ] Very large built-in sphere primitives have wrong normals (#98610)

### Steps to reproduce

-

### Minimal reproduction project (MRP)

-

**Comment by roalyr** [comment]
I've gathered al my tweaks in a single commit for 4.x : https://github.com/godotengine/godot/compare/master...roalyr:godot-for-3d-open-worlds:master and for 3.x: https://github.com/godotengine/godot/compare/3.x...roalyr:godot-for-3d-open-worlds:3.x
Just in case. I also think it is worth adding editor tweaks to the list (scene camera and in-game camera limits, editor zooming speed, grid and gizmos rendering precision, and so on).

**Comment by Zireael07** [comment]
Nit: I'd change the title to be "very large", as "deep" usually refers to the scene tree's complexity

**Comment by CodeSmith32** [comment]
Around 1 million units from the origin, large amounts of snapping and popping occur in the standard Godot build.

https://github.com/user-attachments/assets/977958e3-f17a-476d-8f6f-b775ffdcbae0

Short of using the double-precision build of Godot and the [two-float breakdown trick described here](https://godotengine.org/article/emulating-double-precision-gpu-render-large-worlds/#the-real-solution), there is only one workaround I know, but it does significantly increase the complexity of most projects (it also doesn't work in the editor, though that's slightly less important):

1. Move the world, not the camera.
2. Use multiple layers of coordinates for computing the player's 'virtual' position (really, the world's negative position).
  - e.g., Use one Vector3 for coordinates within a 4,096^3 unit region, and a Vector3i which indicates which region the player is in.

Unfortunately, this is much easier said than done:
- Placing everything under a node and simply setting the node's position to the camera's negative position will probably have a similar effect on movement (and naturally so, since the float-based transform hits the same limits).
- Worse (please correct me if I'm wrong), in my experience, moving the world seriously screws with Godot's physics engine. Since physics run in a separate thread, I believe, when moving the world, sometimes only half the objects' physical bodies move within a physics frame. Thus, using any kind of snapping or jumping - like wrapping the player camera in a cell indexed by a Vector3i, and jumping the world when wrap occurs - would cause bodies to collide when they shouldn't, and at times that are unpredictable and very difficult to track.

**Comment by Flarkk** [comment]
@CodeSmith32 you're indeed pointing out the right two options :
- use the double-precision build
- or implement a "floating origin" system, i.e. leave the camera near the origin and move the rest of the world instead

The latter cannot be implemented by putting everything under a node and moving it to the camera's negative location. As you pointed out it would lead to the same numerical precision issues.

The simplest valid implementation I can think of is to derive a custom node type from `Node3D` that stores its real-world position as 3 `float` member variables (note that the `float` type is always 64 bits even in the single-precision build). Each frame, this node uses these 3 `float` to compute its relative real-world vector to the camera (another instance of this custom node also using 3 `floats` for positioning) and moves all its children accordingly using their built-in position. Create as much of these custom nodes as needed and parent your scene's objects to them with respect to their desired real-world position (assign objects that are too far apart to distinct parents).

If you're using physics, you'll have to provide a mechanism that ensures that this custom node type updates its physics children through their `_integrate_forces()` method. This is where you can access their `PhysicsDirectBodyState3D` and safely change their `transform` to arbitrary values without side effect.

**Comment by ARez2** [comment]
My issue ( #111521 ) might be related, but not sure

**Comment by CodeSmith32** [comment]
> or implement a "floating origin" system, i.e. leave the camera near the origin and move the rest of the world instead

@Flarkk, I have yet to try this solution, but it sounds promising!
